// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class AccesoMensaje
    {
        [Key]
        [Column("MensajeID")]
        public int MensajeId { get; set; }
        [Required]
        [StringLength(300)]
        [Unicode(false)]
        public string Mensaje { get; set; }
        [Column("DepartamentoID")]
        public short? DepartamentoId { get; set; }
        /// <summary>
        /// Nro Lejajo como empleado
        /// </summary>
        [Column("EmpleadoID")]
        public int? EmpleadoId { get; set; }
        [Column("TurnoID")]
        public short? TurnoId { get; set; }
        public DateTime FechaAlta { get; set; }
        public DateTime ValidoDesdeFecha { get; set; }
        public DateTime ValidoHastaFecha { get; set; }

        [ForeignKey("DepartamentoId")]
        [InverseProperty("AccesoMensaje")]
        public virtual Departamento Departamento { get; set; }
        [ForeignKey("EmpleadoId")]
        [InverseProperty("AccesoMensaje")]
        public virtual Empleado Empleado { get; set; }
        [ForeignKey("TurnoId")]
        [InverseProperty("AccesoMensaje")]
        public virtual Turno Turno { get; set; }
    }
}