// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_AutorizacionCompraEstado_Descripcion")]
    public partial class AutorizacionCompraEstado
    {
        public AutorizacionCompraEstado()
        {
            AutorizacionCompra = new HashSet<AutorizacionCompra>();
        }

        [Key]
        [Column("AutCompraEstadoID")]
        public short AutCompraEstadoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public bool InHabilitado { get; set; }

        [InverseProperty("AutCompraEstado")]
        public virtual ICollection<AutorizacionCompra> AutorizacionCompra { get; set; }
    }
}