// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Permite llebar registro de las conciliaciones bancarias/Tarjetas Realizadas
    /// </summary>
    [Index("BancoTarjetaId", Name = "IX_BancoTarjetaConciliacion_BancoTarjetaID")]
    [Index("DesdeFecha", Name = "IX_BancoTarjetaConciliacion_DesdeFecha")]
    [Index("HastaFecha", Name = "IX_BancoTarjetaConciliacion_HastaFecha")]
    public partial class BancoTarjetaConciliacion
    {
        public BancoTarjetaConciliacion()
        {
            BancoTarjetaDebe = new HashSet<BancoTarjetaDebe>();
            BancoTarjetaHaber = new HashSet<BancoTarjetaHaber>();
        }

        [Key]
        [Column("ConciliacionID")]
        public int ConciliacionId { get; set; }
        /// <summary>
        /// Periodo Fecha Desde
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime DesdeFecha { get; set; }
        /// <summary>
        /// Periodo Fecha Hasta
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime HastaFecha { get; set; }
        /// <summary>
        /// Saldo Inicial
        /// </summary>
        [Column(TypeName = "money")]
        public decimal SaldoInicial { get; set; }
        /// <summary>
        /// Cuenta de Banco o Tarjeta
        /// </summary>
        [Column("BancoTarjetaID")]
        public int BancoTarjetaId { get; set; }
        /// <summary>
        /// Conciliacion anterior de la que se obiene el saldo Inicial 
        /// </summary>
        [Column("ConciliacionAnteriorID")]
        public int ConciliacionAnteriorId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }
        public int? Liquidac { get; set; }

        [ForeignKey("BancoTarjetaId")]
        [InverseProperty("BancoTarjetaConciliacion")]
        public virtual BancoTarjeta BancoTarjeta { get; set; }
        [InverseProperty("Conciliacion")]
        public virtual ICollection<BancoTarjetaDebe> BancoTarjetaDebe { get; set; }
        [InverseProperty("Conciliacion")]
        public virtual ICollection<BancoTarjetaHaber> BancoTarjetaHaber { get; set; }
    }
}