// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class BancoTarjetaHaberLiquidacion
    {
        public BancoTarjetaHaberLiquidacion()
        {
            BancoTarjetaHaber = new HashSet<BancoTarjetaHaber>();
        }

        [Key]
        [Column("LiquidBancoID")]
        public int LiquidBancoId { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        public byte[] Archivo { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("BancoTarjetaHaberLiquidacion")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("BancoTarjetaHaberLiquidacion")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("BancoTarjetaHaberLiquidacion")]
        public virtual Sucursal Sucursal { get; set; }
        [InverseProperty("LiquidBanco")]
        public virtual ICollection<BancoTarjetaHaber> BancoTarjetaHaber { get; set; }
    }
}