// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Determina todos los Empleados q estan bajo un determinado Capataz
    /// </summary>
    public partial class BasculaCapatazCuadrilla
    {
        public BasculaCapatazCuadrilla()
        {
            BasculaPesajeLiquidDetalle = new HashSet<BasculaPesajeLiquidDetalle>();
        }

        [Key]
        [Column("CuadrilleroID")]
        public int CuadrilleroId { get; set; }
        [Column("CapatazID")]
        public int CapatazId { get; set; }
        /// <summary>
        /// Nro Sucursal/Entidad
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        /// <summary>
        /// 0=Tumba; 1=Arrastra; 2=Carga
        /// </summary>
        [Column("TipoID")]
        public byte? TipoId { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal ImporteComision { get; set; }
        public bool Inhabilitado { get; set; }
        /// <summary>
        /// 0-No aplica 1-repite Cantidad TIkete Bascula, 2-Dsglosa la cantidad por cada empleado (la suma del desglose del ticket tiene q coincidir con la del ticket)
        /// </summary>
        public byte? TipoCalculo { get; set; }

        [ForeignKey("CapatazId")]
        [InverseProperty("BasculaCapatazCuadrilla")]
        public virtual BasculaCapataz Capataz { get; set; }
        [ForeignKey("EntidadSucId")]
        [InverseProperty("BasculaCapatazCuadrilla")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [InverseProperty("Cuadrillero")]
        public virtual ICollection<BasculaPesajeLiquidDetalle> BasculaPesajeLiquidDetalle { get; set; }
    }
}