// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Precio q se paga lote de donde estan sacando la Madera, quue se paga al conductor
    /// </summary>
    public partial class BasculaEntidadSucursal
    {
        public BasculaEntidadSucursal()
        {
            BasculaPesaje = new HashSet<BasculaPesaje>();
            BasculaPesajeLiquid = new HashSet<BasculaPesajeLiquid>();
        }

        [Key]
        public int RegEntidadSucBas { get; set; }
        /// <summary>
        /// Nro Sucursal/Entidad
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        /// <summary>
        /// Coeficiente a Aplicar para el calculo descueto/recargo
        /// </summary>
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? CoeficAjusteCantidad { get; set; }
        /// <summary>
        /// 0-Inhabilitado 1-Ingreso 2-Salida (Valor Binario)
        /// </summary>
        public byte TipoRegistroBascula { get; set; }
        [Column(TypeName = "decimal(12, 3)")]
        public decimal? ImporteComision { get; set; }
        [Column("NroOperadorINYM")]
        public int? NroOperadorInym { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("BasculaEntidadSucursal")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [InverseProperty("RegEntidadSucBasNavigation")]
        public virtual ICollection<BasculaPesaje> BasculaPesaje { get; set; }
        [InverseProperty("RegEntidadSucBasNavigation")]
        public virtual ICollection<BasculaPesajeLiquid> BasculaPesajeLiquid { get; set; }
    }
}