// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class BasculaOperador
    {
        public BasculaOperador()
        {
            BasculaPesaje = new HashSet<BasculaPesaje>();
        }

        [Key]
        [Column("OperBasculaID")]
        public short OperBasculaId { get; set; }
        [Column("EmpleadoID")]
        public int EmpleadoId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [ForeignKey("EmpleadoId")]
        [InverseProperty("BasculaOperador")]
        public virtual Empleado Empleado { get; set; }
        [InverseProperty("OperBascula")]
        public virtual ICollection<BasculaPesaje> BasculaPesaje { get; set; }
    }
}