// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class BasculaPesajeLiquidDetalle
    {
        [Column("kilos", TypeName = "decimal(12, 4)")]
        public decimal? Kilos { get; set; }
        [Key]
        [Column("PesajeDetID")]
        public int PesajeDetId { get; set; }
        [Column("BasaculaLiqID")]
        public int BasaculaLiqId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("CuadrilleroID")]
        public int CuadrilleroId { get; set; }

        [ForeignKey("BasaculaLiqId")]
        [InverseProperty("BasculaPesajeLiquidDetalle")]
        public virtual BasculaPesajeLiquid BasaculaLiq { get; set; }
        [ForeignKey("CuadrilleroId")]
        [InverseProperty("BasculaPesajeLiquidDetalle")]
        public virtual BasculaCapatazCuadrilla Cuadrillero { get; set; }
    }
}