// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class BasculaCapataz
    {
        public BasculaCapataz()
        {
            BasculaCapatazCuadrilla = new HashSet<BasculaCapatazCuadrilla>();
            BasculaPesaje = new HashSet<BasculaPesaje>();
            BasculaPesajeLiquid = new HashSet<BasculaPesajeLiquid>();
        }

        [Key]
        [Column("CapatazID")]
        public int CapatazId { get; set; }
        /// <summary>
        /// Nro Sucursal/Entidad
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        public bool Inhabilitado { get; set; }
        [Column("NroOperadorINYM")]
        public int? NroOperadorInym { get; set; }
        [Column(TypeName = "decimal(12, 3)")]
        public decimal? ImporteComision { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("BasculaCapataz")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [InverseProperty("Capataz")]
        public virtual ICollection<BasculaCapatazCuadrilla> BasculaCapatazCuadrilla { get; set; }
        [InverseProperty("Capataz")]
        public virtual ICollection<BasculaPesaje> BasculaPesaje { get; set; }
        [InverseProperty("Capataz")]
        public virtual ICollection<BasculaPesajeLiquid> BasculaPesajeLiquid { get; set; }
    }
}