// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_ClienteClasificacion_Descripcion")]
    public partial class ClienteClasificacion
    {
        public ClienteClasificacion()
        {
            Cliente = new HashSet<Cliente>();
            ClienteDescuento = new HashSet<ClienteDescuento>();
            OperacionCreditoPlanesPago = new HashSet<OperacionCreditoPlanesPago>();
        }

        [Key]
        [Column("ClasificacionID")]
        public int ClasificacionId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string ClasificacionHierarchy { get; set; }

        [InverseProperty("Clasificacion")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [InverseProperty("Clasificacion")]
        public virtual ICollection<ClienteDescuento> ClienteDescuento { get; set; }
        [InverseProperty("Clasificacion")]
        public virtual ICollection<OperacionCreditoPlanesPago> OperacionCreditoPlanesPago { get; set; }
    }
}