// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoEntidadId", "ClienteId", Name = "IX_Cliente", IsUnique = true)]
    [Index("CanalId", Name = "IX_Cliente_CanalID")]
    [Index("ClasificacionId", Name = "IX_Cliente_ClasificacionID")]
    [Index("EntidadSucId", Name = "IX_Cliente_EntidadSucID", IsUnique = true)]
    [Index("FormaPagoId", Name = "IX_Cliente_FormaPagoID")]
    [Index("Inhabilitado", Name = "IX_Cliente_Inhabilitado")]
    [Index("ListaPrecId", Name = "IX_Cliente_ListaPrecID")]
    [Index("SupervisorId", Name = "IX_Cliente_SupervisorID")]
    public partial class Cliente
    {
        public Cliente()
        {
            ClienteDescuento = new HashSet<ClienteDescuento>();
            ClienteRepresentada = new HashSet<ClienteRepresentada>();
            ClienteVendedor = new HashSet<ClienteVendedor>();
            LibroDiarioItem = new HashSet<LibroDiarioItem>();
            OperacionCobro = new HashSet<OperacionCobro>();
            OperacionCobroWeb = new HashSet<OperacionCobroWeb>();
            OperacionCredito = new HashSet<OperacionCredito>();
            OperacionDespacho = new HashSet<OperacionDespacho>();
            OperacionPedidoVenta = new HashSet<OperacionPedidoVenta>();
            OperacionPedidoVentaWeb = new HashSet<OperacionPedidoVentaWeb>();
            OperacionVenta = new HashSet<OperacionVenta>();
            OrdenServicio = new HashSet<OrdenServicio>();
            PlanDeCuentaInventarioConsignacion = new HashSet<PlanDeCuentaInventarioConsignacion>();
            PlanDeCuentaInventarioConsignacionAsignacion = new HashSet<PlanDeCuentaInventarioConsignacionAsignacion>();
            ProduccionOrden = new HashSet<ProduccionOrden>();
            ProductoHotelRestReserva = new HashSet<ProductoHotelRestReserva>();
            Proyecto = new HashSet<Proyecto>();
            Servis = new HashSet<Servis>();
            SoporteCaso = new HashSet<SoporteCaso>();
            SoporteClienteConecxion = new HashSet<SoporteClienteConecxion>();
            TransporteCarga = new HashSet<TransporteCarga>();
            TransporteContrareembolso = new HashSet<TransporteContrareembolso>();
            TransporteCrtC15clienteIddestinoNavigation = new HashSet<TransporteCrt>();
            TransporteCrtC15clienteIdorigenNavigation = new HashSet<TransporteCrt>();
            TransporteMandado = new HashSet<TransporteMandado>();
            TransporteRemitos = new HashSet<TransporteRemitos>();
            TransporteViaje = new HashSet<TransporteViaje>();
            UnidadFacturacion = new HashSet<UnidadFacturacion>();
        }

        /// <summary>
        /// Codigo Cliente
        /// </summary>
        [Key]
        [Column("ClienteID")]
        public int ClienteId { get; set; }
        /// <summary>
        /// EntidadSucursal a la q pertenece
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        /// <summary>
        /// Canal de Venta
        /// </summary>
        [Column("CanalID")]
        public int? CanalId { get; set; }
        /// <summary>
        /// Lista de Precio q utiliza
        /// </summary>
        [Column("ListaPrecID")]
        public short? ListaPrecId { get; set; }
        /// <summary>
        /// Detalle adicional para la Entrega,
        /// </summary>
        [StringLength(100)]
        [Unicode(false)]
        public string DatosDeEntrega { get; set; }
        /// <summary>
        /// Indica si esta Inhabilitado
        /// </summary>
        public bool Inhabilitado { get; set; }
        /// <summary>
        /// Clasificacion del Cliente
        /// </summary>
        [Column("ClasificacionID")]
        public int? ClasificacionId { get; set; }
        /// <summary>
        /// Viene de AlmaNET EntidadTipo utilizado para relacionar con registro de Operaciones (1)
        /// </summary>
        [Required]
        [Column("TipoEntidadID")]
        public byte? TipoEntidadId { get; set; }
        /// <summary>
        /// Fecha Alta
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        /// <summary>
        /// Refiere a si la entrega es Semanl, menual, etc
        /// </summary>
        public byte? TipoEntrega { get; set; }
        /// <summary>
        /// Binario q indica los dias de la Seman/Mes q se realiza la entrega
        /// </summary>
        public int? DiaEntrega { get; set; }
        /// <summary>
        /// Indicar la forma de pago utilizada por defecto al  realizar la venta se obtiene de OperacionFormaPago
        /// </summary>
        [Column("FormaPagoID")]
        public short? FormaPagoId { get; set; }
        public bool? RespetarObsVenta { get; set; }
        public byte[] Logo { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? PorcentajeGuia { get; set; }
        /// <summary>
        /// Indicar la forma de pago utilizada por defecto al  realizar un COBRO se obtiene de OperacionFormaPago
        /// </summary>
        [Column("FormaPagoIDCobro")]
        public short? FormaPagoIdcobro { get; set; }
        /// <summary>
        /// Indica q al realizar ventas muestra el saldo de Operaciones anteriroes, aplica a Impresion Facturas, toma Pedidos, etc
        /// </summary>
        public bool? MuestraSaldoVentas { get; set; }
        /// <summary>
        /// N° de Sucursal que atiende a este cliente (default)
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        /// <summary>
        /// Descuento tomar para las operaciones de venta
        /// </summary>
        [Column(TypeName = "decimal(5, 2)")]
        public decimal? DescuentoVenta { get; set; }
        /// <summary>
        /// Sector en que se asento esta Compra
        /// </summary>
        [Column("SectorID")]
        public short? SectorId { get; set; }
        /// <summary>
        /// Indica el limite de credito asignado al Cliente
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? LimiteCredito { get; set; }
        /// <summary>
        /// Codigo Unico De cuenta
        /// </summary>
        [Column("AdelantoCuentaID")]
        public int? AdelantoCuentaId { get; set; }
        public bool? CreadoEnTerminal { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Link1 { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Link2 { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string DatosCobro { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string DatosVenta { get; set; }
        [Column("ModVentaID")]
        public byte? ModVentaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UltimoAvisoSaldo { get; set; }
        [Column("VendedorIDPrincipal")]
        public int? VendedorIdprincipal { get; set; }
        [Column("EntidadSucIDSupervisor")]
        public int? EntidadSucIdsupervisor { get; set; }
        [Column("SupervisorID")]
        public int? SupervisorId { get; set; }
        public byte? GestionCtaCte { get; set; }

        [ForeignKey("AdelantoCuentaId")]
        [InverseProperty("Cliente")]
        public virtual PlanDeCuenta AdelantoCuenta { get; set; }
        [ForeignKey("CanalId")]
        [InverseProperty("Cliente")]
        public virtual ClienteCanal Canal { get; set; }
        [ForeignKey("ClasificacionId")]
        [InverseProperty("Cliente")]
        public virtual ClienteClasificacion Clasificacion { get; set; }
        [ForeignKey("EntidadSucId")]
        [InverseProperty("Cliente")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [ForeignKey("FormaPagoId")]
        [InverseProperty("ClienteFormaPago")]
        public virtual OperacionFormaPago FormaPago { get; set; }
        [ForeignKey("FormaPagoIdcobro")]
        [InverseProperty("ClienteFormaPagoIdcobroNavigation")]
        public virtual OperacionFormaPago FormaPagoIdcobroNavigation { get; set; }
        [ForeignKey("ListaPrecId")]
        [InverseProperty("Cliente")]
        public virtual ProductoLista ListaPrec { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("Cliente")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("Cliente")]
        public virtual Sucursal Sucursal { get; set; }
        [ForeignKey("SupervisorId")]
        [InverseProperty("Cliente")]
        public virtual Supervisor Supervisor { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<ClienteDescuento> ClienteDescuento { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<ClienteRepresentada> ClienteRepresentada { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<ClienteVendedor> ClienteVendedor { get; set; }
        public virtual ICollection<LibroDiarioItem> LibroDiarioItem { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionCobro> OperacionCobro { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionCobroWeb> OperacionCobroWeb { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionCredito> OperacionCredito { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionDespacho> OperacionDespacho { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionPedidoVenta> OperacionPedidoVenta { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionPedidoVentaWeb> OperacionPedidoVentaWeb { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OperacionVenta> OperacionVenta { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<OrdenServicio> OrdenServicio { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<PlanDeCuentaInventarioConsignacion> PlanDeCuentaInventarioConsignacion { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<PlanDeCuentaInventarioConsignacionAsignacion> PlanDeCuentaInventarioConsignacionAsignacion { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<ProduccionOrden> ProduccionOrden { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<ProductoHotelRestReserva> ProductoHotelRestReserva { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<Servis> Servis { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<SoporteCaso> SoporteCaso { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<SoporteClienteConecxion> SoporteClienteConecxion { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<TransporteCarga> TransporteCarga { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<TransporteContrareembolso> TransporteContrareembolso { get; set; }
        [InverseProperty("C15clienteIddestinoNavigation")]
        public virtual ICollection<TransporteCrt> TransporteCrtC15clienteIddestinoNavigation { get; set; }
        [InverseProperty("C15clienteIdorigenNavigation")]
        public virtual ICollection<TransporteCrt> TransporteCrtC15clienteIdorigenNavigation { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<TransporteMandado> TransporteMandado { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<TransporteRemitos> TransporteRemitos { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<TransporteViaje> TransporteViaje { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<UnidadFacturacion> UnidadFacturacion { get; set; }
    }
}