// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ClienteDescuento
    {
        [Column("ClienteID")]
        public int ClienteId { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal Descuento { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string LeyendaAdicional { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaCierre { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        public bool? Inhabilitado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaModificacion { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImporteMinimo { get; set; }
        public byte? DiaOferta { get; set; }
        public bool? EsDescuentoLimite { get; set; }
        [Key]
        [Column("ClienteDescuentoID")]
        public int ClienteDescuentoId { get; set; }
        [Column("TipoDescuentoID")]
        public byte? TipoDescuentoId { get; set; }
        [Column("FormaPagoID")]
        public short? FormaPagoId { get; set; }
        [Column("CanalID")]
        public int? CanalId { get; set; }
        [Column("ClasificacionID")]
        public int? ClasificacionId { get; set; }

        [ForeignKey("CanalId")]
        [InverseProperty("ClienteDescuento")]
        public virtual ClienteCanal Canal { get; set; }
        [ForeignKey("ClasificacionId")]
        [InverseProperty("ClienteDescuento")]
        public virtual ClienteClasificacion Clasificacion { get; set; }
        [ForeignKey("ClienteId")]
        [InverseProperty("ClienteDescuento")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("FormaPagoId")]
        [InverseProperty("ClienteDescuento")]
        public virtual OperacionFormaPago FormaPago { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("ClienteDescuento")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("ClienteDescuento")]
        public virtual Sucursal Sucursal { get; set; }
    }
}