// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ClienteRepresentada
    {
        [Column("ClienteID")]
        public int ClienteId { get; set; }
        [Column("ProveedorID")]
        public int ProveedorId { get; set; }
        [Key]
        [Column("ClienteRepresentadaID")]
        public int ClienteRepresentadaId { get; set; }
        public int? NroClienteAsignado { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string CodigoClienteAlfa { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? CoficienteDeterminaNeto { get; set; }
        [Column("TipoComicionID")]
        public byte? TipoComicionId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Comision { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Descuento1 { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Descuento2 { get; set; }
        [Column("ListaPrecID")]
        public short? ListaPrecId { get; set; }
        public short? TipoBonificProducto { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("ClienteRepresentada")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("ProveedorId")]
        [InverseProperty("ClienteRepresentada")]
        public virtual Proveedor Proveedor { get; set; }
    }
}