// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ComunicadoModelo
    {
        [Key]
        [Column("ComunicadoID")]
        public int ComunicadoId { get; set; }
        [Unicode(false)]
        public string Cuerpo { get; set; }
        [Unicode(false)]
        public string Titulo { get; set; }
        [Column("TipoComunicadoID")]
        public short TipoComunicadoId { get; set; }
    }
}