// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("AnticipoId", Name = "IX_CuentaCorrienteAnticipoCancela_AnticipoID")]
    [Index("RegistroPagoId", Name = "IX_CuentaCorrienteAnticipoCancela_RegistroPagoID")]
    public partial class CuentaCorrienteAnticipoCancela
    {
        /// <summary>
        /// Campo Unico
        /// </summary>
        [Key]
        [Column("RegAntipoCancID")]
        public int RegAntipoCancId { get; set; }
        /// <summary>
        /// Importe q cancela
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImporteIngresa { get; set; }
        /// <summary>
        /// Operacion sobre la que se Realiza el Cancela (ver OpercionPagoDetalle--OperacionXXXXX)
        /// </summary>
        [Column("RegistroPagoID")]
        public int RegistroPagoId { get; set; }
        /// <summary>
        /// Descripcion Adicional
        /// </summary>
        [StringLength(250)]
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// ID Anticipo
        /// </summary>
        [Column("AnticipoID")]
        public int AnticipoId { get; set; }

        [ForeignKey("AnticipoId")]
        [InverseProperty("CuentaCorrienteAnticipoCancela")]
        public virtual CuentaCorrienteAnticipo Anticipo { get; set; }
        [ForeignKey("RegistroPagoId")]
        [InverseProperty("CuentaCorrienteAnticipoCancela")]
        public virtual OperacionDetallePago RegistroPago { get; set; }
    }
}