// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("RegistroOperacionId", Name = "IX_CuentaCorrienteAnticipo_RegistroOperacionID")]
    [Index("TipoOperacionId", Name = "IX_CuentaCorrienteAnticipo_TipoOperacionID")]
    public partial class CuentaCorrienteAnticipo
    {
        public CuentaCorrienteAnticipo()
        {
            CuentaCorrienteAnticipoCancela = new HashSet<CuentaCorrienteAnticipoCancela>();
        }

        /// <summary>
        /// Importe Anticipo
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImporteAnticipo { get; set; }
        /// <summary>
        /// Tipo Movimiento Que Genera el Anticipo, (Cobro o Pagos) de AlmaNET.OperacionTipo
        /// </summary>
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Nro Registro de la Operacion que Genera el Anticipo
        /// </summary>
        [Column("RegistroOperacionID")]
        public int RegistroOperacionId { get; set; }
        /// <summary>
        /// ID Anticipo
        /// </summary>
        [Key]
        [Column("AnticipoID")]
        public int AnticipoId { get; set; }
        /// <summary>
        /// Descripcion Sobre el Anticipo
        /// </summary>
        [StringLength(250)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("CuentaCorrienteAnticipo")]
        public virtual OperacionCobro OperacionCobro { get; set; }
        [InverseProperty("Anticipo")]
        public virtual ICollection<CuentaCorrienteAnticipoCancela> CuentaCorrienteAnticipoCancela { get; set; }
    }
}