// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Indica los Responsable deposito autorizado para hacer los despachos y recepciones
    /// </summary>
    [Index("EmpleadoId", Name = "IX_DepositoEncargado_EmpleadoID")]
    public partial class DepositoEncargado
    {
        public DepositoEncargado()
        {
            Deposito = new HashSet<Deposito>();
            DepositoEncargadoDeposito = new HashSet<DepositoEncargadoDeposito>();
            DepositoMovimiento = new HashSet<DepositoMovimiento>();
        }

        [Column("EmpleadoID")]
        public int EmpleadoId { get; set; }
        [Key]
        [Column("EncargDepositoID")]
        public int EncargDepositoId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Indica que modalidad Aplica para el Despacho 0-Permite Despacho Parcial 1-Solo despacho completo
        /// </summary>
        public byte ModalidadDespacho { get; set; }

        [ForeignKey("EmpleadoId")]
        [InverseProperty("DepositoEncargado")]
        public virtual Empleado Empleado { get; set; }
        [InverseProperty("EncargDeposito")]
        public virtual ICollection<Deposito> Deposito { get; set; }
        [InverseProperty("EncargDeposito")]
        public virtual ICollection<DepositoEncargadoDeposito> DepositoEncargadoDeposito { get; set; }
        [InverseProperty("EncargDeposito")]
        public virtual ICollection<DepositoMovimiento> DepositoMovimiento { get; set; }
    }
}