// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Rigistro de todas las faltas al trabjao de los distintos empleados
    /// </summary>
    [Index("Descripcion", Name = "IX_EmpleadoInasistencia_Descripcion")]
    [Index("EmpleadoId", Name = "IX_EmpleadoInasistencia_EmpleadoID")]
    public partial class EmpleadoInasistencia
    {
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Se obtiene de AlmaNET.InasistenciaTipo (1- enfermedad 2-Fallecimiento Familiar 3-Enfermedad Familiar en 1er Grado
        /// </summary>
        public short TipoInasistencia { get; set; }
        /// <summary>
        /// si es verdadero no se descuenta
        /// </summary>
        public bool Justificada { get; set; }
        /// <summary>
        /// Tipo unidad de Tiempo
        /// </summary>
        public byte TipoUnidadTiempo { get; set; }
        /// <summary>
        /// * Eliminar 
        /// </summary>
        public short CantidadTiempo { get; set; }
        [Column("EmpleadoID")]
        public int EmpleadoId { get; set; }
        /// <summary>
        /// Fecha/Dia que el empleado falto
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaInasistencia { get; set; }
        /// <summary>
        /// Una descripcion de cual fue la causa de la inasistencia
        /// </summary>
        [StringLength(200)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [ForeignKey("EmpleadoId")]
        [InverseProperty("EmpleadoInasistencia")]
        public virtual Empleado Empleado { get; set; }
    }
}