// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Indica el Listado de Preguntas Cuetionarios encuesta a relizar
    /// </summary>
    public partial class Encuesta
    {
        public Encuesta()
        {
            EncuestaOpcion = new HashSet<EncuestaOpcion>();
        }

        /// <summary>
        /// Indica la Pregunta a Realizar
        /// </summary>
        [Key]
        [Column("CustionarioID")]
        public int CustionarioId { get; set; }
        [StringLength(250)]
        public string Descripcion { get; set; }
        public byte? CantidRespuest { get; set; }
        public int? CuestionarioNro { get; set; }
        [Unicode(false)]
        public string Detalle { get; set; }

        [InverseProperty("Custionario")]
        public virtual ICollection<EncuestaOpcion> EncuestaOpcion { get; set; }
    }
}