// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class EncuestaOpcion
    {
        public EncuestaOpcion()
        {
            EncuestaRespuestaOpcion = new HashSet<EncuestaRespuestaOpcion>();
        }

        [Key]
        [Column("OpcionID")]
        public int OpcionId { get; set; }
        [Column("CustionarioID")]
        public int CustionarioId { get; set; }
        public short NroItemCuestionario { get; set; }
        public bool ArgumentaRespuesta { get; set; }
        public byte? ValorMin { get; set; }
        public byte? ValorMax { get; set; }

        [ForeignKey("CustionarioId")]
        [InverseProperty("EncuestaOpcion")]
        public virtual Encuesta Custionario { get; set; }
        [InverseProperty("Opcion")]
        public virtual ICollection<EncuestaRespuestaOpcion> EncuestaRespuestaOpcion { get; set; }
    }
}