// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EntidadSucId", Name = "IX_EntidadSucursalEvento_EntidadSucID")]
    [Index("RegEventoId", Name = "IX_EntidadSucursalEvento_RegEventoID")]
    public partial class EntidadSucursalEvento
    {
        /// <summary>
        /// Nro Sucursal/Entidad al q esta relacionado en caso de tener Relacion
        /// </summary>
        [Column("EntidadSucID")]
        public int? EntidadSucId { get; set; }
        [Column("RegEventoID")]
        public int RegEventoId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("EntidadSucursalEvento")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [ForeignKey("RegEventoId")]
        [InverseProperty("EntidadSucursalEvento")]
        public virtual Evento RegEvento { get; set; }
    }
}