// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EMail", Name = "IX_EntidadSucursalEmail_E_Mail")]
    [Index("EntidadSucId", Name = "IX_EntidadSucursalEmail_EntidadSucID")]
    [Index("EntidadSucId", "TipoEmailId", Name = "IX_EntidadSucursalEmail_SucursalID_tipoDomicID", IsUnique = true)]
    public partial class EntidadSucursalEmail
    {
        [Column("TipoEmailID")]
        public byte TipoEmailId { get; set; }
        [Required]
        [Column("E_Mail")]
        [StringLength(255)]
        [Unicode(false)]
        public string EMail { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Comentario { get; set; }
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        [Key]
        [Column("RegistroEmailID")]
        public int RegistroEmailId { get; set; }
        [Column("ContactoID")]
        public int? ContactoId { get; set; }
        public byte? EnvioAutomatico { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("EntidadSucursalEmail")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
    }
}