// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EntidadSucId", Name = "IX_EntidadSucursalTelefono_EntidadSucID")]
    [Index("EntidadSucId", "TipoTelefonoId", Name = "IX_EntidadSucursalTelefono_SucursID_TipoTelID", IsUnique = true)]
    [Index("TelefonoNro", Name = "IX_EntidadSucursalTelefono_TelefonoNro")]
    public partial class EntidadSucursalTelefono
    {
        public EntidadSucursalTelefono()
        {
            TransporteMandadoRegistroTelefonoIdconsNavigation = new HashSet<TransporteMandado>();
            TransporteMandadoRegistroTelefonoIdremNavigation = new HashSet<TransporteMandado>();
        }

        /// <summary>
        /// Indica tel de Trabajo, cel , casa, etc. se obtiene de AlmaNET.TelefonoTipo
        /// </summary>
        [Column("TipoTelefonoID")]
        public byte TipoTelefonoId { get; set; }
        /// <summary>
        /// Indicar el Nro de Telefono
        /// </summary>
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string TelefonoNro { get; set; }
        /// <summary>
        /// REferencia Con quien se comunica
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string Comentario { get; set; }
        public int CodigoArea { get; set; }
        /// <summary>
        /// Nro de Telefono Interno
        /// </summary>
        public int? ExtencionTel { get; set; }
        [Column("PaisID")]
        public short? PaisId { get; set; }
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        [Key]
        [Column("RegistroTelefonoID")]
        public int RegistroTelefonoId { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("EntidadSucursalTelefono")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [InverseProperty("RegistroTelefonoIdconsNavigation")]
        public virtual ICollection<TransporteMandado> TransporteMandadoRegistroTelefonoIdconsNavigation { get; set; }
        [InverseProperty("RegistroTelefonoIdremNavigation")]
        public virtual ICollection<TransporteMandado> TransporteMandadoRegistroTelefonoIdremNavigation { get; set; }
    }
}