// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Almacena las Imagenes /Fotografias relacionadas a esta EntidadSuxcursal
    /// </summary>
    [Index("EntidadSucId", Name = "IX_EntidadSucursalImagen_EntidadSucID")]
    public partial class EntidadSucursalImagen
    {
        /// <summary>
        /// Sucursal a la que esta relacionado
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Imagen Fotografia
        /// </summary>
        [Required]
        public byte[] Imagen { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Extencion { get; set; }
        /// <summary>
        /// Para el caso que para una Entidad se necesiten vincular varias imagenes estas se enumeran para facilitar su Sincronizacion
        /// </summary>
        public short? NroArchivo { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("EntidadSucursalImagen")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
    }
}