// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoDomicilioId", Name = "IX_EntidadSucursalDomicilio")]
    [Index("Domicilio", Name = "IX_EntidadSucursalDomicilio_Domicilio")]
    [Index("EntidadSucId", Name = "IX_EntidadSucursalDomicilio_EntidadSucID")]
    [Index("EntidadSucId", "TipoDomicilioId", Name = "IX_EntidadSucursalDomicilio_SucursID_TipoDomID", IsUnique = true)]
    public partial class EntidadSucursalDomicilio
    {
        public EntidadSucursalDomicilio()
        {
            TransporteMandadoRegistroDomicilioIdconsNavigation = new HashSet<TransporteMandado>();
            TransporteMandadoRegistroDomicilioIdremNavigation = new HashSet<TransporteMandado>();
        }

        /// <summary>
        /// Indica el Tipo Domicilio, ejem Particular, Trabajo, etc. viene de AlmaNet DomicilioTipo
        /// </summary>
        [Column("TipoDomicilioID")]
        public byte TipoDomicilioId { get; set; }
        /// <summary>
        /// Descripcion Domicilio
        /// </summary>
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Domicilio { get; set; }
        /// <summary>
        /// Codigo Ciudad Mediante la cual tambien se optiene Provincia y Pais al que pertenece el Domicilio
        /// </summary>
        [Column("CiudadID")]
        public int CiudadId { get; set; }
        /// <summary>
        /// EntidadSucursal de la que es el Domicilio
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        /// <summary>
        /// Campo UNICO
        /// </summary>
        [Key]
        [Column("RegistroDomicilioID")]
        public int RegistroDomicilioId { get; set; }
        /// <summary>
        /// Codenada Ubicacuion Geografica
        /// </summary>
        [Column(TypeName = "decimal(18, 13)")]
        public decimal? Latitud { get; set; }
        /// <summary>
        /// Codenada Ubicacuion Geografica
        /// </summary>
        [Column(TypeName = "decimal(18, 13)")]
        public decimal? Longitud { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string LinkDomicilio { get; set; }

        [ForeignKey("EntidadSucId")]
        [InverseProperty("EntidadSucursalDomicilio")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [InverseProperty("RegistroDomicilioIdconsNavigation")]
        public virtual ICollection<TransporteMandado> TransporteMandadoRegistroDomicilioIdconsNavigation { get; set; }
        [InverseProperty("RegistroDomicilioIdremNavigation")]
        public virtual ICollection<TransporteMandado> TransporteMandadoRegistroDomicilioIdremNavigation { get; set; }
    }
}