// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class EntidadAderente
    {
        [Column("EntidadID")]
        public int EntidadId { get; set; }
        [Required]
        [StringLength(350)]
        [Unicode(false)]
        public string ApellidoNombre { get; set; }
        public byte TipoNroIdentificacion { get; set; }
        public long NroIdentificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaNacimiento { get; set; }
        [Column("GrupoSangineoID")]
        public short? GrupoSangineoId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Sexo { get; set; }
        [Column("CiudadID")]
        public int? CiudadId { get; set; }
        [Key]
        [Column("AderenteID")]
        [StringLength(10)]
        public string AderenteId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaBaja { get; set; }
        [Column("AderenteTipoID")]
        public byte? AderenteTipoId { get; set; }
    }
}