// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_EventoClasificacion_Descripcion")]
    public partial class EventoClasificacion
    {
        public EventoClasificacion()
        {
            Evento = new HashSet<Evento>();
        }

        [Key]
        [Column("EventoClasificID")]
        public short EventoClasificId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// Valor de tablas de colores RGB
        /// </summary>
        public int Color { get; set; }
        /// <summary>
        /// Explicacion de Cuando se debe de aplicar esta clasificacion
        /// </summary>
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Cantidad Minutos antes a la fecha q se crea el Evento, para determinar FechaHoraAviso del Evento (Activa Avisar en evento)
        /// </summary>
        public int? AvisoMinutosAntes { get; set; }

        [InverseProperty("EventoClasific")]
        public virtual ICollection<Evento> Evento { get; set; }
    }
}