// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("RegPeriodoMensualId", "AvisoTipoId", Name = "IX_EventoMensual", IsUnique = true)]
    public partial class EventoMensual
    {
        public EventoMensual()
        {
            Evento = new HashSet<Evento>();
        }

        [Key]
        [Column("RegPeriodoMensualID")]
        public int RegPeriodoMensualId { get; set; }
        /// <summary>
        /// Define como valor un Tipo Aviso Mensual
        /// </summary>
        [Column("AvisoTipoID")]
        public byte AvisoTipoId { get; set; }
        /// <summary>
        /// Indicael dia del mes en q se repite el evento Ejem. Cada dia 20 del Mes
        /// </summary>
        public short RepetirCadaDia { get; set; }
        /// <summary>
        /// Se indica con valor cada Cuantos meses se tiene q repetir
        /// </summary>
        public byte DeCadalMes { get; set; }
        [Column(TypeName = "date")]
        public DateTime FechaInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime FechaFinal { get; set; }
        /// <summary>
        /// Indica cuantas veces se tiene q repetir el evento para considerarlo como Finalizado
        /// </summary>
        public int Repeticiones { get; set; }
        /// <summary>
        /// Indica q el Evento Fue Cancelado
        /// </summary>
        public bool? Cancelado { get; set; }
        /// <summary>
        /// Indica la Cantidad de Minutos q dura el Evento
        /// </summary>
        public int Duracion { get; set; }
        public int? DiaDeLaSemana { get; set; }
        public byte? DeLaSemana { get; set; }

        public virtual ICollection<Evento> Evento { get; set; }
    }
}