// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class FiscalAuditoria
    {
        [Key]
        [Column("AuditoriaID")]
        public int AuditoriaId { get; set; }
        [Column("PeriodoID")]
        public byte PeriodoId { get; set; }
        public byte Mes { get; set; }
        public short Año { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Sincronizado { get; set; }
        public int? Filer { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Fecha { get; set; }
        public long NroIdentificacion { get; set; }
        [Column("VentaXML", TypeName = "xml")]
        public string VentaXml { get; set; }
        [Column("ProductoXML", TypeName = "xml")]
        public string ProductoXml { get; set; }
        [Column("ClienteXML", TypeName = "xml")]
        public string ClienteXml { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Cargado { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
    }
}