// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("AnimalPiezaId", "TipificId", Name = "IX_FrigorificoPiezaEgresoProducto", IsUnique = true)]
    public partial class FrigorificoPiezaEgresoProducto
    {
        /// <summary>
        /// Campo unico q  indica la pieza especifica par un tipo de Animal
        /// </summary>
        [Column("AnimalPiezaID")]
        public int AnimalPiezaId { get; set; }
        /// <summary>
        /// Indica el Codigo de Tipificacion de la Pieza (Calidad de la Carne), que la asigan el tipificador
        /// </summary>
        [Column("TipificID")]
        public short TipificId { get; set; }
        [Key]
        [Column("RegPiezTipID")]
        public short RegPiezTipId { get; set; }
        /// <summary>
        /// Codigo Vinculado en Venta
        /// </summary>
        [Column("CodigoID")]
        public int CodigoId { get; set; }

        [ForeignKey("AnimalPiezaId")]
        [InverseProperty("FrigorificoPiezaEgresoProducto")]
        public virtual FrigorificoAnimalPieza AnimalPieza { get; set; }
        [ForeignKey("CodigoId")]
        [InverseProperty("FrigorificoPiezaEgresoProducto")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("TipificId")]
        [InverseProperty("FrigorificoPiezaEgresoProducto")]
        public virtual FrigorificoTipificacion Tipific { get; set; }
    }
}