// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class FrigorificoTropa
    {
        public FrigorificoTropa()
        {
            FrigorificoIngreso = new HashSet<FrigorificoIngreso>();
        }

        [Key]
        [Column("TropaID")]
        public int TropaId { get; set; }
        public short CantidadCabezas { get; set; }
        [StringLength(150)]
        public string Detalle { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? TotalKgVivo { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? TotalKgFaenado { get; set; }

        [InverseProperty("Tropa")]
        public virtual ICollection<FrigorificoIngreso> FrigorificoIngreso { get; set; }
    }
}