// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class FrigorificoEntidad
    {
        [Key]
        [Column("TipoEntidadID")]
        public byte TipoEntidadId { get; set; }
        [Key]
        [Column("NroEntidadID")]
        public int NroEntidadId { get; set; }
        /// <summary>
        /// N° Registro Único de la Cadena Agroalimentaria
        /// </summary>
        [Column("NroRUCA")]
        public int NroRuca { get; set; }
        /// <summary>
        /// 1-Productor/criador
        /// 2-Feed lots
        /// 3-Invernador
        /// 4-Establecimiento faenador y/o frigorífico
        /// 5-Consignatario y/o comisionista
        /// 6-Consignatario directo
        /// 7-Consignatario de Carnes
        /// 9-Matarife abastecedor y carnicero y usuario de faena
        /// </summary>
        [Column("TipoParticipanteID")]
        public byte TipoParticipanteId { get; set; }
        /// <summary>
        /// N° Registro Nacional Sanitario de Productores Agropecuarios
        /// </summary>
        [Column("NroRENSPA")]
        public int? NroRenspa { get; set; }

        public virtual Proveedor Proveedor { get; set; }
    }
}