// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoOperacionId", "HabitAuditId", Name = "IX_HotelHabitacionAuditoria", IsUnique = true)]
    public partial class HotelHabitacionAuditoria
    {
        public HotelHabitacionAuditoria()
        {
            HotelHabitacionAuditoriaItem = new HashSet<HotelHabitacionAuditoriaItem>();
            OperacionArchivo = new HashSet<OperacionArchivo>();
        }

        [Key]
        [Column("HabitAuditID")]
        public int HabitAuditId { get; set; }
        [Column("HabitacionID")]
        public int HabitacionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("HotelHabitacionAuditoria")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("HabitacionId")]
        [InverseProperty("HotelHabitacionAuditoria")]
        public virtual HotelSectorHabitacion Habitacion { get; set; }
        [InverseProperty("HabitAudit")]
        public virtual ICollection<HotelHabitacionAuditoriaItem> HotelHabitacionAuditoriaItem { get; set; }
        public virtual ICollection<OperacionArchivo> OperacionArchivo { get; set; }
    }
}