// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class HotelHabitacionAuditoriaItem
    {
        [Key]
        [Column("ItemAuditoriaID")]
        public int ItemAuditoriaId { get; set; }
        [Column("HabitAuditID")]
        public int HabitAuditId { get; set; }
        [Column("EstadoID")]
        public byte EstadoId { get; set; }
        [Column("OrdenSerID")]
        public int OrdenSerId { get; set; }
        [StringLength(150)]
        public string Detalle { get; set; }

        [ForeignKey("HabitAuditId")]
        [InverseProperty("HotelHabitacionAuditoriaItem")]
        public virtual HotelHabitacionAuditoria HabitAudit { get; set; }
        [ForeignKey("OrdenSerId")]
        [InverseProperty("HotelHabitacionAuditoriaItem")]
        public virtual OrdenServicioHabitacion OrdenSer { get; set; }
    }
}