// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// 1-Pulgar Derecho 2-Indice Derecho 3-Medio Derecho 4-Anular Derecho 5- Meñisco Derecho 6-Pulgar Izquierdo 7-Indice Izquierdo 8-Medio Izquierdo 9-Anular Izquierdo 10- Meñisco Izquierdo 
    /// </summary>
    [Index("TipoEntidadId", "RegistroEntidadId", "TipoHuella", Name = "IX_Huella", IsUnique = true)]
    public partial class Huella
    {
        [Column("TipoEntidadID")]
        public byte TipoEntidadId { get; set; }
        [Column("RegistroEntidadID")]
        public int RegistroEntidadId { get; set; }
        [Required]
        [Column("Huella")]
        public byte[] Huella1 { get; set; }
        /// <summary>
        /// 0-No Especifica 1-Pulgar Derecho 2-Indice Derecho 3-Corazon/Medio Dercho 4-Anular Derecho 5- Meñique Derecho 6-Pulgar Izquierdo 7-Indice Izquierdo 8-Corazon/Medio Izquierdo 9-Anular Izquierdo 10- Meñique Izquierdo
        /// </summary>
        public byte? TipoHuella { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
    }
}