// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ImpuestoFormulario
    {
        public ImpuestoFormulario()
        {
            ImpuestoFormularioLiquidacion = new HashSet<ImpuestoFormularioLiquidacion>();
        }

        [Key]
        [Column("ImpuestoFormularioID")]
        public int ImpuestoFormularioId { get; set; }
        public int Descripcion { get; set; }
        [Column("PresentacionTipoID")]
        public byte? PresentacionTipoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Vencimiento { get; set; }
        public byte? DiaVencimiento { get; set; }
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        [Column("TipoCalculoImpID")]
        public short TipoCalculoImpId { get; set; }
        [StringLength(120)]
        [Unicode(false)]
        public string FiltroSector { get; set; }
        [StringLength(120)]
        [Unicode(false)]
        public string FiltroSucursal { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("ImpuestoFormulario")]
        public virtual Usuario AlmaUser { get; set; }
        [InverseProperty("ImpuestoFormulario")]
        public virtual ICollection<ImpuestoFormularioLiquidacion> ImpuestoFormularioLiquidacion { get; set; }
    }
}