// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ImpuestoFormuarioLiquidacionDetalle
    {
        [Key]
        [Column("LiquidacionImpuestoItemID")]
        public int LiquidacionImpuestoItemId { get; set; }
        [Column("LiquidacionID")]
        public int LiquidacionId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Concepto { get; set; }
        [Column(TypeName = "money")]
        public decimal? Importe { get; set; }
        [Column("TipoConceptoID")]
        public short? TipoConceptoId { get; set; }

        [ForeignKey("LiquidacionId")]
        [InverseProperty("ImpuestoFormuarioLiquidacionDetalle")]
        public virtual ImpuestoFormularioLiquidacion Liquidacion { get; set; }
    }
}