// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class Informes
    {
        [Key]
        [Column("InformeID")]
        public int InformeId { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string ReportServerUrl { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string ReportPath { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ModeloInforme { get; set; }
        [Column("ArchivoXML", TypeName = "xml")]
        public string ArchivoXml { get; set; }
        [Column("FiltrosXML", TypeName = "xml")]
        public string FiltrosXml { get; set; }
        public bool? PresentacionVentana { get; set; }
        [Column(TypeName = "money")]
        public decimal? Alto { get; set; }
        [Column(TypeName = "money")]
        public decimal? Ancho { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Usuario { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Contrasena { get; set; }
    }
}