// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class LibroDiarioAgrupado
    {
        public LibroDiarioAgrupado()
        {
            LibroDiario = new HashSet<LibroDiario>();
        }

        [Key]
        [Column("DiarioAgrupID")]
        public int DiarioAgrupId { get; set; }
        public int? NroDiario { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string CondicionAgrupar { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Fecha { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("LibroDiarioAgrupado")]
        public virtual Usuario AlmaUser { get; set; }
        [InverseProperty("DiarioAgrup")]
        public virtual ICollection<LibroDiario> LibroDiario { get; set; }
    }
}