// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class MonedaTipo
    {
        public MonedaTipo()
        {
            BilletesDesglose = new HashSet<BilletesDesglose>();
            OperacionCompra = new HashSet<OperacionCompra>();
            OperacionFormaPago = new HashSet<OperacionFormaPago>();
            OperacionPedidoVenta = new HashSet<OperacionPedidoVenta>();
            OperacionRendicionPase = new HashSet<OperacionRendicionPase>();
            PlanDeCuenta = new HashSet<PlanDeCuenta>();
        }

        [Key]
        [Column("MonedaID")]
        public byte MonedaId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// Cotizacion Precio de Toma (Compra)
        /// </summary>
        [Column(TypeName = "money")]
        public decimal Cotizacion { get; set; }
        [StringLength(6)]
        [Unicode(false)]
        public string Abrebiatura { get; set; }
        [Column("MonedaIDER")]
        [StringLength(3)]
        [Unicode(false)]
        public string MonedaIder { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string Simbolo { get; set; }
        /// <summary>
        /// Cotizacion para la Venta
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? CotizacionVenta { get; set; }

        [InverseProperty("Moneda")]
        public virtual ICollection<BilletesDesglose> BilletesDesglose { get; set; }
        [InverseProperty("Moneda")]
        public virtual ICollection<OperacionCompra> OperacionCompra { get; set; }
        [InverseProperty("Moneda")]
        public virtual ICollection<OperacionFormaPago> OperacionFormaPago { get; set; }
        [InverseProperty("Moneda")]
        public virtual ICollection<OperacionPedidoVenta> OperacionPedidoVenta { get; set; }
        [InverseProperty("Moneda")]
        public virtual ICollection<OperacionRendicionPase> OperacionRendicionPase { get; set; }
        [InverseProperty("Moneda")]
        public virtual ICollection<PlanDeCuenta> PlanDeCuenta { get; set; }
    }
}