// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class NovedadRegistroTabla
    {
        [Key]
        [Column("RegNovedadID")]
        public int RegNovedadId { get; set; }
        public byte Proceso { get; set; }
        [Column(TypeName = "xml")]
        public string Detalle { get; set; }
        [Column("IDRegistroNovedad")]
        public int IdregistroNovedad { get; set; }
        [Column("TablaID")]
        public int TablaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        [StringLength(120)]
        public string NombreTabla { get; set; }
    }
}