// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoOperacionId", Name = "IX_MayorDetalle_TipoOperacionID")]
    [Index("ResumenId", Name = "IX_OperacionResumenDetalleResumenID")]
    public partial class OperacionResumenDetalle
    {
        /// <summary>
        /// Codigo Cuenta
        /// </summary>
        [Column("CuentaID")]
        public int CuentaId { get; set; }
        /// <summary>
        /// Importe 
        /// </summary>
        [Column(TypeName = "money")]
        public decimal Importe { get; set; }
        /// <summary>
        /// 1 Determina que el Importe es Deudor 0-Acreedor
        /// </summary>
        public bool EsDebe { get; set; }
        [Column("TipoOperacionID")]
        public byte? TipoOperacionId { get; set; }
        [Key]
        [Column("ResumenDetalleID")]
        public int ResumenDetalleId { get; set; }
        /// <summary>
        /// Nro de Resmun de Operaciones
        /// </summary>
        [Column("ResumenID")]
        public int ResumenId { get; set; }

        [ForeignKey("CuentaId")]
        [InverseProperty("OperacionResumenDetalle")]
        public virtual PlanDeCuenta Cuenta { get; set; }
        [ForeignKey("ResumenId")]
        [InverseProperty("OperacionResumenDetalle")]
        public virtual OperacionResumen Resumen { get; set; }
    }
}