// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionRendicionPase
    {
        /// <summary>
        /// Nro Reparto Planilla de Carga
        /// </summary>
        [Column("RendicionID")]
        public int RendicionId { get; set; }
        /// <summary>
        /// Codigo Unico De cuenta
        /// </summary>
        [Column("CuentaID")]
        public int? CuentaId { get; set; }
        /// <summary>
        /// Codigo Unico De cuenta
        /// </summary>
        [Column("CuentaIDPase")]
        public int CuentaIdpase { get; set; }
        /// <summary>
        /// De MonedaTipo
        /// </summary>
        [Column("MonedaID")]
        public byte? MonedaId { get; set; }
        /// <summary>
        /// Se optiene de AlmaNET PagoRegistroTipo (Especifica la reistracion a realizar segun Forma Pago)Contado, Cuenta Corriente, Banco, Adelanto,Cheque Tercero, Credito Etc.
        /// </summary>
        [Column("PagoTipoRegistroID")]
        public byte PagoTipoRegistroId { get; set; }
        [Column(TypeName = "money")]
        public decimal? CantidadMonedaOrigen { get; set; }
        [Column(TypeName = "money")]
        public decimal? CotizacionDia { get; set; }
        [Column(TypeName = "money")]
        public decimal? Importe { get; set; }
        /// <summary>
        /// Indico cuenta Ajuste (no aplica asiento sobre CuentaID)
        /// </summary>
        [Column("CuentaIDAjuste")]
        public int? CuentaIdajuste { get; set; }
        [Key]
        [Column("OperRendPaseID")]
        public int OperRendPaseId { get; set; }

        [ForeignKey("CuentaId")]
        [InverseProperty("OperacionRendicionPaseCuenta")]
        public virtual PlanDeCuenta Cuenta { get; set; }
        [ForeignKey("CuentaIdajuste")]
        [InverseProperty("OperacionRendicionPaseCuentaIdajusteNavigation")]
        public virtual PlanDeCuenta CuentaIdajusteNavigation { get; set; }
        [ForeignKey("CuentaIdpase")]
        [InverseProperty("OperacionRendicionPaseCuentaIdpaseNavigation")]
        public virtual PlanDeCuenta CuentaIdpaseNavigation { get; set; }
        [ForeignKey("MonedaId")]
        [InverseProperty("OperacionRendicionPase")]
        public virtual MonedaTipo Moneda { get; set; }
        [ForeignKey("RendicionId")]
        [InverseProperty("OperacionRendicionPase")]
        public virtual OperacionRendicion Rendicion { get; set; }
    }
}