// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("AlmaUserId", Name = "IX_OperacionVale_AlmaUserID")]
    [Index("EntidadSucId", Name = "IX_OperacionVale_EntidadSucID")]
    [Index("EsDeudor", Name = "IX_OperacionVale_EsDeudor")]
    [Index("EstadoId", Name = "IX_OperacionVale_EstadoID")]
    [Index("Fecha", Name = "IX_OperacionVale_Fecha")]
    [Index("FechaExpiracion", Name = "IX_OperacionVale_FechaExpiracion")]
    [Index("Filer", Name = "IX_OperacionVale_Filer")]
    [Index("Importe", Name = "IX_OperacionVale_Importe")]
    [Index("ImporteGastado", Name = "IX_OperacionVale_ImporteGastado")]
    [Index("NroComprobante", Name = "IX_OperacionVale_NroComprobante")]
    [Index("ProyectoId", Name = "IX_OperacionVale_ProyectoID")]
    [Index("Saldo", Name = "IX_OperacionVale_Saldo")]
    [Index("SectorId", Name = "IX_OperacionVale_SectorID")]
    [Index("SucursalId", Name = "IX_OperacionVale_SucursalID")]
    [Index("TalonarioId", Name = "IX_OperacionVale_TalonarioID")]
    [Index("TipoEntidadId", Name = "IX_OperacionVale_TipoEntidadID")]
    [Index("TipoOperacionId", Name = "IX_OperacionVale_TipoOperacionID")]
    public partial class OperacionVale
    {
        public OperacionVale()
        {
            OperacionValeCancelacion = new HashSet<OperacionValeCancelacion>();
            OperacionValeContra = new HashSet<OperacionValeContra>();
        }

        [Key]
        [Column("ValeID")]
        public int ValeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Column(TypeName = "money")]
        public decimal Importe { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        /// <summary>
        /// Tipo de comprobante utilizado (Ver indica vale)
        /// </summary>
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        /// <summary>
        /// Nro Talonario al que pertenece la Numeracion del comprobante
        /// </summary>
        [Column("TalonarioID")]
        public short TalonarioId { get; set; }
        /// <summary>
        /// Nro de comprobante / Se repite por ComprobnateID y Nro de Punto de Venta
        /// </summary>
        public int NroComprobante { get; set; }
        /// <summary>
        /// Nro de Sucursal de la Empresa q realizo la operacion
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        /// <summary>
        /// Se indica cualquier detalle y/u observacion sobre este Vale
        /// </summary>
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Sector que realizo la operacion
        /// </summary>
        [Column("SectorID")]
        public short? SectorId { get; set; }
        /// <summary>
        /// Codigo Proyecto
        /// </summary>
        [Column("ProyectoID")]
        public short? ProyectoId { get; set; }
        /// <summary>
        /// 0-Vale No genrado 1-Generado 2-Utilizado 3-Sin Credito  10-Cancelado
        /// </summary>
        [Column("EstadoID")]
        public byte? EstadoId { get; set; }
        /// <summary>
        /// 0-Si es para Venta 1-Para Compra
        /// </summary>
        public bool EsDeudor { get; set; }
        /// <summary>
        /// 1-Cliente 2-Proveedor
        /// </summary>
        [Column("TipoEntidadID")]
        public byte TipoEntidadId { get; set; }
        /// <summary>
        /// Indica hasta Fecha se puede utilizar (null- no tiene limites)
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? FechaExpiracion { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Nro Sucursal/Entidad
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImporteGastado { get; set; }
        /// <summary>
        /// Casmpu Calculado ImporteVale-ImporteGastado-Importe Contravale
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? Saldo { get; set; }
        public int? Filer { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionVale")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("EntidadSucId")]
        [InverseProperty("OperacionVale")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [ForeignKey("ProyectoId")]
        [InverseProperty("OperacionVale")]
        public virtual Proyecto Proyecto { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("OperacionVale")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("OperacionVale")]
        public virtual Sucursal Sucursal { get; set; }
        [InverseProperty("Vale")]
        public virtual ICollection<OperacionValeCancelacion> OperacionValeCancelacion { get; set; }
        [InverseProperty("Vale")]
        public virtual ICollection<OperacionValeContra> OperacionValeContra { get; set; }
    }
}