// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Autorizacion de ingreso a Depsoito
    /// </summary>
    [Index("FechaHora", Name = "IX_OperacionRecepcion")]
    [Index("ComprobanteId", Name = "IX_OperacionRecepcion_ComprobanteID")]
    [Index("DepositoId", Name = "IX_OperacionRecepcion_DepositoID")]
    [Index("NroComprobante", Name = "IX_OperacionRecepcion_NroComprobante")]
    [Index("ProveedorId", Name = "IX_OperacionRecepcion_ProveedorID")]
    [Index("RecepcionId", Name = "IX_OperacionRecepcion_RecepcionID", IsUnique = true)]
    [Index("TalonarioId", Name = "IX_OperacionRecepcion_TalonarioID")]
    [Index("TipoOperacionId", Name = "IX_OperacionRecepcion_TipoOperacionID")]
    public partial class OperacionRecepcion
    {
        public OperacionRecepcion()
        {
            BasculaPesaje = new HashSet<BasculaPesaje>();
            DepositoMovimiento = new HashSet<DepositoMovimiento>();
            OperacionArchivo = new HashSet<OperacionArchivo>();
            OperacionInterDeposito = new HashSet<OperacionInterDeposito>();
            OperacionRecepcionCodigoNoHallado = new HashSet<OperacionRecepcionCodigoNoHallado>();
            OperacionRecepcionItem = new HashSet<OperacionRecepcionItem>();
            OperacionRelacionOperacion = new HashSet<OperacionRelacionOperacion>();
        }

        /// <summary>
        /// Nro Recepcion
        /// </summary>
        [Key]
        [Column("RecepcionID")]
        public int RecepcionId { get; set; }
        /// <summary>
        /// Fecha y hora de la Recepcion
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        [Column("ProveedorID")]
        public int? ProveedorId { get; set; }
        /// <summary>
        /// Detalle q refiere a esta Recepcion
        /// </summary>
        [StringLength(250)]
        [Unicode(false)]
        public string DetalleRecepcion { get; set; }
        /// <summary>
        /// 21-Recepcion
        /// </summary>
        [Key]
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Column("DepositoID")]
        public short DepositoId { get; set; }
        /// <summary>
        /// Utilizado para grabar datos para comparacion otras base de datos (Ejem.Aldema)
        /// </summary>
        public int? Filer { get; set; }
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        [Column("TalonarioID")]
        public short TalonarioId { get; set; }
        public int NroComprobante { get; set; }
        /// <summary>
        /// Sector que realizo la Venta
        /// </summary>
        [Column("SectorID")]
        public short? SectorId { get; set; }
        /// <summary>
        /// Nro de Sucursal de la Empresa q realizo la venta
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        /// <summary>
        /// Codigo Proyecto
        /// </summary>
        [Column("ProyectoID")]
        public short? ProyectoId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        /// <summary>
        /// DispositivoID que tomo la recepcion(utilizado para identificar si fue ingresado desde AlmaMobile y de q dispositibo (Ver AlmaNET.UsuarioAlmaMobile)
        /// </summary>
        [Column("AlmaMobileID")]
        public int? AlmaMobileId { get; set; }
        [Column(TypeName = "money")]
        public decimal? Total { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionRecepcion")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("DepositoId")]
        [InverseProperty("OperacionRecepcion")]
        public virtual Deposito Deposito { get; set; }
        [ForeignKey("ProveedorId")]
        [InverseProperty("OperacionRecepcion")]
        public virtual Proveedor Proveedor { get; set; }
        [ForeignKey("ProyectoId")]
        [InverseProperty("OperacionRecepcion")]
        public virtual Proyecto Proyecto { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("OperacionRecepcion")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("OperacionRecepcion")]
        public virtual Sucursal Sucursal { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual OperacionAltaModicacion OperacionAltaModicacion { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<BasculaPesaje> BasculaPesaje { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<DepositoMovimiento> DepositoMovimiento { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<OperacionArchivo> OperacionArchivo { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<OperacionInterDeposito> OperacionInterDeposito { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<OperacionRecepcionCodigoNoHallado> OperacionRecepcionCodigoNoHallado { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<OperacionRecepcionItem> OperacionRecepcionItem { get; set; }
        [InverseProperty("OperacionRecepcion")]
        public virtual ICollection<OperacionRelacionOperacion> OperacionRelacionOperacion { get; set; }
    }
}