// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionItemProductoPedidoCompraReposicion
    {
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? CantidadPiezas { get; set; }
        [Column(TypeName = "decimal(13, 4)")]
        public decimal Cantidad { get; set; }
        [Column("PresentacionID")]
        public short PresentacionId { get; set; }
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        [Key]
        [Column("ReposicionID")]
        public int ReposicionId { get; set; }
        [Column("RegistroPedidoCompraID")]
        public int? RegistroPedidoCompraId { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("DepositoID")]
        public short? DepositoId { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Fecha { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        public byte? EstadoPedido { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("CodigoId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("DepositoId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual Deposito Deposito { get; set; }
        [ForeignKey("PresentacionId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual ProductoPresentacionTipo Presentacion { get; set; }
        [ForeignKey("RegistroPedidoCompraId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual OperacionItemProductoPedidoCompra RegistroPedidoCompra { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("OperacionItemProductoPedidoCompraReposicion")]
        public virtual Sucursal Sucursal { get; set; }
    }
}