// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("DespachoId", "ItemDespachoEstadoId", Name = "DespachoIDItemDespachoEstadoIDInc")]
    [Index("CodigoId", Name = "IX_OperacionDespachoItem_CodigoID")]
    [Index("ItemDespachoEstadoId", Name = "IX_OperacionDespachoItem_DespachoEstadoID")]
    [Index("DespachoId", Name = "IX_OperacionDespachoItem_DespachoID")]
    [Index("PresentacionId", Name = "IX_OperacionDespachoItem_PresentacionID")]
    [Index("TipoItem", "ItemDespchId", Name = "IX_TipoItem_ItemDespchID", IsUnique = true)]
    public partial class OperacionDespachoItem
    {
        public OperacionDespachoItem()
        {
            OperacionDespachoItemDetalleDevolucionItemDespch = new HashSet<OperacionDespachoItemDetalle>();
            OperacionDespachoItemDetalleItemDespch = new HashSet<OperacionDespachoItemDetalle>();
            OperacionPedidoCompraDespachoItem = new HashSet<OperacionPedidoCompraDespachoItem>();
            ProductoNroSerieMovimiento = new HashSet<ProductoNroSerieMovimiento>();
        }

        /// <summary>
        /// N° Despacho
        /// </summary>
        [Column("DespachoID")]
        public int DespachoId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal Cantidad { get; set; }
        /// <summary>
        /// Campo unico que indica el Item de un despacho
        /// </summary>
        [Key]
        [Column("ItemDespchID")]
        public int ItemDespchId { get; set; }
        /// <summary>
        /// Codigo Producto
        /// </summary>
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        /// <summary>
        /// Tipo de Presentacion del Producto (Caja-Unidades- etc.)
        /// </summary>
        [Column("PresentacionID")]
        public short PresentacionId { get; set; }
        /// <summary>
        /// Unidades que contiene la presentacion al momento del registro
        /// </summary>
        [Column(TypeName = "decimal(12, 4)")]
        public decimal UnidadesContiene { get; set; }
        /// <summary>
        /// 0-Normal 10-No Posee Venta 20-Error Despacho Indica si Estdo de Proseso Item despachado
        /// </summary>
        [Column("ItemDespachoEstadoID")]
        public byte? ItemDespachoEstadoId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Filer { get; set; }
        /// <summary>
        /// Precio promedio Ponderado (utilizado para asignar un valor al item despachado
        /// </summary>
        [Column("PrecioPP", TypeName = "money")]
        public decimal? PrecioPp { get; set; }
        /// <summary>
        /// Indica q es un item despacho (11)  o Repecion (21)  (utilizado para relacionar con ProductoNroSeriMovimiento
        /// </summary>
        public byte TipoItem { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Permite indicar o explicar sobre el item despachado
        /// </summary>
        [StringLength(300)]
        public string DetalleItemDespacho { get; set; }
        [Column("ListaPrecID")]
        public short? ListaPrecId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? CantidadPiezas { get; set; }

        [ForeignKey("CodigoId")]
        [InverseProperty("OperacionDespachoItem")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("ItemDespachoEstadoId")]
        [InverseProperty("OperacionDespachoItem")]
        public virtual OperacionDespachoEstado ItemDespachoEstado { get; set; }
        [ForeignKey("ListaPrecId")]
        [InverseProperty("OperacionDespachoItem")]
        public virtual ProductoLista ListaPrec { get; set; }
        [ForeignKey("TipoOperacionId,DespachoId")]
        [InverseProperty("OperacionDespachoItem")]
        public virtual OperacionDespacho OperacionDespacho { get; set; }
        [ForeignKey("PresentacionId")]
        [InverseProperty("OperacionDespachoItem")]
        public virtual ProductoPresentacionTipo Presentacion { get; set; }
        [InverseProperty("DevolucionItemDespch")]
        public virtual ICollection<OperacionDespachoItemDetalle> OperacionDespachoItemDetalleDevolucionItemDespch { get; set; }
        [InverseProperty("ItemDespch")]
        public virtual ICollection<OperacionDespachoItemDetalle> OperacionDespachoItemDetalleItemDespch { get; set; }
        [InverseProperty("ItemDespch")]
        public virtual ICollection<OperacionPedidoCompraDespachoItem> OperacionPedidoCompraDespachoItem { get; set; }
        public virtual ICollection<ProductoNroSerieMovimiento> ProductoNroSerieMovimiento { get; set; }
    }
}