// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Table("OperacionCompraCAEA")]
    public partial class OperacionCompraCaea
    {
        public OperacionCompraCaea()
        {
            OperacionCompra = new HashSet<OperacionCompra>();
        }

        [Key]
        [Column("CAEA_ID")]
        public int CaeaId { get; set; }
        [Required]
        [Column("CAEA")]
        [StringLength(20)]
        [Unicode(false)]
        public string Caea { get; set; }
        [Column("CAEAFechaVto", TypeName = "datetime")]
        public DateTime CaeafechaVto { get; set; }
        [Column("CAEAFechaSol", TypeName = "datetime")]
        public DateTime CaeafechaSol { get; set; }
        [Column("CAEADesde")]
        public int? Caeadesde { get; set; }
        [Column("CAEAHasta")]
        public int? Caeahasta { get; set; }
        [Column("CAEAFechaDesde", TypeName = "datetime")]
        public DateTime? CaeafechaDesde { get; set; }
        [Column("CAEAFechaHasta", TypeName = "datetime")]
        public DateTime? CaeafechaHasta { get; set; }
        public byte? Quincena { get; set; }
        public int? Periodo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Informado { get; set; }
        [Column("ValidadoID")]
        public byte? ValidadoId { get; set; }

        [InverseProperty("Caea")]
        public virtual ICollection<OperacionCompra> OperacionCompra { get; set; }
    }
}