// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Leyenda", Name = "IX_OperacionItemProductoLeyenda_Leyenda")]
    [Index("LeyendaItemId", Name = "IX_OperacionItemProductoLeyenda_LeyendaItemID")]
    public partial class OperacionItemProductoLeyenda
    {
        [Key]
        [Column("ItemLeyendaID")]
        public int ItemLeyendaId { get; set; }
        [Column("LeyendaItemID")]
        public int LeyendaItemId { get; set; }
        [Required]
        [StringLength(320)]
        [Unicode(false)]
        public string Leyenda { get; set; }
        public bool? ReemplazaDesc { get; set; }

        [ForeignKey("LeyendaItemId")]
        [InverseProperty("OperacionItemProductoLeyenda")]
        public virtual OperacionItemProducto LeyendaItem { get; set; }
    }
}