// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("ItemId", Name = "IX_OperacionItemProductoVentaComisEspec", IsUnique = true)]
    public partial class OperacionItemProductoVentaComisEspec
    {
        [Key]
        [Column("RegComisEspID")]
        public int RegComisEspId { get; set; }
        [Column("ItemID")]
        public int ItemId { get; set; }
        [Column("EntidadSucIDGestor")]
        public int? EntidadSucIdgestor { get; set; }
        [Column("EntidadSucIDSupervisor")]
        public int? EntidadSucIdsupervisor { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PorcComisGestor { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PorcComisSupervisor { get; set; }
        [Column("TipoOperacionIDLiqSupervisor")]
        public byte? TipoOperacionIdliqSupervisor { get; set; }
        [Column("CompraIDLiqSupervisor")]
        public int? CompraIdliqSupervisor { get; set; }
        [Column("TipoOperacionIDLiqGestor")]
        public byte? TipoOperacionIdliqGestor { get; set; }
        [Column("CompraIDLiqGestor")]
        public int? CompraIdliqGestor { get; set; }
        [Column("SupervisorID")]
        public int? SupervisorId { get; set; }

        [ForeignKey("EntidadSucIdgestor")]
        [InverseProperty("OperacionItemProductoVentaComisEspec")]
        public virtual EntidadSucursal EntidadSucIdgestorNavigation { get; set; }
        [ForeignKey("ItemId")]
        [InverseProperty("OperacionItemProductoVentaComisEspec")]
        public virtual OperacionItemProducto Item { get; set; }
        [ForeignKey("TipoOperacionIdliqGestor,CompraIdliqGestor")]
        [InverseProperty("OperacionItemProductoVentaComisEspecOperacionCompra")]
        public virtual OperacionCompra OperacionCompra { get; set; }
        [ForeignKey("TipoOperacionIdliqSupervisor,CompraIdliqSupervisor")]
        [InverseProperty("OperacionItemProductoVentaComisEspecOperacionCompraNavigation")]
        public virtual OperacionCompra OperacionCompraNavigation { get; set; }
        [ForeignKey("SupervisorId")]
        [InverseProperty("OperacionItemProductoVentaComisEspec")]
        public virtual Supervisor Supervisor { get; set; }
    }
}