// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionRecepcionItemVentaItem
    {
        /// <summary>
        /// Operacion Liquido Producto Nro
        /// </summary>
        [Key]
        public int RegistroLiq { get; set; }
        [Column("ItemRecepID")]
        public int ItemRecepId { get; set; }
        /// <summary>
        /// Cantidad, Puede estar expresado hasta con 4 decimales
        /// </summary>
        [Column(TypeName = "decimal(13, 4)")]
        public decimal CantidadVenta { get; set; }
        /// <summary>
        /// Item Unico del detalle
        /// </summary>
        [Column("ItemID")]
        public int? ItemId { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column(TypeName = "money")]
        public decimal? Comision { get; set; }
        [Column("LiquidoProductoID")]
        public int LiquidoProductoId { get; set; }

        [ForeignKey("ItemId")]
        [InverseProperty("OperacionRecepcionItemVentaItem")]
        public virtual OperacionItemProducto Item { get; set; }
        [ForeignKey("ItemRecepId")]
        [InverseProperty("OperacionRecepcionItemVentaItem")]
        public virtual OperacionRecepcionItem ItemRecep { get; set; }
        [ForeignKey("LiquidoProductoId")]
        [InverseProperty("OperacionRecepcionItemVentaItem")]
        public virtual OperacionLiquidoProducto LiquidoProducto { get; set; }
    }
}