// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionComisionImpuesto
    {
        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [Column(TypeName = "decimal(8, 3)")]
        public decimal? PorcImpuesto { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImpImpuesto { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImportUnitario { get; set; }
        public byte EstaModificado { get; set; }
        [Column("PagoCimisionID")]
        public int PagoCimisionId { get; set; }

        [ForeignKey("ImpuestoId")]
        [InverseProperty("OperacionComisionImpuesto")]
        public virtual Impuesto Impuesto { get; set; }
        [ForeignKey("PagoCimisionId")]
        [InverseProperty("OperacionComisionImpuesto")]
        public virtual OperacionComisionCompra PagoCimision { get; set; }
    }
}