// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Permite llebar el registro del ultimo nro utilizado en cada talonario por cada comprobante y operacion, Empresa
    /// </summary>
    [Index("TipoOperacionId", "ComprobanteId", "TalonarioId", "EmpresaId", Name = "IX_OperacionTalonarioNumeracion", IsUnique = true)]
    [Index("ComprobanteId", Name = "IX_OperacionTalonarioNumeracion_ComprobanteID")]
    [Index("TalonarioId", Name = "IX_OperacionTalonarioNumeracion_TalonarioID")]
    public partial class OperacionTalonarioNumeracion
    {
        public OperacionTalonarioNumeracion()
        {
            OperacionPedidoVenta = new HashSet<OperacionPedidoVenta>();
            OperacionRegistroUsoComprobantes = new HashSet<OperacionRegistroUsoComprobantes>();
            OperacionRegistroUsoTalonario = new HashSet<OperacionRegistroUsoTalonario>();
        }

        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        public int UltimoNroIngresado { get; set; }
        /// <summary>
        /// Nro Talonario al que pertenece la Numeracion del comprobante
        /// </summary>
        [Column("TalonarioID")]
        public short TalonarioId { get; set; }
        [Key]
        [Column("RegistroTalonarioID")]
        public int RegistroTalonarioId { get; set; }
        /// <summary>
        /// Tipo Movimiento al que pertenece (Ventas,Compras,Pagod,Cobros) de AlmaNET.OperacionTipo
        /// </summary>
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Indico empresa en la que se utilizo el talonario
        /// </summary>
        [Column("EmpresaID")]
        public int? EmpresaId { get; set; }
        public bool InHabilitado { get; set; }
        /// <summary>
        /// 1-Utiliza Facturacion Electronica y Autoenumera y asigna la fecha comprobante al informar a la afip 10- Utiliza Facturacion Electronica NO Autoenumera 50-Impresor Fiscal 100-Indicar q el talonario Solo permite editar sin modificar la numeracion y no utilizado para cargar nuevos registros
        /// </summary>
        public byte UsaFacturaElectronica { get; set; }
        /// <summary>
        /// Indica el nombre reporte a utilizar por defecto
        /// </summary>
        [StringLength(250)]
        public string NombreReporteUtilizar { get; set; }
        /// <summary>
        /// Indica el Modelo reporte a Utilizar (segun TipoOperacionID)
        /// </summary>
        [Column("ModeRporteID")]
        public short? ModeRporteId { get; set; }
        /// <summary>
        /// Indica el Ultimo nro  q esta autorizado dentro de este talonario (No debe autorizar nro mayor al valor ingresado n caso q se distinto de null)
        /// </summary>
        public int? UltimoNroAutorizado { get; set; }
        /// <summary>
        /// Indica la cantidad minima de pendientes q tiene q tener antesdel llegar al UltimoNroAutorizado, utilizado para solicitar la impresion de nuevos talonarios
        /// </summary>
        public int? CantidadPendientesMin { get; set; }
        [Column("ControladorFiscalID")]
        public int? ControladorFiscalId { get; set; }
        public short? CantidadItems { get; set; }
        /// <summary>
        /// Nro Proveedor q utiliza como representada 
        /// </summary>
        [Column("ProveedorID")]
        public int? ProveedorId { get; set; }
        /// <summary>
        /// Indica que este talonario solo puede facturar productos que no corresponden a ninguna representada 
        /// </summary>
        public bool? ProductosSinRepresentada { get; set; }
        [StringLength(250)]
        public string Impresora { get; set; }
        [Column("CertiAFIP_ID")]
        public short? CertiAfipId { get; set; }
        [Column("RegistroEncTalonID")]
        public int? RegistroEncTalonId { get; set; }

        [ForeignKey("CertiAfipId")]
        [InverseProperty("OperacionTalonarioNumeracion")]
        public virtual EmpresaCertificadoAfip CertiAfip { get; set; }
        [ForeignKey("ControladorFiscalId")]
        [InverseProperty("OperacionTalonarioNumeracion")]
        public virtual OperacionControladorFiscal ControladorFiscal { get; set; }
        [ForeignKey("ProveedorId")]
        [InverseProperty("OperacionTalonarioNumeracion")]
        public virtual Proveedor Proveedor { get; set; }
        [ForeignKey("RegistroEncTalonId")]
        [InverseProperty("OperacionTalonarioNumeracion")]
        public virtual OperacionTalonarioEncabezado RegistroEncTalon { get; set; }
        [InverseProperty("RegistroTalonario")]
        public virtual ICollection<OperacionPedidoVenta> OperacionPedidoVenta { get; set; }
        [InverseProperty("RegistroTalonario")]
        public virtual ICollection<OperacionRegistroUsoComprobantes> OperacionRegistroUsoComprobantes { get; set; }
        [InverseProperty("RegistroTalonario")]
        public virtual ICollection<OperacionRegistroUsoTalonario> OperacionRegistroUsoTalonario { get; set; }
    }
}