// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionTransporte
    {
        [Key]
        [Column("RegtranspID")]
        public int RegtranspId { get; set; }
        /// <summary>
        /// Nro de Conductor/Chofer
        /// </summary>
        [Column("ConductorID")]
        public int? ConductorId { get; set; }
        /// <summary>
        /// 1- Flete en Origen 10- Flete en Destino
        /// </summary>
        public byte? TipoFlete { get; set; }
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }
        /// <summary>
        /// Nro Registro de la Operacion a la que se ingresa la Leyenda
        /// </summary>
        [Column("RegistroOperacionID")]
        public int RegistroOperacionId { get; set; }
        /// <summary>
        /// Tipo Operacion a la que se le Ingresa la Leyenda
        /// </summary>
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// 75-CoRemito ,Tipo de comprobante utilizado para registro y control trasnporte
        /// </summary>
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        /// <summary>
        /// Nro Talonario al que pertenece la Numeracion del comprobante
        /// </summary>
        [Column("TalonarioID")]
        public short? TalonarioId { get; set; }
        /// <summary>
        /// Nro de comprobante / Se repite por ComprobnateID y Nro de Punto de Venta
        /// </summary>
        public int? NroComprobante { get; set; }
        [Unicode(false)]
        public string DetalleRemito { get; set; }

        [ForeignKey("ConductorId")]
        [InverseProperty("OperacionTransporte")]
        public virtual TransporteConductor Conductor { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionTransporte")]
        public virtual OperacionCompra OperacionCompra { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionTransporte")]
        public virtual OperacionPedidoCompra OperacionPedidoCompra { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionTransporte")]
        public virtual OperacionVenta OperacionVenta { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("OperacionTransporte")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
    }
}