// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionCobroWebImagen
    {
        [Key]
        [Column("CobroImagID")]
        public int CobroImagId { get; set; }
        public byte[] Archivo { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Extencion { get; set; }
        [StringLength(250)]
        public string Descripcion { get; set; }
        [Column("CobroWebID")]
        public int CobroWebId { get; set; }

        [ForeignKey("CobroWebId")]
        [InverseProperty("OperacionCobroWebImagen")]
        public virtual OperacionCobroWeb CobroWeb { get; set; }
    }
}