// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Utilizado para Indicar los productos reservados, para no considerarlos en el stock
    /// </summary>
    [Index("CodigoId", Name = "IX_OperacionItemProductoReservado_CodigoID")]
    [Index("EstadoReservaId", Name = "IX_OperacionItemProductoReservado_EstadoReservaID")]
    [Index("ItemIdpedido", Name = "IX_OperacionItemProductoReservado_ItemID")]
    [Index("ItemPedidoId", Name = "IX_OperacionItemProductoReservado_ItemPedidoID")]
    [Index("PresentacionId", Name = "IX_OperacionItemProductoReservado_PresentacionID")]
    public partial class OperacionItemProductoReservado
    {
        public OperacionItemProductoReservado()
        {
            OperacionDespachoItemDetalle = new HashSet<OperacionDespachoItemDetalle>();
        }

        /// <summary>
        /// N° Reserva
        /// </summary>
        [Key]
        [Column("ReservaID")]
        public int ReservaId { get; set; }
        /// <summary>
        /// Cantidad que se deja reservada, al despacharse se tiene q despachar el total reservado, no permite Parcializacion
        /// </summary>
        [Column(TypeName = "decimal(12, 4)")]
        public decimal Cantidad { get; set; }
        /// <summary>
        /// Codigo Producto
        /// </summary>
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        /// <summary>
        /// Tipo de Presentacion del Producto (Caja-Unidades- etc.)
        /// </summary>
        [Column("PresentacionID")]
        public short PresentacionId { get; set; }
        /// <summary>
        /// Permite indicar o explicar sobre el item Reservado
        /// </summary>
        [StringLength(300)]
        public string DetalleReserva { get; set; }
        /// <summary>
        /// Item pedido de venta q realizo la reserva
        /// </summary>
        [Column("ItemIDPedido")]
        public int? ItemIdpedido { get; set; }
        /// <summary>
        /// 10-Reservado PedidoWEB, 20-Reservado Pedido, 30-Reservado Venta, 100-Entregado 250-Cancelado
        /// </summary>
        [Column("EstadoReservaID")]
        public byte EstadoReservaId { get; set; }
        /// <summary>
        /// Indica Pedido Web q genera la reserva
        /// </summary>
        [Column("ItemPedidoID")]
        public int? ItemPedidoId { get; set; }
        /// <summary>
        /// Nro de Deposito
        /// </summary>
        [Column("DepositoID")]
        public short? DepositoId { get; set; }
        /// <summary>
        /// Nor Item De la venta
        /// </summary>
        [Column("ItemIDVenta")]
        public int? ItemIdventa { get; set; }
        public int? Filer { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? CantidadPendiente { get; set; }

        [ForeignKey("CodigoId")]
        [InverseProperty("OperacionItemProductoReservado")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("DepositoId")]
        [InverseProperty("OperacionItemProductoReservado")]
        public virtual Deposito Deposito { get; set; }
        [ForeignKey("ItemIdpedido")]
        [InverseProperty("OperacionItemProductoReservadoItemIdpedidoNavigation")]
        public virtual OperacionItemProducto ItemIdpedidoNavigation { get; set; }
        [ForeignKey("ItemIdventa")]
        [InverseProperty("OperacionItemProductoReservadoItemIdventaNavigation")]
        public virtual OperacionItemProducto ItemIdventaNavigation { get; set; }
        [ForeignKey("ItemPedidoId")]
        [InverseProperty("OperacionItemProductoReservado")]
        public virtual OperacionPedidoVentaWebItem ItemPedido { get; set; }
        [ForeignKey("PresentacionId")]
        [InverseProperty("OperacionItemProductoReservado")]
        public virtual ProductoPresentacionTipo Presentacion { get; set; }
        [InverseProperty("Reserva")]
        public virtual ICollection<OperacionDespachoItemDetalle> OperacionDespachoItemDetalle { get; set; }
    }
}