// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionCobroWeb
    {
        public OperacionCobroWeb()
        {
            OperacionCobroWebImagen = new HashSet<OperacionCobroWebImagen>();
            OperacionCobroWebItem = new HashSet<OperacionCobroWebItem>();
        }

        [Key]
        [Column("CobroWebID")]
        public int CobroWebId { get; set; }
        [Column("ClienteID")]
        public int? ClienteId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaComprobante { get; set; }
        [Column("TalonarioID")]
        public short TalonarioId { get; set; }
        public int NroComprobante { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalCobro { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaImputacion { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        [Column("ProyectoID")]
        public short? ProyectoId { get; set; }
        [Column("CobradorID")]
        public int? CobradorId { get; set; }



        [Unicode(false)]
        public string Observacion { get; set; }



        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraReproceso { get; set; }
        public bool EsMobile { get; set; }
        [Column("TerminalID")]
        public short? TerminalId { get; set; }
        [Column("CobroID")]
        public int? CobroId { get; set; }
        [Column("TipoOperacionID")]
        public byte? TipoOperacionId { get; set; }
        [Column("MovID")]
        public int? MovId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("ClienteId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("CobradorId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual Cobrador Cobrador { get; set; }
        [ForeignKey("MovId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual TransporteCargaMovimiento Mov { get; set; }
        [ForeignKey("TipoOperacionId,CobroId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual OperacionCobro OperacionCobro { get; set; }
        [ForeignKey("ProyectoId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual Proyecto Proyecto { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual Sucursal Sucursal { get; set; }
        [ForeignKey("TerminalId")]
        [InverseProperty("OperacionCobroWeb")]
        public virtual SincronizacionTerminal Terminal { get; set; }
        [InverseProperty("CobroWeb")]
        public virtual ICollection<OperacionCobroWebImagen> OperacionCobroWebImagen { get; set; }
        [InverseProperty("CobroWeb")]
        public virtual ICollection<OperacionCobroWebItem> OperacionCobroWebItem { get; set; }
    }
}