// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("CompraId", "ImportePago", Name = "CobroIDRegComisionID")]
    [Index("CompraId", Name = "IX_CompraID")]
    [Index("CompraId", "ImportePago", Name = "IX_CompraIDImportePago")]
    [Index("RegComisionId", Name = "IX_OperacionComisionPago_RegComisionID")]
    [Index("TipoOperacionId", Name = "IX_OperacionComisionPago_TipoOperacionID")]
    [Index("TipoOperacionId", "CompraId", Name = "IX_TipoOperacionIDCompraID")]
    public partial class OperacionComisionCompra
    {
        public OperacionComisionCompra()
        {
            OperacionComisionImpuesto = new HashSet<OperacionComisionImpuesto>();
        }

        [Key]
        [Column("PagoCimisionID")]
        public int PagoCimisionId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Nro de Compra
        /// </summary>
        [Column("CompraID")]
        public int CompraId { get; set; }
        [Column("RegComisionID")]
        public int RegComisionId { get; set; }
        [Column(TypeName = "money")]
        public decimal ImportePago { get; set; }
        /// <summary>
        /// Indico Porc. De Comicion q se paga
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? PorComisionPago { get; set; }
        /// <summary>
        /// Para relacion con Cobro
        /// </summary>
        [Column("TipoOperacionIDCobro")]
        public byte? TipoOperacionIdcobro { get; set; }
        /// <summary>
        /// Nro Imputacion del COBRO por el que se paga comision segun importe cobrado en la venta
        /// </summary>
        [Column("CobroID")]
        public int? CobroId { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImporteImpuestos { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImporteTotal { get; set; }
        public byte? TipoLiquidacion { get; set; }

        [ForeignKey("TipoOperacionIdcobro,CobroId")]
        [InverseProperty("OperacionComisionCompra")]
        public virtual OperacionCobro OperacionCobro { get; set; }
        [ForeignKey("TipoOperacionId,CompraId")]
        [InverseProperty("OperacionComisionCompra")]
        public virtual OperacionCompra OperacionCompra { get; set; }
        [ForeignKey("RegComisionId")]
        [InverseProperty("OperacionComisionCompra")]
        public virtual OperacionComision RegComision { get; set; }
        [InverseProperty("PagoCimision")]
        public virtual ICollection<OperacionComisionImpuesto> OperacionComisionImpuesto { get; set; }
    }
}