// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoOperacionId", "RegistroOperacionId", Name = "IX_OperacionComision_TipoOperacionIDRegistroOperacionID")]
    [Index("VendedorId", Name = "IX_OperacionComision_VendedorID")]
    public partial class OperacionComision
    {
        public OperacionComision()
        {
            OperacionComisionCompra = new HashSet<OperacionComisionCompra>();
        }

        /// <summary>
        /// Campo Unico
        /// </summary>
        [Key]
        [Column("RegComisionID")]
        public int RegComisionId { get; set; }
        /// <summary>
        /// Comicion General Sobre la Venta
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ComisionGral { get; set; }
        /// <summary>
        /// Comision Por Venta Productos Determinados
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ComisionProd { get; set; }
        /// <summary>
        /// Vendedor que Percibe la comision
        /// </summary>
        [Column("VendedorID")]
        public int? VendedorId { get; set; }
        /// <summary>
        /// Tipo Operacion que se Imprime
        /// </summary>
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Nro Registro de la Operacion
        /// </summary>
        [Column("RegistroOperacionID")]
        public int RegistroOperacionId { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal PorcComicGeneral { get; set; }
        [Column(TypeName = "money")]
        public decimal? SaldoComision { get; set; }
        [Column("EntidadID")]
        public int? EntidadId { get; set; }
        [Column(TypeName = "money")]
        public decimal? ComisionEspecial { get; set; }
        /// <summary>
        /// Indica la base imponible para Calular la comicion de venta producto
        /// Esta Deducida la bonificacion y descuento,(consideracion ver venta OTROS)
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? BaseImponibleComisionGral { get; set; }

        [ForeignKey("EntidadId")]
        [InverseProperty("OperacionComision")]
        public virtual Entidad Entidad { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionComision")]
        public virtual OperacionPedidoVenta OperacionPedidoVenta { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionComision")]
        public virtual OperacionVenta OperacionVenta { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionComision")]
        public virtual OrdenServicio OrdenServicio { get; set; }
        [ForeignKey("VendedorId")]
        [InverseProperty("OperacionComision")]
        public virtual Vendedor Vendedor { get; set; }
        [InverseProperty("RegComision")]
        public virtual ICollection<OperacionComisionCompra> OperacionComisionCompra { get; set; }
    }
}