// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoOperacionId", "RegistroOperacionId", Name = "IX_OperacionAltaModicacionTipoNroOperacion", IsUnique = true)]
    [Index("AlmaUserId", Name = "IX_OperacionAltaModicacion_AlmaUserID")]
    public partial class OperacionAltaModicacion
    {
        [Column("RegistroOperacionID")]
        public int RegistroOperacionId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaUltimaModificacion { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionCobro OperacionCobro { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionCompra OperacionCompra { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionCredito OperacionCredito { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionDespacho OperacionDespacho { get; set; }
        public virtual OperacionInventario OperacionInventario { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionPago OperacionPago { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionPedidoCompra OperacionPedidoCompra { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionPedidoVenta OperacionPedidoVenta { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionRecepcion OperacionRecepcion { get; set; }
        public virtual OperacionRendicion OperacionRendicion { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OperacionVenta OperacionVenta { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("OperacionAltaModicacion")]
        public virtual OrdenServicio OrdenServicio { get; set; }
    }
}