// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("CentroCostoId", "Importe", Name = "CentroCostoIDImporte")]
    [Index("CentroCostoId", Name = "IX_OperacionImputacionCentroCosto")]
    [Index("RegistroImputacion", Name = "IX_OperacionImputacionCentroCosto_RegistroImputacion")]
    public partial class OperacionImputacionCentroCosto
    {
        /// <summary>
        /// Registro de Imputacion
        /// </summary>
        public int RegistroImputacion { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Indico el Codigo Vehiculo, o de Proyecto etc.
        /// </summary>
        [Column("CentroCostoID")]
        public int? CentroCostoId { get; set; }
        /// <summary>
        /// Indica a que refiere mi centro de Costo (Viene de AlmaNET==&gt; CentroCostoTipo)
        /// </summary>
        [Column("TipoCentroCostoID")]
        public short? TipoCentroCostoId { get; set; }
        [Column(TypeName = "money")]
        public decimal Importe { get; set; }

        [ForeignKey("CentroCostoId")]
        [InverseProperty("OperacionImputacionCentroCosto")]
        public virtual PlanDeCuentaCentroCosto CentroCosto { get; set; }
        [ForeignKey("RegistroImputacion")]
        [InverseProperty("OperacionImputacionCentroCosto")]
        public virtual OperacionImputacion RegistroImputacionNavigation { get; set; }
    }
}