// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Inica Recepcion Producto en base a OrdeProduccion
    /// CoopAndresito  COntrol Yerba mate CanchadaElaborada
    /// </summary>
    public partial class OperacionRecepcionItemProduccionProgramacionItem
    {
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column("ItemRecepID")]
        public int ItemRecepId { get; set; }
        /// <summary>
        /// ItemID de Programacion
        /// </summary>
        [Column("ProgramacionItemID")]
        public int ProgramacionItemId { get; set; }

        [ForeignKey("ItemRecepId")]
        [InverseProperty("OperacionRecepcionItemProduccionProgramacionItem")]
        public virtual OperacionRecepcionItem ItemRecep { get; set; }
        [ForeignKey("ProgramacionItemId")]
        [InverseProperty("OperacionRecepcionItemProduccionProgramacionItem")]
        public virtual ProduccionProgramacionItem ProgramacionItem { get; set; }
    }
}