// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionPedidoVentaHotelRest
    {
        public OperacionPedidoVentaHotelRest()
        {
            ProductoHotelRestReserva = new HashSet<ProductoHotelRestReserva>();
        }

        /// <summary>
        /// Tipo Movimiento al que pertenece ( 10-Indica pedido Venta)
        /// </summary>
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Nro Imputacion del Pedido
        /// </summary>
        [Column("PedidoVentaID")]
        public int PedidoVentaId { get; set; }
        [Key]
        [Column("RegistroAtencID")]
        public int RegistroAtencId { get; set; }
        /// <summary>
        /// 0-Disponible (Blanco) 10-Abierta(Vede) 20-Posse Pedido Pendiente(Naranja), 30-Solicito Cierre(Negro) 50-Reservado (Amarillo)
        /// </summary>
        [Column("EstadoID")]
        public short EstadoId { get; set; }
        [Column("CierreID")]
        public int? CierreId { get; set; }
        /// <summary>
        /// Indica la Mesa u Habitacion a la q va el cargo
        /// </summary>
        [Column("ItemServID")]
        public int ItemServId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [ForeignKey("CierreId")]
        [InverseProperty("OperacionPedidoVentaHotelRest")]
        public virtual HotelRestTurno Cierre { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("OperacionPedidoVentaHotelRest")]
        public virtual OperacionPedidoVentaHotelRestEstado Estado { get; set; }
        [ForeignKey("ItemServId")]
        [InverseProperty("OperacionPedidoVentaHotelRest")]
        public virtual ProductoHotelRest ItemServ { get; set; }
        [ForeignKey("TipoOperacionId,PedidoVentaId")]
        [InverseProperty("OperacionPedidoVentaHotelRest")]
        public virtual OperacionPedidoVenta OperacionPedidoVenta { get; set; }
        [InverseProperty("RegistroAtenc")]
        public virtual ICollection<ProductoHotelRestReserva> ProductoHotelRestReserva { get; set; }
    }
}