// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Se registran todos los productos q Salen en Consignacion OperacionTipoID=130 y los productos q ingresaron en Consigancion OperacionTipoID=140
    /// </summary>
    [Index("TipoOperacionId", "ConsignacionId", Name = "IX_OperacionConsignacion", IsUnique = true)]
    [Index("TipoOperacionId", Name = "IX_OperacionConsignacion_1")]
    [Index("ConsignacionId", Name = "IX_OperacionConsignacion_2")]
    public partial class OperacionConsignacion
    {
        public OperacionConsignacion()
        {
            OperacionItemProducto = new HashSet<OperacionItemProducto>();
            OperacionLeyenda = new HashSet<OperacionLeyenda>();
        }

        /// <summary>
        /// Tipo Movimiento al que pertenece (Ventas,Compras,Pagod,Cobros) de AlmaNET.OperacionTipo
        /// </summary>
        [Key]
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Key]
        [Column("ConsignacionID")]
        public int ConsignacionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHora { get; set; }
        /// <summary>
        /// Nro Sucursal/Entidad
        /// </summary>
        [Column("EntidadSucID")]
        public int EntidadSucId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaComprobante { get; set; }
        /// <summary>
        /// Tipo de comprobante utilizado
        /// </summary>
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        /// <summary>
        /// Nro Talonario al que pertenece la Numeracion del comprobante
        /// </summary>
        [Column("TalonarioID")]
        public short TalonarioId { get; set; }
        /// <summary>
        /// Nro de comprobante / Se repite por ComprobnateID y Nro de Punto de Venta
        /// </summary>
        public int NroComprobante { get; set; }
        [Column("TipoEntidadID")]
        public byte? TipoEntidadId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        /// <summary>
        /// Sector en que se asento esta Compra
        /// </summary>
        [Column("SectorID")]
        public short? SectorId { get; set; }
        /// <summary>
        /// Nro de Sucursal de la Empresa en que se realizo la compra
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        /// <summary>
        /// Utilizado para almacenar Informacion de Sincronizacion
        /// </summary>
        public int? Filer { get; set; }
        /// <summary>
        /// Codigo Proyecto
        /// </summary>
        [Column("ProyectoID")]
        public short? ProyectoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaSalida { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaRetorno { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionConsignacion")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("EntidadSucId")]
        [InverseProperty("OperacionConsignacion")]
        public virtual EntidadSucursal EntidadSuc { get; set; }
        [InverseProperty("OperacionConsignacion")]
        public virtual ICollection<OperacionItemProducto> OperacionItemProducto { get; set; }
        [InverseProperty("OperacionConsignacion")]
        public virtual ICollection<OperacionLeyenda> OperacionLeyenda { get; set; }
    }
}