// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("AlmaUserId", Name = "IX_OperacionCompra_AlmaUserID")]
    [Index("CompraId", Name = "IX_OperacionCompra_CompraID", IsUnique = true)]
    [Index("ComprobanteId", Name = "IX_OperacionCompra_ComprobanteID")]
    [Index("FechaComprobante", Name = "IX_OperacionCompra_FechaComprobante")]
    [Index("FechaDevengado", Name = "IX_OperacionCompra_FechaDevengado")]
    [Index("FechaImputacion", Name = "IX_OperacionCompra_FechaImputacion")]
    [Index("FechaVencimiento", Name = "IX_OperacionCompra_FechaVencimiento")]
    [Index("Filer", Name = "IX_OperacionCompra_Filer")]
    [Index("NroComprobante", Name = "IX_OperacionCompra_NroComprobante")]
    [Index("ProveedorId", Name = "IX_OperacionCompra_ProveedorID")]
    [Index("ResumenId", Name = "IX_OperacionCompra_ResumenID")]
    [Index("SectorId", Name = "IX_OperacionCompra_SectorID")]
    [Index("SucursalId", Name = "IX_OperacionCompra_SucursalID")]
    [Index("TalonarioId", Name = "IX_OperacionCompra_TalonarioID")]
    [Index("TipoOperacionId", "ComprobanteId", Name = "IX_OperacionCompra_TipoOperacion_ComprobanteID")]
    public partial class OperacionCompra
    {
        public OperacionCompra()
        {
            AfipmisCombantesRecibidos = new HashSet<AfipmisCombantesRecibidos>();
            AutorizacionCompraCancelacion = new HashSet<AutorizacionCompraCancelacion>();
            ImpuestoFormularioLiquidacion = new HashSet<ImpuestoFormularioLiquidacion>();
            OperacionArchivo = new HashSet<OperacionArchivo>();
            OperacionComisionCompra = new HashSet<OperacionComisionCompra>();
            OperacionDescuento = new HashSet<OperacionDescuento>();
            OperacionDetallePago = new HashSet<OperacionDetallePago>();
            OperacionImpuesto = new HashSet<OperacionImpuesto>();
            OperacionImputacion = new HashSet<OperacionImputacion>();
            OperacionItemProducto = new HashSet<OperacionItemProducto>();
            OperacionItemProductoVentaComisEspecOperacionCompra = new HashSet<OperacionItemProductoVentaComisEspec>();
            OperacionItemProductoVentaComisEspecOperacionCompraNavigation = new HashSet<OperacionItemProductoVentaComisEspec>();
            OperacionLeyenda = new HashSet<OperacionLeyenda>();
            OperacionLiquidoProducto = new HashSet<OperacionLiquidoProducto>();
            OperacionRelacionOperacionOperacionCompra = new HashSet<OperacionRelacionOperacion>();
            OperacionRelacionOperacionOperacionCompraNavigation = new HashSet<OperacionRelacionOperacion>();
            OperacionRetencionFacturas = new HashSet<OperacionRetencionFacturas>();
            OperacionTransporte = new HashSet<OperacionTransporte>();
            ProductoProveedor = new HashSet<ProductoProveedor>();
            RepartoRendicion = new HashSet<RepartoRendicion>();
        }

        /// <summary>
        /// Tipo Movimiento al que pertenece (Ventas,Compras,Pagod,Cobros)
        /// </summary>
        [Key]
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// Nro de Compra
        /// </summary>
        [Key]
        [Column("CompraID")]
        public int CompraId { get; set; }
        /// <summary>
        /// Codigo Proveedor
        /// </summary>
        [Column("ProveedorID")]
        public int? ProveedorId { get; set; }
        /// <summary>
        /// Fecha de la Factura
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaComprobante { get; set; }
        /// <summary>
        /// Categoria de Impuesto al q pertenece el proveedor
        /// </summary>
        [Column("CategoriaImpuestoID")]
        public byte CategoriaImpuestoId { get; set; }
        /// <summary>
        /// Tipo de comprobante a ser  utilizado para este pediodo
        /// </summary>
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }
        /// <summary>
        /// Nro de comprobante / Se repite por ComprobnateID y Nro de talonario
        /// </summary>
        public int NroComprobante { get; set; }
        /// <summary>
        /// Total Importes Sugeto a impuestos
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImporteRegistraImpuesto { get; set; }
        /// <summary>
        /// Total Importes que NO  esta sugeto a Impuesto
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImporteNoRegistraImpuesto { get; set; }
        /// <summary>
        /// Total Desuento Realizado
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImporteDescuento { get; set; }
        /// <summary>
        /// Total Importe Impuestos Suma de la Tabla OperacionImpuesto
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImporteImpuestos { get; set; }
        /// <summary>
        /// ImporteRegistraImpuesto+ImporteNoRegistraImpuesto
        /// </summary>
        [Column(TypeName = "money")]
        public decimal SubTotal { get; set; }
        /// <summary>
        /// Importe Total Compra
        /// </summary>
        [Column(TypeName = "money")]
        public decimal TotalCompra { get; set; }
        /// <summary>
        /// Indica si el pago es deglosado (Tiene + de 1 forma de Pago)
        /// </summary>
        public bool EsPagoDetallar { get; set; }
        /// <summary>
        /// Importe total de bonificaciones realizadas en los distintos itemes de esta  Compra
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ImpBonificacion { get; set; }
        /// <summary>
        /// Tipo Detalle que se viusliza por defecto en esta Compra
        /// </summary>
        public byte TipoDetalle { get; set; }
        /// <summary>
        /// Indica si se trata de Factura, Remito,Ticket
        /// </summary>
        [Column("FRT")]
        public byte Frt { get; set; }
        /// <summary>
        /// Sector en que se asento esta Compra
        /// </summary>
        [Column("SectorID")]
        public short? SectorId { get; set; }
        /// <summary>
        /// Fecha Imputacion Contable
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaImputacion { get; set; }
        /// <summary>
        /// Indica si Generaq Asiento
        /// </summary>
        public bool? GeneraAsiento { get; set; }
        /// <summary>
        /// Transporte en que se eviara la compra
        /// </summary>
        [Column("TransporteID")]
        public int? TransporteId { get; set; }
        /// <summary>
        /// Nro de Sucursal de la Empresa en que se realizo la compra
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        /// <summary>
        /// Cierre Resumen Contable al que pertenece la Compra
        /// </summary>
        [Column("ResumenID")]
        public int? ResumenId { get; set; }
        /// <summary>
        /// Fecha Vencimiento o de Pago de la Factura de Comp[ra
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? FechaVencimiento { get; set; }
        /// <summary>
        /// Nro Talonario al que pertenece la Numeracion del comprobante
        /// </summary>
        [Column("TalonarioID")]
        public short TalonarioId { get; set; }
        /// <summary>
        /// Utilizado para almacenar Informacion de Sincronizacion
        /// </summary>
        public int? Filer { get; set; }
        /// <summary>
        /// Codigo Proyecto
        /// </summary>
        [Column("ProyectoID")]
        public short? ProyectoId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        /// <summary>
        /// Se indica cualquier detalle y/u observacion sobre esta operacion
        /// </summary>
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Indica el Deposito que esta realizando el Pedido
        /// </summary>
        [Column("DepositoID")]
        public short? DepositoId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaDevengado { get; set; }
        [Column("TerminalID")]
        public short? TerminalId { get; set; }
        /// <summary>
        /// Tipo de Moneda en que se realizo la Venta
        /// </summary>
        [Column("MonedaID")]
        public byte? MonedaId { get; set; }
        /// <summary>
        /// Cotizacion a la Fecha de la Moneda
        /// </summary>
        [Column(TypeName = "money")]
        public decimal? Cotizacion { get; set; }
        [Column("RegistroTipoID")]
        public byte? RegistroTipoId { get; set; }
        [Column("CAEA_ID")]
        public int? CaeaId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("OperacionCompra")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("CaeaId")]
        [InverseProperty("OperacionCompra")]
        public virtual OperacionCompraCaea Caea { get; set; }
        [ForeignKey("DepositoId")]
        [InverseProperty("OperacionCompra")]
        public virtual Deposito Deposito { get; set; }
        [ForeignKey("MonedaId")]
        [InverseProperty("OperacionCompra")]
        public virtual MonedaTipo Moneda { get; set; }
        [ForeignKey("ProveedorId")]
        [InverseProperty("OperacionCompra")]
        public virtual Proveedor Proveedor { get; set; }
        [ForeignKey("ProyectoId")]
        [InverseProperty("OperacionCompra")]
        public virtual Proyecto Proyecto { get; set; }
        [ForeignKey("ResumenId")]
        [InverseProperty("OperacionCompra")]
        public virtual OperacionResumen Resumen { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("OperacionCompra")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("OperacionCompra")]
        public virtual Sucursal Sucursal { get; set; }
        [ForeignKey("TerminalId")]
        [InverseProperty("OperacionCompra")]
        public virtual SincronizacionTerminal Terminal { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual LibroDiario LibroDiario { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual OperacionAltaModicacion OperacionAltaModicacion { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<AfipmisCombantesRecibidos> AfipmisCombantesRecibidos { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<AutorizacionCompraCancelacion> AutorizacionCompraCancelacion { get; set; }
        public virtual ICollection<ImpuestoFormularioLiquidacion> ImpuestoFormularioLiquidacion { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionArchivo> OperacionArchivo { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionComisionCompra> OperacionComisionCompra { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionDescuento> OperacionDescuento { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionDetallePago> OperacionDetallePago { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionImpuesto> OperacionImpuesto { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionImputacion> OperacionImputacion { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionItemProducto> OperacionItemProducto { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionItemProductoVentaComisEspec> OperacionItemProductoVentaComisEspecOperacionCompra { get; set; }
        [InverseProperty("OperacionCompraNavigation")]
        public virtual ICollection<OperacionItemProductoVentaComisEspec> OperacionItemProductoVentaComisEspecOperacionCompraNavigation { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionLeyenda> OperacionLeyenda { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionLiquidoProducto> OperacionLiquidoProducto { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionRelacionOperacion> OperacionRelacionOperacionOperacionCompra { get; set; }
        [InverseProperty("OperacionCompraNavigation")]
        public virtual ICollection<OperacionRelacionOperacion> OperacionRelacionOperacionOperacionCompraNavigation { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionRetencionFacturas> OperacionRetencionFacturas { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<OperacionTransporte> OperacionTransporte { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<ProductoProveedor> ProductoProveedor { get; set; }
        [InverseProperty("OperacionCompra")]
        public virtual ICollection<RepartoRendicion> RepartoRendicion { get; set; }
    }
}