// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionVentaBaucherCancelacion
    {
        [Column("BaucherID")]
        public int BaucherId { get; set; }
        public int ImporteBaucher { get; set; }
        [Key]
        [Column("BaucherCancelID")]
        public int BaucherCancelId { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("VentaIDLocal")]
        public int? VentaIdlocal { get; set; }
        [Column("TerminalID")]
        public short? TerminalId { get; set; }
        [Column("RegistroPagoID")]
        public int? RegistroPagoId { get; set; }
        [Column("RegistroPagoIDLocal")]
        public int? RegistroPagoIdlocal { get; set; }

        [ForeignKey("BaucherId")]
        [InverseProperty("OperacionVentaBaucherCancelacion")]
        public virtual OperacionVentaBaucher Baucher { get; set; }
        [ForeignKey("RegistroPagoId")]
        [InverseProperty("OperacionVentaBaucherCancelacion")]
        public virtual OperacionDetallePago RegistroPago { get; set; }
        [ForeignKey("TerminalId")]
        [InverseProperty("OperacionVentaBaucherCancelacion")]
        public virtual SincronizacionTerminal Terminal { get; set; }
    }
}