// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("ItemId", Name = "IX_OperacionItemProductoCompraItemID")]
    public partial class OperacionItemProductoCompra
    {
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column("ItemID")]
        public int ItemId { get; set; }
        /// <summary>
        /// Es el codigo con el que me factura el Proveedor
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string CodigoProveedor { get; set; }
        /// <summary>
        /// Indica la Fecha Vencimiento
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? FechaVencimiento { get; set; }

        [ForeignKey("ItemId")]
        [InverseProperty("OperacionItemProductoCompra")]
        public virtual OperacionItemProducto Item { get; set; }
    }
}