// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OperacionItemProductoVentaBaucher
    {
        [Column("ItemID")]
        public int ItemId { get; set; }
        [Key]
        [Column("ItemVtaBucherID")]
        public int ItemVtaBucherId { get; set; }
        [Column("ProductoOfertaID")]
        public int ProductoOfertaId { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? PorcBaucher { get; set; }
        [Column(TypeName = "money")]
        public decimal Importe { get; set; }
        [Column("BaucherID")]
        public int? BaucherId { get; set; }

        [ForeignKey("BaucherId")]
        [InverseProperty("OperacionItemProductoVentaBaucher")]
        public virtual OperacionVentaBaucher Baucher { get; set; }
        [ForeignKey("ItemId")]
        [InverseProperty("OperacionItemProductoVentaBaucher")]
        public virtual OperacionItemProducto Item { get; set; }
        [ForeignKey("ProductoOfertaId")]
        [InverseProperty("OperacionItemProductoVentaBaucher")]
        public virtual ProductoOferta ProductoOferta { get; set; }
    }
}