// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("DevolucionItemDespchId", Name = "IX_OperacionDespachoItemDetalle")]
    [Index("ItemDespchId", Name = "IX_OperacionDespachoItemDetalle_ItemDespchID")]
    [Index("PresentacionId", Name = "IX_OperacionDespachoItemDetalle_PresentacionID")]
    [Index("RegItemId", Name = "IX_OperacionDespachoItemDetalle_RegItemID")]
    [Index("ReservaId", Name = "IX_OperacionDespachoItemDetalle_ReservaID")]
    public partial class OperacionDespachoItemDetalle
    {
        public OperacionDespachoItemDetalle()
        {
            OperacionItemProductoCubierta = new HashSet<OperacionItemProductoCubierta>();
        }

        /// <summary>
        /// el Item de un despacho
        /// </summary>
        [Column("ItemDespchID")]
        public int ItemDespchId { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Nro de Item de OperacionItemProducto
        /// </summary>
        [Column("RegItemID")]
        public int? RegItemId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal Cantidad { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal UnidadesContiene { get; set; }
        /// <summary>
        /// Tipo Presentacion Producto
        /// </summary>
        [Column("PresentacionID")]
        public short PresentacionId { get; set; }
        /// <summary>
        /// Indica q es una debolucion sobre el Item de un despachacho , Prodcucto q se saco pero que ahora se debuelbe por no utilizarce
        /// </summary>
        [Column("DevolucionItemDespchID")]
        public int? DevolucionItemDespchId { get; set; }
        [Column("ReservaID")]
        public int? ReservaId { get; set; }

        [ForeignKey("DevolucionItemDespchId")]
        [InverseProperty("OperacionDespachoItemDetalleDevolucionItemDespch")]
        public virtual OperacionDespachoItem DevolucionItemDespch { get; set; }
        [ForeignKey("ItemDespchId")]
        [InverseProperty("OperacionDespachoItemDetalleItemDespch")]
        public virtual OperacionDespachoItem ItemDespch { get; set; }
        [ForeignKey("RegItemId")]
        [InverseProperty("OperacionDespachoItemDetalle")]
        public virtual OperacionItemProducto RegItem { get; set; }
        [ForeignKey("ReservaId")]
        [InverseProperty("OperacionDespachoItemDetalle")]
        public virtual OperacionItemProductoReservado Reserva { get; set; }
        [InverseProperty("ItemDespachoNavigation")]
        public virtual ICollection<OperacionItemProductoCubierta> OperacionItemProductoCubierta { get; set; }
    }
}