// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class OrdenServicioEquipo
    {
        [Key]
        [Column("OrdenSerID")]
        public int OrdenSerId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Column("EquipoID")]
        public int EquipoId { get; set; }
        public int? CantidadContador { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ProximoVencimiento { get; set; }

        [ForeignKey("EquipoId")]
        [InverseProperty("OrdenServicioEquipo")]
        public virtual Equipo Equipo { get; set; }
        [ForeignKey("TipoOperacionId,OrdenSerId")]
        [InverseProperty("OrdenServicioEquipo")]
        public virtual OrdenServicio OrdenServicio { get; set; }
    }
}