// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Indica los distintos estado por lo q esta pasando la Orden de Servicio
    /// </summary>
    [Index("TipoOperacionId", Name = "IX_OrdenServicioEstado")]
    [Index("OrdenEstadoId", Name = "IX_OrdenServicioEstado_OrdenEstadoID")]
    [Index("OrdenSerId", Name = "IX_OrdenServicioEstado_OrdenSerID")]
    public partial class OrdenServicioEstado
    {
        [Key]
        [Column("RegEstadoID")]
        public int RegEstadoId { get; set; }
        /// <summary>
        /// Nro ID Orden de Servicio
        /// </summary>
        [Column("OrdenSerID")]
        public int OrdenSerId { get; set; }
        /// <summary>
        /// ID q indica el Codigo de Estado de la Orden de Servicio (Presupuesto, Presupuesto Aprobado, En Proceso, Facturado, Pendiente Entrega, Entregado, Cancelado Etc.)
        /// </summary>
        [Column("OrdenEstadoID")]
        public byte OrdenEstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }

        [ForeignKey("OrdenEstadoId")]
        [InverseProperty("OrdenServicioEstado")]
        public virtual OrdenServioTipoEstado OrdenEstado { get; set; }
        [ForeignKey("TipoOperacionId,OrdenSerId")]
        [InverseProperty("OrdenServicioEstado")]
        public virtual OrdenServicio OrdenServicio { get; set; }
    }
}