// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_OrdenServicioDetallePrioridad_Descripcion")]
    public partial class OrdenServicioDetallePrioridad
    {
        public OrdenServicioDetallePrioridad()
        {
            OperacionItemProductoOrdenServicio = new HashSet<OperacionItemProductoOrdenServicio>();
        }

        /// <summary>
        /// Indica la Prioridad para el Detalle de la Orden de Servicio (Alta, media, Baja, etc.)
        /// </summary>
        [Key]
        [Column("OdenSerPrioridadID")]
        public byte OdenSerPrioridadId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("OdenSerPrioridad")]
        public virtual ICollection<OperacionItemProductoOrdenServicio> OperacionItemProductoOrdenServicio { get; set; }
    }
}