// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EmpresaId", Name = "IX_PermisoEmpresa_EmpresaID")]
    [Index("NroPermiso", Name = "IX_PermisoEmpresa_NroPermiso")]
    public partial class PermisoEmpresa
    {
        public PermisoEmpresa()
        {
            PermisoEmpresaNroCrtmic = new HashSet<PermisoEmpresaNroCrtmic>();
        }

        [Key]
        [Column("PermisoEmpresaID")]
        public int PermisoEmpresaId { get; set; }
        [Column("EmpresaID")]
        public int EmpresaId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NroPermiso { get; set; }
        public int? NroIdoneidad { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaVencimiento { get; set; }
        public int? NroCertIdent { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("CRTInicia")]
        public int? Crtinicia { get; set; }
        [Column("CRTFinaliza")]
        public int? Crtfinaliza { get; set; }
        [Column("MICInicia")]
        public int? Micinicia { get; set; }
        [Column("MICFinaliza")]
        public int? Micfinaliza { get; set; }
        [Column("PaisID")]
        public short? PaisId { get; set; }

        [ForeignKey("EmpresaId")]
        [InverseProperty("PermisoEmpresa")]
        public virtual EmpresaDatos Empresa { get; set; }
        [InverseProperty("PermisoEmpresa")]
        public virtual ICollection<PermisoEmpresaNroCrtmic> PermisoEmpresaNroCrtmic { get; set; }
    }
}