// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class PlanDeCuentaInventarioBienTipo
    {
        public PlanDeCuentaInventarioBienTipo()
        {
            PlanDeCuentaInventario = new HashSet<PlanDeCuentaInventario>();
        }

        [Key]
        [Column("TipoBienID")]
        public short TipoBienId { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public short? VidaUtilAnos { get; set; }
        [Column("TablaIndiceID")]
        public short? TablaIndiceId { get; set; }
        [Column("AjusteCuentaID")]
        public int? AjusteCuentaId { get; set; }

        [InverseProperty("TipoBien")]
        public virtual ICollection<PlanDeCuentaInventario> PlanDeCuentaInventario { get; set; }
    }
}