// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class PlanDeCuentaInventarioSeccion
    {
        public PlanDeCuentaInventarioSeccion()
        {
            PlanDeCuentaInventario = new HashSet<PlanDeCuentaInventario>();
        }

        [Key]
        [Column("SeccionInvetarioID")]
        public int SeccionInvetarioId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("SeccionInvetario")]
        public virtual ICollection<PlanDeCuentaInventario> PlanDeCuentaInventario { get; set; }
    }
}