// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("CuentaTotalizadoraHierarchy", Name = "IX_PlanDeCuentasTotalizadora_CuentaTotalizadoraHierarchy")]
    [Index("Filer", Name = "IX_PlanDeCuentasTotalizadora_Filer")]
    [Index("Orden", Name = "IX_PlanDeCuentasTotalizadora_Orden")]
    [Index("TipoCuentaId", Name = "IX_PlanDeCuentasTotalizadora_TipoCuentaID")]
    public partial class PlanDeCuentasTotalizadora
    {
        public PlanDeCuentasTotalizadora()
        {
            PlanDeCuenta = new HashSet<PlanDeCuenta>();
        }

        /// <summary>
        /// Descripcion de la Cuenta Madre/Totalizadora
        /// </summary>
        [Required]
        [StringLength(180)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        ///  Desc. corta de Orden  Ejem. 1.2.3 
        /// </summary>
        [Required]
        [StringLength(220)]
        [Unicode(false)]
        public string CuentaTotalizadoraHierarchy { get; set; }
        /// <summary>
        /// Tipo De Cuenta (Activo -Pasivo- Reultado etc.)
        /// </summary>
        [Column("TipoCuentaID")]
        public byte TipoCuentaId { get; set; }
        /// <summary>
        /// Autoincremeta
        /// </summary>
        [Key]
        [Column("CuentaTotalizID")]
        public int CuentaTotalizId { get; set; }
        /// <summary>
        /// ejem. 000001.000002.00003 
        /// </summary>
        [StringLength(400)]
        public string Orden { get; set; }
        [StringLength(1500)]
        public string DescripcionCuentaCompleto { get; set; }
        public int? Filer { get; set; }
        [Column("TipoAjusteID")]
        public short? TipoAjusteId { get; set; }
        [Column("TablaIndiceID")]
        public short? TablaIndiceId { get; set; }

        [ForeignKey("TablaIndiceId")]
        [InverseProperty("PlanDeCuentasTotalizadora")]
        public virtual PlanDeCuentaTablaIndice TablaIndice { get; set; }
        [ForeignKey("TipoAjusteId")]
        [InverseProperty("PlanDeCuentasTotalizadora")]
        public virtual PlanDeCuentaTipoAjuste TipoAjuste { get; set; }
        [ForeignKey("TipoCuentaId")]
        [InverseProperty("PlanDeCuentasTotalizadora")]
        public virtual PlanDeCuentasTotalizadoraTipo TipoCuenta { get; set; }
        [InverseProperty("CuentaTotaliz")]
        public virtual ICollection<PlanDeCuenta> PlanDeCuenta { get; set; }
    }
}