// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Programa la Produccion, Permite Programar la produccion en base a las Ordenes de Produccion pendientes
    /// </summary>
    [Index("Detalle", Name = "IX_ProduccionProgramacion_Detalle")]
    public partial class ProduccionProgramacion
    {
        public ProduccionProgramacion()
        {
            Produccion = new HashSet<Produccion>();
            ProduccionProgramacionItem = new HashSet<ProduccionProgramacionItem>();
        }

        [Key]
        [Column("ProgramacionID")]
        public int ProgramacionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [InverseProperty("Programacion")]
        public virtual ICollection<Produccion> Produccion { get; set; }
        [InverseProperty("Programacion")]
        public virtual ICollection<ProduccionProgramacionItem> ProduccionProgramacionItem { get; set; }
    }
}