// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoMarcaManufactur
    {
        public ProductoMarcaManufactur()
        {
            ProductoMarca = new HashSet<ProductoMarca>();
            ProductoOferta = new HashSet<ProductoOferta>();
        }

        [Key]
        [Column("FabricanteID")]
        public int FabricanteId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public byte[] Imagen { get; set; }
        [Column("PaginaWEB")]
        [StringLength(250)]
        [Unicode(false)]
        public string PaginaWeb { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TelServAtencionCliente { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string EmailAtencionCliente { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }
        public int? FabricanteNro { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Domicilio { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Contacto { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaAlta { get; set; }

        [InverseProperty("Fabricante")]
        public virtual ICollection<ProductoMarca> ProductoMarca { get; set; }
        [InverseProperty("Fabricante")]
        public virtual ICollection<ProductoOferta> ProductoOferta { get; set; }
    }
}