// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("FechaActualizacion", Name = "IX_ProductoListaPrecio_FechaActualizacion")]
    [Index("ListaPrecId", Name = "IX_ProductoListaPrecio_ListaPrecID")]
    [Index("ProductoPresentacionId", Name = "IX_ProductoListaPrecio_ProductoPresentacionID")]
    public partial class ProductoListaPrecio
    {
        public ProductoListaPrecio()
        {
            ProductoListaPrecioComision = new HashSet<ProductoListaPrecioComision>();
            ProductoListaSucursal = new HashSet<ProductoListaSucursal>();
            ProductoPrecioHistorico = new HashSet<ProductoPrecioHistorico>();
            TransporteAutorizacionCargaDetalleTransporteCarga = new HashSet<TransporteAutorizacionCargaDetalleTransporteCarga>();
            TransporteCarga = new HashSet<TransporteCarga>();
            TransportePasEnteCarnetTipo = new HashSet<TransportePasEnteCarnetTipo>();
            TransporteViaje = new HashSet<TransporteViaje>();
        }

        [Column("ProductoPresentacionID")]
        public int ProductoPresentacionId { get; set; }
        [Column("ListaPrecID")]
        public short ListaPrecId { get; set; }
        [Column(TypeName = "decimal(10, 5)")]
        public decimal PorcentajeUtilidad { get; set; }
        public byte CalcularUtilidadSobre { get; set; }
        public bool RegistraNroSerie { get; set; }
        [Column(TypeName = "money")]
        public decimal Precio { get; set; }
        [Key]
        [Column("ProductoPrecioID")]
        public int ProductoPrecioId { get; set; }
        [Column(TypeName = "decimal(13, 3)")]
        public decimal? ComicionVendedor { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaActualizacion { get; set; }
        public bool RespetarLista { get; set; }
        [Column(TypeName = "decimal(9, 4)")]
        public decimal? MaxBonif { get; set; }
        [Column(TypeName = "decimal(9, 5)")]
        public decimal? AjusteUtilidad { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [Column(TypeName = "money")]
        public decimal? ComisionVendedorImporte { get; set; }
        [Column(TypeName = "money")]
        public decimal PrecioFinal { get; set; }
        /// <summary>
        /// N° de Sucursal Ver si podemos utilizar para reemplazar la Tabla ProductoListaPrecioSucursal
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("ProductoListaPrecio")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("ListaPrecId")]
        [InverseProperty("ProductoListaPrecio")]
        public virtual ProductoLista ListaPrec { get; set; }
        [ForeignKey("ProductoPresentacionId")]
        [InverseProperty("ProductoListaPrecio")]
        public virtual ProductoPresentacion ProductoPresentacion { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("ProductoListaPrecio")]
        public virtual Sucursal Sucursal { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<ProductoListaPrecioComision> ProductoListaPrecioComision { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<ProductoListaSucursal> ProductoListaSucursal { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<ProductoPrecioHistorico> ProductoPrecioHistorico { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<TransporteAutorizacionCargaDetalleTransporteCarga> TransporteAutorizacionCargaDetalleTransporteCarga { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<TransporteCarga> TransporteCarga { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<TransportePasEnteCarnetTipo> TransportePasEnteCarnetTipo { get; set; }
        [InverseProperty("ProductoPrecio")]
        public virtual ICollection<TransporteViaje> TransporteViaje { get; set; }
    }
}