// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoProveedorInventarioItems
    {
        [Key]
        public int ItemInventProveed { get; set; }
        [Column(TypeName = "decimal(9, 4)")]
        public decimal UnidadesContiene { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal CantidadStock { get; set; }
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        [Column("PresentacionID")]
        public short PresentacionId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? StockAnterior { get; set; }
        [StringLength(10)]
        public string NroItemDetalle { get; set; }
        [StringLength(150)]
        public string Detalle { get; set; }
        [Column("InventarioProveedorID")]
        public int InventarioProveedorId { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        [Column("DepositoID")]
        public short? DepositoId { get; set; }

        [ForeignKey("CodigoId")]
        [InverseProperty("ProductoProveedorInventarioItems")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("DepositoId")]
        [InverseProperty("ProductoProveedorInventarioItems")]
        public virtual Deposito Deposito { get; set; }
        [ForeignKey("InventarioProveedorId")]
        [InverseProperty("ProductoProveedorInventarioItems")]
        public virtual ProductoProveedorInventario InventarioProveedor { get; set; }
        [ForeignKey("PresentacionId")]
        [InverseProperty("ProductoProveedorInventarioItems")]
        public virtual ProductoPresentacionTipo Presentacion { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("ProductoProveedorInventarioItems")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("ProductoProveedorInventarioItems")]
        public virtual Sucursal Sucursal { get; set; }
    }
}