// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Contiene el detalle de Procesos que sufre un Item de una Orden de Produccion
    /// </summary>
    [Index("OrdenProduccionItemId", Name = "IX_ProduccionOrdenItemProceso_OrdenProduccionItemID")]
    [Index("ProcesoId", Name = "IX_ProduccionOrdenItemProceso_ProcesoID")]
    public partial class ProduccionOrdenItemProceso
    {
        /// <summary>
        /// Item de la Orden de la Orden De Produccion
        /// </summary>
        [Column("OrdenProduccionItemID")]
        public int OrdenProduccionItemId { get; set; }
        /// <summary>
        /// Proceso que tiene el Item
        /// </summary>
        [Column("ProcesoID")]
        public short ProcesoId { get; set; }
        /// <summary>
        /// Precio (por cada Proceso para este Item de la Orden), se suma el importe de cada proceso y este es el total para
        /// </summary>
        [Column(TypeName = "money")]
        public decimal PrecioProceso { get; set; }
        /// <summary>
        /// Campo Unico (Enumerador)
        /// </summary>
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("OrdenProduccionItemId")]
        [InverseProperty("ProduccionOrdenItemProceso")]
        public virtual ProduccionOrdenItem OrdenProduccionItem { get; set; }
        [ForeignKey("ProcesoId")]
        [InverseProperty("ProduccionOrdenItemProceso")]
        public virtual ProduccionProceso Proceso { get; set; }
    }
}