// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("NroSerieId", Name = "IX_ProductoNroSerieDetalle_NroSerieID")]
    public partial class ProductoNroSerieDetalle
    {
        /// <summary>
        /// Registro del Nro de Serie
        /// </summary>
        [Column("NroSerieID")]
        public int NroSerieId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Medida1 { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Medida2 { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Medida3 { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? Medida4 { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("NroSerieId")]
        [InverseProperty("ProductoNroSerieDetalle")]
        public virtual ProductoNroSerie NroSerie { get; set; }
    }
}