// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoCostoTipo
    {
        public ProductoCostoTipo()
        {
            ProductoCostoDescuento = new HashSet<ProductoCostoDescuento>();
            ProductoCostoRecargo = new HashSet<ProductoCostoRecargo>();
        }

        [Key]
        [Column("CostoTipoID")]
        public short CostoTipoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public bool RecargoDescuento { get; set; }

        [InverseProperty("DescuentoCompra")]
        public virtual ICollection<ProductoCostoDescuento> ProductoCostoDescuento { get; set; }
        [InverseProperty("RecargoCompra")]
        public virtual ICollection<ProductoCostoRecargo> ProductoCostoRecargo { get; set; }
    }
}