// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Se refiere a un Lote de Produccion, o Ingreso, permite agrupardeterminada cantidad de ProductosNroSerie, para controlar fecha vencimientos, garantia etc.
    /// </summary>
    [Index("ComprobanteId", Name = "IX_ProductoNroSerieLote_ComprobanteID")]
    [Index("Descripcion", Name = "IX_ProductoNroSerieLote_Descripcion")]
    [Index("ProductoPresentacionId", Name = "IX_ProductoNroSerieLote_ProductoPresentacionID")]
    public partial class ProductoNroSerieLote
    {
        public ProductoNroSerieLote()
        {
            ProductoNroSerie = new HashSet<ProductoNroSerie>();
            ProductoNroSerieLoteFraccion = new HashSet<ProductoNroSerieLoteFraccion>();
        }

        [Key]
        [Column("LoteID")]
        public int LoteId { get; set; }
        /// <summary>
        /// Descripcion del Lote
        /// </summary>
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// NroSeirie Inicio
        /// </summary>
        public int NroSerieInicia { get; set; }
        /// <summary>
        /// Nro Serie Final
        /// </summary>
        public int NroSerieFinal { get; set; }
        public byte? LoteEstadoId { get; set; }
        public int? CantidadRollosSerie { get; set; }
        [Column("ProductoPresentacionID")]
        public int ProductoPresentacionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Column("ComprobanteID")]
        public short ComprobanteId { get; set; }

        [ForeignKey("LoteEstadoId")]
        [InverseProperty("ProductoNroSerieLote")]
        public virtual ProductoNroSerieLoteEstado LoteEstado { get; set; }
        [ForeignKey("ProductoPresentacionId")]
        [InverseProperty("ProductoNroSerieLote")]
        public virtual ProductoPresentacion ProductoPresentacion { get; set; }
        [InverseProperty("Lote")]
        public virtual ICollection<ProductoNroSerie> ProductoNroSerie { get; set; }
        [InverseProperty("Lote")]
        public virtual ICollection<ProductoNroSerieLoteFraccion> ProductoNroSerieLoteFraccion { get; set; }
    }
}