// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("MaquinaId", Name = "IX_ProduccionInsumosOrden_MaquinaID")]
    [Index("OperadorId", Name = "IX_ProduccionInsumosOrden_OperadorID")]
    [Index("PlanillaProduccionId", Name = "IX_ProduccionInsumosOrden_PlanillaProduccionID")]
    [Index("ProcesoId", Name = "IX_ProduccionInsumosOrden_ProcesoID")]
    public partial class ProduccionInsumosOrden
    {
        public ProduccionInsumosOrden()
        {
            ProduccionInsumosOrdenItem = new HashSet<ProduccionInsumosOrdenItem>();
        }

        [Key]
        [Column("OrdenInsumoID")]
        public int OrdenInsumoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Column("ProcesoID")]
        public int ProcesoId { get; set; }
        [Column("MaquinaID")]
        public short? MaquinaId { get; set; }
        [Column("TurnoProduccionID")]
        public byte? TurnoProduccionId { get; set; }
        [Column("PlanillaProduccionID")]
        public int PlanillaProduccionId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column("OperadorID")]
        public int? OperadorId { get; set; }

        [ForeignKey("MaquinaId")]
        [InverseProperty("ProduccionInsumosOrden")]
        public virtual ProduccionMaquina Maquina { get; set; }
        [ForeignKey("OperadorId")]
        [InverseProperty("ProduccionInsumosOrden")]
        public virtual ProduccionOperario Operador { get; set; }
        [ForeignKey("PlanillaProduccionId")]
        [InverseProperty("ProduccionInsumosOrden")]
        public virtual Produccion PlanillaProduccion { get; set; }
        [InverseProperty("OrdenInsumo")]
        public virtual ICollection<ProduccionInsumosOrdenItem> ProduccionInsumosOrdenItem { get; set; }
    }
}