// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoHotelRestReserva
    {
        [Key]
        [Column("ReservaID")]
        public int ReservaId { get; set; }
        [Column("ItemServID")]
        public int ItemServId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaIngreso { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaPedido { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaAviso { get; set; }
        [Column("ConfirmacionID")]
        public byte? ConfirmacionId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Detalle { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaSalida { get; set; }
        [Column("RegistroAtencID")]
        public int? RegistroAtencId { get; set; }
        [Column("ClienteID")]
        public int? ClienteId { get; set; }
        /// <summary>
        /// 0-Normal 20-Mantenimiento programado 100-Cancelado 
        /// </summary>
        [Column("EstadoID")]
        public short EstadoId { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("ProductoHotelRestReserva")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("ItemServId")]
        [InverseProperty("ProductoHotelRestReserva")]
        public virtual ProductoHotelRest ItemServ { get; set; }
        [ForeignKey("RegistroAtencId")]
        [InverseProperty("ProductoHotelRestReserva")]
        public virtual OperacionPedidoVentaHotelRest RegistroAtenc { get; set; }
    }
}