// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_ProductoNroSerieLoteEstado_Descripcion")]
    public partial class ProductoNroSerieLoteEstado
    {
        public ProductoNroSerieLoteEstado()
        {
            ProductoNroSerieLote = new HashSet<ProductoNroSerieLote>();
        }

        /// <summary>
        /// Define el Estado de los Lotes de Producto
        /// </summary>
        [Key]
        public byte LoteEstadoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("LoteEstado")]
        public virtual ICollection<ProductoNroSerieLote> ProductoNroSerieLote { get; set; }
    }
}