// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoProveedorInventario
    {
        public ProductoProveedorInventario()
        {
            ProductoProveedorInventarioItems = new HashSet<ProductoProveedorInventarioItems>();
        }

        [Key]
        [Column("InventarioProveedorID")]
        public int InventarioProveedorId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        [Column("ProyectoID")]
        public short? ProyectoId { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string DetalleInventario { get; set; }
        [Column("EstadoID")]
        public byte? EstadoId { get; set; }
        [Column("ProveedorID")]
        public int ProveedorId { get; set; }
        [Column("RepresentadaID")]
        public short? RepresentadaId { get; set; }

        [ForeignKey("ProveedorId")]
        [InverseProperty("ProductoProveedorInventario")]
        public virtual Proveedor Proveedor { get; set; }
        [InverseProperty("InventarioProveedor")]
        public virtual ICollection<ProductoProveedorInventarioItems> ProductoProveedorInventarioItems { get; set; }
    }
}