// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("ProductoPresentacionId", Name = "IX_ProductoProcesoPrecio_CodigoID")]
    [Index("DescripcionVenta", Name = "IX_ProductoProcesoPrecio_DescripcionVenta")]
    [Index("MaquinaId", Name = "IX_ProductoProcesoPrecio_MaquinaID")]
    [Index("ProcesoId", Name = "IX_ProductoProcesoPrecio_ProcesoID")]
    public partial class ProductoProcesoPrecio
    {
        public ProductoProcesoPrecio()
        {
            ProductoProcesoInsumo = new HashSet<ProductoProcesoInsumo>();
        }

        /// <summary>
        /// Define un Nro Poceso  unico (CodigoID,ProcesoID)  para cada Uno de los distintos de Procesos de elaboracion dentro de un Producto
        /// </summary>
        [Key]
        [Column("SubProcesoID")]
        public int SubProcesoId { get; set; }
        /// <summary>
        /// Codigo Proceso dentro de este Producto
        /// </summary>
        [Column("ProcesoID")]
        public short ProcesoId { get; set; }
        /// <summary>
        /// Opcional Mauina en la que se realiza el Proceso de este Producto
        /// </summary>
        [Column("MaquinaID")]
        public short? MaquinaId { get; set; }
        /// <summary>
        /// Descricpcion a utilizar para Facturar Este. Proceso
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string DescripcionVenta { get; set; }
        /// <summary>
        /// Costo de Este Proceso
        /// </summary>
        [Column(TypeName = "money")]
        public decimal TotalCosto { get; set; }
        /// <summary>
        /// % De ganancia aplicado Sobre el Costo  Insumo de este Proceso
        /// </summary>
        [Column(TypeName = "decimal(12, 5)")]
        public decimal MagenUtilidad { get; set; }
        /// <summary>
        /// Precio de venta de este Proceso
        /// </summary>
        [Column(TypeName = "money")]
        public decimal PrecioVenta { get; set; }
        /// <summary>
        /// Indica si aparecera en la lista de Precio (Precios Producto--Procesos)
        /// </summary>
        public bool MostrarEnListaPrecio { get; set; }
        /// <summary>
        /// Tiempo que se demora en Realizar el Proceso para un producto (Estimado)
        /// </summary>
        public int TiempoProceso { get; set; }
        /// <summary>
        /// Indica que este proceso puede ser Obviado en la elaboracion de un producto
        /// </summary>
        public bool ProcesoOpcional { get; set; }
        /// <summary>
        /// Orden en que se elabora el Producto, no poermite saltearse el orden del proceso salvo ProcesoOpcional
        /// </summary>
        public short OrdenProceso { get; set; }
        /// <summary>
        /// 0- Control de tiempo se realiza por Proceso, 1-Control de Tiempo por Maquina (Obliga a Ingresar una Maquina)
        /// </summary>
        public byte TiempoControlPor { get; set; }
        public bool AsignaNroSerie { get; set; }
        [Column("ProductoPresentacionID")]
        public int ProductoPresentacionId { get; set; }
        /// <summary>
        /// Impresora a utilizar para emision de comandas en hotel resturant
        /// </summary>
        [StringLength(250)]
        [Unicode(false)]
        public string ImpresoraDefault { get; set; }

        [ForeignKey("MaquinaId")]
        [InverseProperty("ProductoProcesoPrecio")]
        public virtual ProduccionMaquina Maquina { get; set; }
        [ForeignKey("ProcesoId")]
        [InverseProperty("ProductoProcesoPrecio")]
        public virtual ProduccionProceso Proceso { get; set; }
        [ForeignKey("ProductoPresentacionId")]
        [InverseProperty("ProductoProcesoPrecio")]
        public virtual ProductoPresentacion ProductoPresentacion { get; set; }
        [InverseProperty("SubProceso")]
        public virtual ICollection<ProductoProcesoInsumo> ProductoProcesoInsumo { get; set; }
    }
}