// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Caracteristica1Id", Name = "IX_Producto_Caracteristica1ID")]
    [Index("Caracteristica2Id", Name = "IX_Producto_Caracteristica2ID")]
    [Index("Caracteristica3Id", Name = "IX_Producto_Caracteristica3ID")]
    [Index("CodigoAlfanum", Name = "IX_Producto_CodigoAlfanum")]
    [Index("CodigoBaseId", Name = "IX_Producto_CodigoBaseID")]
    [Index("CodigoFabrica", Name = "IX_Producto_CodigoFabrica")]
    [Index("DescripcionCorta", Name = "IX_Producto_DescripcionCorta")]
    [Index("DescripcionLarga", Name = "IX_Producto_DescripcionLarga")]
    [Index("Inhabilitado", Name = "IX_Producto_Inhabilitado")]
    [Index("RubroCodigo", Name = "IX_Producto_RubroCodigo")]
    [Index("Inhabilitado", Name = "ProductoInhabilitado2")]
    public partial class Producto
    {
        public Producto()
        {
            BasculaPesaje = new HashSet<BasculaPesaje>();
            BasculaProducto = new HashSet<BasculaProducto>();
            ComisionEspecial = new HashSet<ComisionEspecial>();
            DepositoMovimientoItem = new HashSet<DepositoMovimientoItem>();
            Equipo = new HashSet<Equipo>();
            FrigorificoAnimaIngresolProducto = new HashSet<FrigorificoAnimaIngresolProducto>();
            FrigorificoPiezaEgresoProducto = new HashSet<FrigorificoPiezaEgresoProducto>();
            OperacionDespachoItem = new HashSet<OperacionDespachoItem>();
            OperacionInventarioProducto = new HashSet<OperacionInventarioProducto>();
            OperacionItemProdPedidoVentaOperacionItemProdVenta = new HashSet<OperacionItemProdPedidoVentaOperacionItemProdVenta>();
            OperacionItemProductCtrlEnvase = new HashSet<OperacionItemProductCtrlEnvase>();
            OperacionItemProducto = new HashSet<OperacionItemProducto>();
            OperacionItemProductoPedidoCompraReposicion = new HashSet<OperacionItemProductoPedidoCompraReposicion>();
            OperacionItemProductoReservado = new HashSet<OperacionItemProductoReservado>();
            OperacionPedidoVentaWebItem = new HashSet<OperacionPedidoVentaWebItem>();
            OperacionRecepcionItem = new HashSet<OperacionRecepcionItem>();
            ProductoComboItem = new HashSet<ProductoComboItem>();
            ProductoComboItemOpcion = new HashSet<ProductoComboItemOpcion>();
            ProductoComisionEspecial = new HashSet<ProductoComisionEspecial>();
            ProductoCosto = new HashSet<ProductoCosto>();
            ProductoEnvaseConsignacion = new HashSet<ProductoEnvaseConsignacion>();
            ProductoHotelRest = new HashSet<ProductoHotelRest>();
            ProductoOferta2 = new HashSet<ProductoOferta2>();
            ProductoOfertaCodigo = new HashSet<ProductoOferta>();
            ProductoOfertaCodigoIdgratisNavigation = new HashSet<ProductoOferta>();
            ProductoPresentacion = new HashSet<ProductoPresentacion>();
            ProductoProveedor = new HashSet<ProductoProveedor>();
            ProductoProveedorInventarioItems = new HashSet<ProductoProveedorInventarioItems>();
            ProductoRelacionProductoCodigo = new HashSet<ProductoRelacionProducto>();
            ProductoRelacionProductoCodigoIdprodRelacionadoNavigation = new HashSet<ProductoRelacionProducto>();
            ProductoUbicacionStock = new HashSet<ProductoUbicacionStock>();
            ProductoVencimiento = new HashSet<ProductoVencimiento>();
            RepartoVentaDirecta = new HashSet<RepartoVentaDirecta>();
            ServisItem = new HashSet<ServisItem>();
            SoporteTecnicoServicios = new HashSet<SoporteTecnicoServicios>();
            TransporteCargaConvenioColectivoDetalle = new HashSet<TransporteCargaConvenioColectivoDetalle>();
            TransporteCubierta = new HashSet<TransporteCubierta>();
            TransporteMantenimientoDetalle = new HashSet<TransporteMantenimientoDetalle>();
            UnidadFacturacionConceptos = new HashSet<UnidadFacturacionConceptos>();
        }

        [Key]
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CodigoFabrica { get; set; }
        /// <summary>
        /// Se utiliza para Sub-Clasificar Productos (ejem. Talle de una Prenda)
        /// </summary>
        [Column("Caracteristica1ID")]
        public int? Caracteristica1Id { get; set; }
        /// <summary>
        /// Se utiliza para Sub-Clasificar Productos (ejem. Color de una Prenda)
        /// </summary>
        [Column("Caracteristica2ID")]
        public int? Caracteristica2Id { get; set; }
        public bool Inhabilitado { get; set; }
        /// <summary>
        /// Producto Base (Clase), utilizado en tiendas, para agrupar 
        /// </summary>
        [Column("CodigoBaseID")]
        public int CodigoBaseId { get; set; }
        [Column("Caracteristica3ID")]
        public int? Caracteristica3Id { get; set; }
        /// <summary>
        /// Descripcion Completa
        /// </summary>
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string DescripcionLarga { get; set; }
        /// <summary>
        /// Descripcion Abreviada
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string DescripcionCorta { get; set; }
        /// <summary>
        /// Presentacion por defecto en la que se vende el Producto
        /// </summary>
        [Column("DefaultPresentacionVentaID")]
        public short? DefaultPresentacionVentaId { get; set; }
        /// <summary>
        /// Presentacion por defecto en la que se realiza la compra del Producto
        /// </summary>
        [Column("DefaultPresentacionCompraID")]
        public short? DefaultPresentacionCompraId { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string RubroCodigo { get; set; }
        /// <summary>
        /// Codigo alfanumerico que se puede utilizar para facturacion producto
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string CodigoAlfanum { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? CondicionListaPrecio { get; set; }
        public short? ListaPrecioUtilizar { get; set; }
        [Column("ItemIDUltimaVenta")]
        public int? ItemIdultimaVenta { get; set; }
        [Column("ItemIDUltimaCompra")]
        public int? ItemIdultimaCompra { get; set; }

        [ForeignKey("Caracteristica1Id")]
        [InverseProperty("Producto")]
        public virtual ProductoCaracteristica1 Caracteristica1 { get; set; }
        [ForeignKey("Caracteristica2Id")]
        [InverseProperty("Producto")]
        public virtual ProductoCaracteristica2 Caracteristica2 { get; set; }
        [ForeignKey("Caracteristica3Id")]
        [InverseProperty("Producto")]
        public virtual ProductoCaracteristica3 Caracteristica3 { get; set; }
        [ForeignKey("CodigoBaseId")]
        [InverseProperty("Producto")]
        public virtual ProductoBase CodigoBase { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<BasculaPesaje> BasculaPesaje { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<BasculaProducto> BasculaProducto { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ComisionEspecial> ComisionEspecial { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<DepositoMovimientoItem> DepositoMovimientoItem { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<Equipo> Equipo { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<FrigorificoAnimaIngresolProducto> FrigorificoAnimaIngresolProducto { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<FrigorificoPiezaEgresoProducto> FrigorificoPiezaEgresoProducto { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionDespachoItem> OperacionDespachoItem { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionInventarioProducto> OperacionInventarioProducto { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionItemProdPedidoVentaOperacionItemProdVenta> OperacionItemProdPedidoVentaOperacionItemProdVenta { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionItemProductCtrlEnvase> OperacionItemProductCtrlEnvase { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionItemProducto> OperacionItemProducto { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionItemProductoPedidoCompraReposicion> OperacionItemProductoPedidoCompraReposicion { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionItemProductoReservado> OperacionItemProductoReservado { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionPedidoVentaWebItem> OperacionPedidoVentaWebItem { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<OperacionRecepcionItem> OperacionRecepcionItem { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoComboItem> ProductoComboItem { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoComboItemOpcion> ProductoComboItemOpcion { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoComisionEspecial> ProductoComisionEspecial { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoCosto> ProductoCosto { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoEnvaseConsignacion> ProductoEnvaseConsignacion { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoHotelRest> ProductoHotelRest { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoOferta2> ProductoOferta2 { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoOferta> ProductoOfertaCodigo { get; set; }
        [InverseProperty("CodigoIdgratisNavigation")]
        public virtual ICollection<ProductoOferta> ProductoOfertaCodigoIdgratisNavigation { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoPresentacion> ProductoPresentacion { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoProveedor> ProductoProveedor { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoProveedorInventarioItems> ProductoProveedorInventarioItems { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoRelacionProducto> ProductoRelacionProductoCodigo { get; set; }
        [InverseProperty("CodigoIdprodRelacionadoNavigation")]
        public virtual ICollection<ProductoRelacionProducto> ProductoRelacionProductoCodigoIdprodRelacionadoNavigation { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoUbicacionStock> ProductoUbicacionStock { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ProductoVencimiento> ProductoVencimiento { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<RepartoVentaDirecta> RepartoVentaDirecta { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<ServisItem> ServisItem { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<SoporteTecnicoServicios> SoporteTecnicoServicios { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<TransporteCargaConvenioColectivoDetalle> TransporteCargaConvenioColectivoDetalle { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<TransporteCubierta> TransporteCubierta { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<TransporteMantenimientoDetalle> TransporteMantenimientoDetalle { get; set; }
        [InverseProperty("Codigo")]
        public virtual ICollection<UnidadFacturacionConceptos> UnidadFacturacionConceptos { get; set; }
    }
}