// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Detalle de los Items de Programacion 
    /// </summary>
    [Index("MaquinaId", Name = "IX_ProduccionProgramacionItems_MaquinaID")]
    [Index("OperadorId", Name = "IX_ProduccionProgramacionItems_OperadorID")]
    [Index("ProgramacionId", Name = "IX_ProduccionProgramacionItems_ProgramacionID")]
    [Index("ProgramacionItemElaboracionId", Name = "IX_ProduccionProgramacionItems_ProgramacionItemElaboracionID")]
    public partial class ProduccionProgramacionItem
    {
        public ProduccionProgramacionItem()
        {
            OperacionRecepcionItemProduccionProgramacionItem = new HashSet<OperacionRecepcionItemProduccionProgramacionItem>();
            ProduccionItem = new HashSet<ProduccionItem>();
        }

        /// <summary>
        /// ItemID de Programacion
        /// </summary>
        [Key]
        [Column("ProgramacionItemID")]
        public int ProgramacionItemId { get; set; }
        /// <summary>
        /// Nro Planilla de Programacion
        /// </summary>
        [Column("ProgramacionID")]
        public int? ProgramacionId { get; set; }
        /// <summary>
        /// Refiere al Codigo de un Producto Elaborado en su ProcesoID (Un producto Elaborado Subre Varios Procesos por cada Proceso Recibe un  Nro de ProgamacionItemElaboracionID)
        /// </summary>
        [Column("ProgramacionItemElaboracionID")]
        public int ProgramacionItemElaboracionId { get; set; }
        [Column("MaquinaID")]
        public short? MaquinaId { get; set; }
        [Column("OperadorID")]
        public int? OperadorId { get; set; }
        [Column("TurnoID")]
        public short? TurnoId { get; set; }
        public int CantidadTiempo { get; set; }
        [Column(TypeName = "decimal(12, 3)")]
        public decimal Cantidad { get; set; }

        [ForeignKey("MaquinaId")]
        [InverseProperty("ProduccionProgramacionItem")]
        public virtual ProduccionMaquina Maquina { get; set; }
        [ForeignKey("OperadorId")]
        [InverseProperty("ProduccionProgramacionItem")]
        public virtual ProduccionOperario Operador { get; set; }
        [ForeignKey("ProgramacionId")]
        [InverseProperty("ProduccionProgramacionItem")]
        public virtual ProduccionProgramacion Programacion { get; set; }
        [ForeignKey("ProgramacionItemElaboracionId")]
        [InverseProperty("ProduccionProgramacionItem")]
        public virtual ProduccionOrdenItemProgramacion ProgramacionItemElaboracion { get; set; }
        [ForeignKey("TurnoId")]
        [InverseProperty("ProduccionProgramacionItem")]
        public virtual Turno Turno { get; set; }
        [InverseProperty("ProgramacionItem")]
        public virtual ICollection<OperacionRecepcionItemProduccionProgramacionItem> OperacionRecepcionItemProduccionProgramacionItem { get; set; }
        [InverseProperty("ProgramacionItem")]
        public virtual ICollection<ProduccionItem> ProduccionItem { get; set; }
    }
}