// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    ///  BAZAR , ELECTRODOMESTICOS ,PRODUCTOS FRESCOS  
    ///  TEXTIL  ,CONSUMO PRINCIPAL, FARMACIA  
    /// Permite sectorizar las distintos tipo de canastas(ProductoFamiliaTipo)
    /// </summary>
    public partial class ProductoFamiliaTipoSector
    {
        public ProductoFamiliaTipoSector()
        {
            ProductoFamiliaTipo = new HashSet<ProductoFamiliaTipo>();
        }

        [Key]
        [Column("ProductoSectorID")]
        public short ProductoSectorId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("ProductoSector")]
        public virtual ICollection<ProductoFamiliaTipo> ProductoFamiliaTipo { get; set; }
    }
}