// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Fecha", Name = "IX_ProductoPrecioHistorico_Fecha")]
    [Index("ProductoPrecioId", Name = "IX_ProductoPrecioHistorico_ProductoPrecioID")]
    public partial class ProductoPrecioHistorico
    {
        /// <summary>
        /// Lista Precio y codigo porducto q cambio
        /// </summary>
        [Column("ProductoPrecioID")]
        public int ProductoPrecioId { get; set; }
        /// <summary>
        /// Fecha del Cambio de Precio
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        /// <summary>
        /// Unidades q Contiene al realizar el cambio
        /// </summary>
        [Column(TypeName = "decimal(9, 4)")]
        public decimal UnidadesContiene { get; set; }
        /// <summary>
        /// Informacion Adicional
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// almaceno el % de recargo a Aplicar
        /// </summary>
        [Column(TypeName = "decimal(9, 4)")]
        public decimal PocentajeUtilidad { get; set; }
        /// <summary>
        /// Precio Neto
        /// </summary>
        [Column(TypeName = "money")]
        public decimal Precio { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// 0-Lista General 1-Sobre Costo 10-Precio Manual
        /// </summary>
        public byte CalcularUtilidadSobre { get; set; }
        /// <summary>
        /// Indica Codigo Nueva lista Precio Aplicar
        /// </summary>
        [Column("ListaPrecioNuevaID")]
        public int? ListaPrecioNuevaId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        /// <summary>
        /// N° de Sucursal a lq que pertenece la lista de precio
        /// </summary>
        [Column("SucursalID")]
        public short? SucursalId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("ProductoPrecioHistorico")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("ListaPrecioNuevaId")]
        [InverseProperty("ProductoPrecioHistorico")]
        public virtual ProductoNuevaListaPrecio ListaPrecioNueva { get; set; }
        [ForeignKey("ProductoPrecioId")]
        [InverseProperty("ProductoPrecioHistorico")]
        public virtual ProductoListaPrecio ProductoPrecio { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("ProductoPrecioHistorico")]
        public virtual Sucursal Sucursal { get; set; }
    }
}