// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Permite Agrupar Productos Ejem. Pesables, PLU Interno, Ofertas, Etc.
    /// </summary>
    [Index("Descripcion", Name = "IX_ProductoClasificacion_Descripcion")]
    public partial class ProductoClasificacion
    {
        public ProductoClasificacion()
        {
            ProductoBase = new HashSet<ProductoBase>();
        }

        [Key]
        [Column("ClasificacionID")]
        public int ClasificacionId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Required]
        [StringLength(220)]
        [Unicode(false)]
        public string ProductoClasificacionHierarchy { get; set; }

        [InverseProperty("Clasificacion")]
        public virtual ICollection<ProductoBase> ProductoBase { get; set; }
    }
}