// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// La maquinas que estan atados a los distintos Procesos
    /// </summary>
    [Index("MaquinaId", Name = "IX_ProduccionProcesoMaquina_MaquinaID")]
    [Index("ProcesoId", Name = "IX_ProduccionProcesoMaquina_ProcesoID")]
    public partial class ProduccionProcesoMaquina
    {
        /// <summary>
        /// Codigo  Maquina Relacionada al proceso
        /// </summary>
        [Column("MaquinaID")]
        public short MaquinaId { get; set; }
        /// <summary>
        /// Codigo del Proceso al que esta relacionado la Maquina
        /// </summary>
        [Column("ProcesoID")]
        public short ProcesoId { get; set; }
        [Key]
        [Column("ProsesoMaquinaID")]
        public int ProsesoMaquinaId { get; set; }

        [ForeignKey("MaquinaId")]
        [InverseProperty("ProduccionProcesoMaquina")]
        public virtual ProduccionMaquina Maquina { get; set; }
        [ForeignKey("ProcesoId")]
        [InverseProperty("ProduccionProcesoMaquina")]
        public virtual ProduccionProceso Proceso { get; set; }
    }
}