// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_ProductoCaracteristica3Tipo_Descripcion")]
    public partial class ProductoCaracteristica3Tipo
    {
        public ProductoCaracteristica3Tipo()
        {
            ProductoCaracteristica3 = new HashSet<ProductoCaracteristica3>();
        }

        [Key]
        [Column("TipoCaracteristicaID")]
        public short TipoCaracteristicaId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("TipoCaracteristica")]
        public virtual ICollection<ProductoCaracteristica3> ProductoCaracteristica3 { get; set; }
    }
}