// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Contiene los Distintos estado en que puede estar una Ordende Produccion
    /// </summary>
    [Index("Descripcion", Name = "IX_ProduccionOrdenEstadoTipo_Descripcion")]
    public partial class ProduccionOrdenEstadoTipo
    {
        public ProduccionOrdenEstadoTipo()
        {
            ProduccionOrden = new HashSet<ProduccionOrden>();
        }

        [Key]
        [Column("EstadoOrdenID")]
        public int EstadoOrdenId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("EstadoOrden")]
        public virtual ICollection<ProduccionOrden> ProduccionOrden { get; set; }
    }
}