// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoPalletItem
    {
        [Column("LoteFraccionID")]
        public int LoteFraccionId { get; set; }
        [Key]
        [Column("PalletItemID")]
        public int PalletItemId { get; set; }
        [Column("RegistroPalletID")]
        public int RegistroPalletId { get; set; }

        [ForeignKey("LoteFraccionId")]
        [InverseProperty("ProductoPalletItem")]
        public virtual ProductoNroSerieLoteFraccion LoteFraccion { get; set; }
        [ForeignKey("RegistroPalletId")]
        [InverseProperty("ProductoPalletItem")]
        public virtual ProductoPallet RegistroPallet { get; set; }
    }
}