// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Permite especificar los gastos sobre un proceso
    /// </summary>
    [Index("CuentaId", "ProcesoId", Name = "IX_ProduccionGastoProceso", IsUnique = true)]
    [Index("CuentaId", Name = "IX_ProduccionGastoProceso_CuentaID")]
    public partial class ProduccionGastoProceso
    {
        [Column("CuentaID")]
        public int CuentaId { get; set; }
        [Column("ProcesoID")]
        public short ProcesoId { get; set; }
        [Column(TypeName = "decimal(12, 0)")]
        public decimal Insidencia { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }

        [ForeignKey("CuentaId")]
        [InverseProperty("ProduccionGastoProceso")]
        public virtual ProduccionGasto Cuenta { get; set; }
        [ForeignKey("ProcesoId")]
        [InverseProperty("ProduccionGastoProceso")]
        public virtual ProduccionProceso Proceso { get; set; }
    }
}