// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoHotelRestCategoria
    {
        public ProductoHotelRestCategoria()
        {
            ProductoHotelRest = new HashSet<ProductoHotelRest>();
        }

        [Key]
        [Column("CategoriaID")]
        public short CategoriaId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("Categoria")]
        public virtual ICollection<ProductoHotelRest> ProductoHotelRest { get; set; }
    }
}