// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EmpleadoId", Name = "IX_ProduccionOperario_EmpleadoID")]
    public partial class ProduccionOperario
    {
        public ProduccionOperario()
        {
            ProduccionInsumosOrden = new HashSet<ProduccionInsumosOrden>();
            ProduccionMaquinaOperario = new HashSet<ProduccionMaquinaOperario>();
            ProduccionOrdenItemProgramacion = new HashSet<ProduccionOrdenItemProgramacion>();
            ProduccionProgramacionItem = new HashSet<ProduccionProgramacionItem>();
        }

        [Column("EmpleadoID")]
        public int EmpleadoId { get; set; }
        /// <summary>
        /// Se reasigna el nro de empleado a un Nro de Operario (Esto evita tener que seleccionar de la tabla empleados el operador de la maquina, y permitira adicionar datos a los que sean operarios, ademas de crear una nueva numeracion correlativa)
        /// </summary>
        [Key]
        [Column("OperadorID")]
        public int OperadorId { get; set; }

        [ForeignKey("EmpleadoId")]
        [InverseProperty("ProduccionOperario")]
        public virtual Empleado Empleado { get; set; }
        [InverseProperty("Operador")]
        public virtual ICollection<ProduccionInsumosOrden> ProduccionInsumosOrden { get; set; }
        [InverseProperty("Operador")]
        public virtual ICollection<ProduccionMaquinaOperario> ProduccionMaquinaOperario { get; set; }
        [InverseProperty("Operador")]
        public virtual ICollection<ProduccionOrdenItemProgramacion> ProduccionOrdenItemProgramacion { get; set; }
        [InverseProperty("Operador")]
        public virtual ICollection<ProduccionProgramacionItem> ProduccionProgramacionItem { get; set; }
    }
}