// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Ordenes de Produccion
    /// </summary>
    [Index("ClienteId", Name = "IX_ProduccionOrden_ClienteID")]
    [Index("VendedorId", Name = "IX_ProduccionOrden_VendedorID")]
    public partial class ProduccionOrden
    {
        public ProduccionOrden()
        {
            ProduccionOrdenItem = new HashSet<ProduccionOrdenItem>();
        }

        [Key]
        [Column("OrdenProduccionID")]
        public int OrdenProduccionId { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime Fecha { get; set; }
        [Column("ClienteID")]
        public int? ClienteId { get; set; }
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// 0-Presupuesto 1-Presup. Confirmado 2-En Produccion 3-Terminado, etc
        /// </summary>
        [Column("EstadoOrdenID")]
        public int? EstadoOrdenId { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImporteTotal { get; set; }
        [Column("VendedorID")]
        public int? VendedorId { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("ProduccionOrden")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("EstadoOrdenId")]
        [InverseProperty("ProduccionOrden")]
        public virtual ProduccionOrdenEstadoTipo EstadoOrden { get; set; }
        [ForeignKey("VendedorId")]
        [InverseProperty("ProduccionOrden")]
        public virtual Vendedor Vendedor { get; set; }
        [InverseProperty("OrdenProduccion")]
        public virtual ICollection<ProduccionOrdenItem> ProduccionOrdenItem { get; set; }
    }
}