// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("CodigoBaseId", Name = "IX_ProductoImpuesto_CodigoBaseID")]
    [Index("ImpuestoId", Name = "IX_ProductoImpuesto_ImpuestoID")]
    public partial class ProductoImpuesto
    {
        [Column("CodigoBaseID")]
        public int CodigoBaseId { get; set; }
        [Column("ImpuestoID")]
        public short ImpuestoId { get; set; }
        [Column(TypeName = "decimal(8, 3)")]
        public decimal? PorcImpuesto { get; set; }
        [Column(TypeName = "money")]
        public decimal? ImpImpuesto { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column("NoAplicaCF")]
        public bool? NoAplicaCf { get; set; }

        [ForeignKey("CodigoBaseId")]
        [InverseProperty("ProductoImpuesto")]
        public virtual ProductoBase CodigoBase { get; set; }
        [ForeignKey("ImpuestoId")]
        [InverseProperty("ProductoImpuesto")]
        public virtual Impuesto Impuesto { get; set; }
    }
}