// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("ProdCostoId", Name = "IX_ProductoCostoDescuento")]
    [Index("ProdCostoId", "DescuentoCompraId", Name = "IX_ProductoCostoDescuentoTipo", IsUnique = true)]
    public partial class ProductoCostoDescuento
    {
        [Column(TypeName = "decimal(9, 4)")]
        public decimal Porcentaje { get; set; }
        /// <summary>
        /// 0-Se realiza el Descuento Sobre el Ultimo resuldado del Descuento Anterior (Si ubiere) 1-Se trata de un descuento directo sobre el Precio de Compra
        /// </summary>
        public byte TipoCalculo { get; set; }
        /// <summary>
        /// Orden en que se presenta en la tabla y orden para realizra el Calculo
        /// </summary>
        public byte OrdenPresentacion { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Indica el Tipo de Descuento a Aplicar (Se obtiene de AlmaNET.ProductoCostoDescuentoTipo)
        /// </summary>
        [Column("DescuentoCompraID")]
        public short DescuentoCompraId { get; set; }
        [Column(TypeName = "money")]
        public decimal ImporteFijo { get; set; }
        [Column("ProdCostoID")]
        public int ProdCostoId { get; set; }

        [ForeignKey("DescuentoCompraId")]
        [InverseProperty("ProductoCostoDescuento")]
        public virtual ProductoCostoTipo DescuentoCompra { get; set; }
        [ForeignKey("ProdCostoId")]
        [InverseProperty("ProductoCostoDescuento")]
        public virtual ProductoCosto ProdCosto { get; set; }
    }
}