// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// CUIDADO, se puede borrar un producto que era un insumo y quedara mal armado el Precio del Proceso
    /// </summary>
    [Index("DescripcionPlanilla", Name = "IX_ProductoProcesoInsumo_DescripcionPlanilla")]
    [Index("ProductoInsumoId", Name = "IX_ProductoProcesoInsumo_ProductoInsumoID")]
    [Index("SubProcesoId", Name = "IX_ProductoProcesoInsumo_SubProcesoID")]
    public partial class ProductoProcesoInsumo
    {
        [Column("SubProcesoID")]
        public int SubProcesoId { get; set; }
        [Column("ProductoInsumoID")]
        public int ProductoInsumoId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal Cantidad { get; set; }
        /// <summary>
        /// Descripcion a Utilizar (Nombre Generico), para la Planillas de Insumos diarios
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string DescripcionPlanilla { get; set; }
        [Key]
        public int RegistroInsumo { get; set; }

        [ForeignKey("ProductoInsumoId")]
        [InverseProperty("ProductoProcesoInsumo")]
        public virtual ProductoPresentacion ProductoInsumo { get; set; }
        [ForeignKey("SubProcesoId")]
        [InverseProperty("ProductoProcesoInsumo")]
        public virtual ProductoProcesoPrecio SubProceso { get; set; }
    }
}