// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EmpleadoId", Name = "IX_ProduccionTecnico_EmpleadoID")]
    public partial class ProduccionTecnico
    {
        [Column("EmpleadoID")]
        public int EmpleadoId { get; set; }
        /// <summary>
        /// Se reasigna el nro de empleado a un Nro de Tecnico (Esto evita tener que seleccionar de la tabla empleados el Tecnico de una orden de servicio, y permitira adicionar datos a los que sean exclusivos de un tecnico, ademas de crear una nueva numeracion correlativa)
        /// </summary>
        [Key]
        [Column("TecnicoID")]
        public int TecnicoId { get; set; }

        [ForeignKey("EmpleadoId")]
        [InverseProperty("ProduccionTecnico")]
        public virtual Empleado Empleado { get; set; }
    }
}