// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProductoComisionEspecial
    {
        [Key]
        public int RegComisProd { get; set; }
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PorcComisGestor { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PorcComisSupervisor { get; set; }

        [ForeignKey("CodigoId")]
        [InverseProperty("ProductoComisionEspecial")]
        public virtual Producto Codigo { get; set; }
    }
}