// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ProveedorBanco
    {
        [Column("ProveedorID")]
        public int ProveedorId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CuentaNro { get; set; }
        [Column("BancoCBU")]
        [StringLength(22)]
        [Unicode(false)]
        public string BancoCbu { get; set; }
        [Column("BancoAliasCBU")]
        [StringLength(50)]
        [Unicode(false)]
        public string BancoAliasCbu { get; set; }
        [Key]
        [Column("RegistroBancoProvID")]
        public int RegistroBancoProvId { get; set; }
    }
}