// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Detalles", Name = "IX_ProveedorMarca_Detalles")]
    [Index("MarcaId", Name = "IX_ProveedorMarca_MarcaID")]
    [Index("ProveedorId", Name = "IX_ProveedorMarca_ProveedorID")]
    public partial class ProveedorMarca
    {
        /// <summary>
        /// Proveedor q vende productos de esta marca
        /// </summary>
        [Column("ProveedorID")]
        public int ProveedorId { get; set; }
        /// <summary>
        /// Marca que vende el Proveedor
        /// </summary>
        [Column("MarcaID")]
        public int MarcaId { get; set; }
        /// <summary>
        /// Campo Unico
        /// </summary>
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Magen de Utilidad que se aplican a productos de esta Marca
        /// </summary>
        [Column(TypeName = "decimal(9, 4)")]
        public decimal? PorcUtilidad { get; set; }
        /// <summary>
        /// Comentarios
        /// </summary>
        [StringLength(150)]
        [Unicode(false)]
        public string Detalles { get; set; }
        /// <summary>
        /// %Comicion que se otorga al vendedor por la venta de productos de esta marca
        /// </summary>
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? ComicionVenta { get; set; }

        [ForeignKey("MarcaId")]
        [InverseProperty("ProveedorMarca")]
        public virtual ProductoMarca Marca { get; set; }
        [ForeignKey("ProveedorId")]
        [InverseProperty("ProveedorMarca")]
        public virtual Proveedor Proveedor { get; set; }
    }
}