// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Proyectos permite el segimiento de gastos o de Operaciones, realizadas para la concrecion de un determinado proyecto, y luego poder determinar los gastos realizados, como tambien el mobimiento de las distintas cuentas con relacion a este proyecto
    /// </summary>
    [Index("Descripcion", Name = "IX_Proyecto_Descripcion")]
    public partial class Proyecto
    {
        public Proyecto()
        {
            AutorizacionCompra = new HashSet<AutorizacionCompra>();
            Evento = new HashSet<Evento>();
            LibroDiario = new HashSet<LibroDiario>();
            LibroDiarioBalance = new HashSet<LibroDiarioBalance>();
            LibroDiarioItem = new HashSet<LibroDiarioItem>();
            OperacionCobro = new HashSet<OperacionCobro>();
            OperacionCobroWeb = new HashSet<OperacionCobroWeb>();
            OperacionCompra = new HashSet<OperacionCompra>();
            OperacionCredito = new HashSet<OperacionCredito>();
            OperacionDespacho = new HashSet<OperacionDespacho>();
            OperacionInventario = new HashSet<OperacionInventario>();
            OperacionPago = new HashSet<OperacionPago>();
            OperacionPagoAutorizacion = new HashSet<OperacionPagoAutorizacion>();
            OperacionPedidoCompra = new HashSet<OperacionPedidoCompra>();
            OperacionPedidoVenta = new HashSet<OperacionPedidoVenta>();
            OperacionRecepcion = new HashSet<OperacionRecepcion>();
            OperacionRendicion = new HashSet<OperacionRendicion>();
            OperacionVale = new HashSet<OperacionVale>();
            OperacionValeContra = new HashSet<OperacionValeContra>();
            OperacionVenta = new HashSet<OperacionVenta>();
            OrdenServicio = new HashSet<OrdenServicio>();
            Perfil = new HashSet<Perfil>();
            PlanDeCuentaInventario = new HashSet<PlanDeCuentaInventario>();
            PlanDeCuentaProyeccion = new HashSet<PlanDeCuentaProyeccion>();
        }

        /// <summary>
        /// Codigo Proyecto
        /// </summary>
        [Key]
        [Column("ProyectoID")]
        public short ProyectoId { get; set; }
        /// <summary>
        /// Nombre asignado al Proyecto
        /// </summary>
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column("ClienteID")]
        public int? ClienteId { get; set; }
        [Column("ZonaID")]
        public int? ZonaId { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Domicilio { get; set; }
        [Unicode(false)]
        public string Observacion { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("Proyecto")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("ZonaId")]
        [InverseProperty("Proyecto")]
        public virtual ZonaGeografica Zona { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<AutorizacionCompra> AutorizacionCompra { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<Evento> Evento { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<LibroDiario> LibroDiario { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<LibroDiarioBalance> LibroDiarioBalance { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<LibroDiarioItem> LibroDiarioItem { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionCobro> OperacionCobro { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionCobroWeb> OperacionCobroWeb { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionCompra> OperacionCompra { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionCredito> OperacionCredito { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionDespacho> OperacionDespacho { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionInventario> OperacionInventario { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionPago> OperacionPago { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionPagoAutorizacion> OperacionPagoAutorizacion { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionPedidoCompra> OperacionPedidoCompra { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionPedidoVenta> OperacionPedidoVenta { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionRecepcion> OperacionRecepcion { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionRendicion> OperacionRendicion { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionVale> OperacionVale { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionValeContra> OperacionValeContra { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OperacionVenta> OperacionVenta { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<OrdenServicio> OrdenServicio { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<Perfil> Perfil { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<PlanDeCuentaInventario> PlanDeCuentaInventario { get; set; }
        [InverseProperty("Proyecto")]
        public virtual ICollection<PlanDeCuentaProyeccion> PlanDeCuentaProyeccion { get; set; }
    }
}