// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Titulo", Name = "IX_Publicidad_Titulo")]
    public partial class Publicidad
    {
        [Key]
        [Column("PublicidadID")]
        public int PublicidadId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Titulo { get; set; }
        [Required]
        [Unicode(false)]
        public string Contenido { get; set; }
        /// <summary>
        /// 1-Canal Youtube 2-Publicaciones Facebook 3-xxx
        /// </summary>
        [Column("PublicidadTipoID")]
        public short PublicidadTipoId { get; set; }
        public byte[] Video { get; set; }
        [Column("SectorID")]
        public short? SectorId { get; set; }
        [Column("SucursalID")]
        public short? SucursalId { get; set; }
        public byte[] Imagen { get; set; }
        public bool? Inhabilitado { get; set; }
        public short? DiasVigencia { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaModificacion { get; set; }

        [ForeignKey("SectorId")]
        [InverseProperty("Publicidad")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SucursalId")]
        [InverseProperty("Publicidad")]
        public virtual Sucursal Sucursal { get; set; }
    }
}