// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("MovId", Name = "IX_RepartoRendicion_MovID")]
    [Index("TipoOperacionId", "RegistroOperacionId", Name = "IX_RepartoRendicion_TipoOperacionNroOperacion")]
    [Index("MovId", "TipoOperacionId", Name = "IX_RepartoRendicion_movIDTipoOperacionID")]
    public partial class RepartoRendicion
    {
        [Key]
        [Column("IDRepartoRendion")]
        public int IdrepartoRendion { get; set; }
        /// <summary>
        /// De AlmaNet.OperacionTipo - Indica si se trata de una Venta, Compra, Pago, Cobro
        /// </summary>
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        /// <summary>
        /// El Nro de Venta, Compra, Pago, Cobro que Genero el detalle
        /// </summary>
        [Column("RegistroOperacionID")]
        public int RegistroOperacionId { get; set; }
        /// <summary>
        /// Indica la Fecha y hora q ingreso de Nuevo al Deposito (pendiente)
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraRegreso { get; set; }
        [StringLength(150)]
        public string Detalle { get; set; }
        /// <summary>
        /// Nro Reparto Planilla de Carga
        /// </summary>
        [Column("MovID")]
        public int MovId { get; set; }

        [ForeignKey("MovId")]
        [InverseProperty("RepartoRendicion")]
        public virtual TransporteCargaMovimiento Mov { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("RepartoRendicion")]
        public virtual OperacionCobro OperacionCobro { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("RepartoRendicion")]
        public virtual OperacionCompra OperacionCompra { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("RepartoRendicion")]
        public virtual OperacionPago OperacionPago { get; set; }
        [ForeignKey("TipoOperacionId,RegistroOperacionId")]
        [InverseProperty("RepartoRendicion")]
        public virtual OperacionVenta OperacionVenta { get; set; }
    }
}