// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Define las distinas Hojas de rutas Especificadas para los vendedores y Repartidores/Transportes
    /// </summary>
    [Index("Descripcion", Name = "IX_Ruta_Descripcion")]
    [Index("NroOrden", Name = "IX_Ruta_NroOrden")]
    [Index("ZonaId", Name = "IX_Ruta_ZonaID")]
    [Index("ZonaId", "NroOrden", Name = "IX_Ruta_ZonaID_NroOrden")]
    public partial class Ruta
    {
        public Ruta()
        {
            EntidadSucursal = new HashSet<EntidadSucursal>();
        }

        [Key]
        [Column("RutaID")]
        public int RutaId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// Indica la Zona en la q se encuentra la Sucursal
        /// </summary>
        [Column("ZonaID")]
        public int? ZonaId { get; set; }
        /// <summary>
        /// Indica el Orden de Recorrido asigando dentro de la Zona (no puede repetir en la misma Zona)
        /// </summary>
        public int NroOrden { get; set; }

        [InverseProperty("Ruta")]
        public virtual ICollection<EntidadSucursal> EntidadSucursal { get; set; }
    }
}