// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Indica el estadpo de la garantia, ingresadoa, procesada, en el despachado  de la empresa, En el Tecnioco, esperando respuesta tecnico, Esperando respuesta Cliente, Recibida en l aempresa, Entregafo al Cliente, Finalizada
    /// </summary>
    public partial class ServisEstado
    {
        public ServisEstado()
        {
            Servis = new HashSet<Servis>();
            ServisProcesos = new HashSet<ServisProcesos>();
        }

        [Key]
        [Column("EstadoServisID")]
        public short EstadoServisId { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// Si un Servicio tiene este estado se encuntra Finalizado
        /// </summary>
        public bool EsFinalizado { get; set; }

        [InverseProperty("EstadoServis")]
        public virtual ICollection<Servis> Servis { get; set; }
        [InverseProperty("EstadoServis")]
        public virtual ICollection<ServisProcesos> ServisProcesos { get; set; }
    }
}