// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class ServisProcesos
    {
        [Column("ServisItemID")]
        public int ServisItemId { get; set; }
        /// <summary>
        /// 0-Cliente 1-La casa 2-Proveedor 4-Servicio Tecnico
        /// </summary>
        public byte TipoProceso { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Unicode(false)]
        public string Comentario { get; set; }
        [Key]
        [Column("ServisProcesoID")]
        public int ServisProcesoId { get; set; }
        /// <summary>
        /// Operador q atendio
        /// </summary>
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        /// <summary>
        /// Indico si genera un evento (Aviso Vinculado)
        /// </summary>
        [Column("RegEventoID")]
        public int? RegEventoId { get; set; }
        /// <summary>
        /// Indica el Estado en el Momento *echa
        /// </summary>
        [Column("EstadoServisID")]
        public short? EstadoServisId { get; set; }
        [Column("TransporteID")]
        public int? TransporteId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("ServisProcesos")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("EstadoServisId")]
        [InverseProperty("ServisProcesos")]
        public virtual ServisEstado EstadoServis { get; set; }
        [ForeignKey("RegEventoId")]
        [InverseProperty("ServisProcesos")]
        public virtual Evento RegEvento { get; set; }
        [ForeignKey("ServisItemId")]
        [InverseProperty("ServisProcesos")]
        public virtual ServisItem ServisItem { get; set; }
        [ForeignKey("TransporteId")]
        [InverseProperty("ServisProcesos")]
        public virtual Transporte Transporte { get; set; }
    }
}