// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_SoporteCasoEstado_Descripcion")]
    public partial class SoporteCasoEstado
    {
        public SoporteCasoEstado()
        {
            SoporteCaso = new HashSet<SoporteCaso>();
        }

        [Key]
        [Column("EstadoID")]
        public int EstadoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("Estado")]
        public virtual ICollection<SoporteCaso> SoporteCaso { get; set; }
    }
}