// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class SoporteAbono
    {
        public SoporteAbono()
        {
            SoporteAbonoCasoTarea = new HashSet<SoporteAbonoCasoTarea>();
        }

        [Key]
        [Column("SoporteAbonoID")]
        public int SoporteAbonoId { get; set; }
        [Column("ItemID")]
        public int? ItemId { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? SaldoCantidad { get; set; }

        [ForeignKey("ItemId")]
        [InverseProperty("SoporteAbono")]
        public virtual OperacionItemProducto Item { get; set; }
        [InverseProperty("SoporteAbono")]
        public virtual ICollection<SoporteAbonoCasoTarea> SoporteAbonoCasoTarea { get; set; }
    }
}