// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class SoporteAbonoCasoTarea
    {
        [Key]
        [Column("SoporteAbonoTareaID")]
        public int SoporteAbonoTareaId { get; set; }
        [Column("SoporteAbonoID")]
        public int SoporteAbonoId { get; set; }
        [Column("TareaID")]
        public int TareaId { get; set; }

        [ForeignKey("SoporteAbonoId")]
        [InverseProperty("SoporteAbonoCasoTarea")]
        public virtual SoporteAbono SoporteAbono { get; set; }
        [ForeignKey("TareaId")]
        [InverseProperty("SoporteAbonoCasoTarea")]
        public virtual SoporteCasoTarea Tarea { get; set; }
    }
}