// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_SoporteCasoTipo_Descripcion")]
    public partial class SoporteCasoTipo
    {
        public SoporteCasoTipo()
        {
            SoporteCaso = new HashSet<SoporteCaso>();
        }

        [Key]
        [Column("TipoCasoID")]
        public short TipoCasoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public bool? EsAbono { get; set; }

        [InverseProperty("TipoCaso")]
        public virtual ICollection<SoporteCaso> SoporteCaso { get; set; }
    }
}