// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Table("TableDB")]
    [Index("TableId", Name = "IX_Tabla", IsUnique = true)]
    [Index("TableName", Name = "IX_TableDB_TableName")]
    public partial class TableDb
    {
        public TableDb()
        {
            BuscarConfiguracion = new HashSet<BuscarConfiguracion>();
            LicenciaIndiceTabla = new HashSet<LicenciaIndiceTabla>();
        }

        [Key]
        [Column("TableID")]
        public int TableId { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string TableName { get; set; }

        [InverseProperty("Table")]
        public virtual ICollection<BuscarConfiguracion> BuscarConfiguracion { get; set; }
        [InverseProperty("Table")]
        public virtual ICollection<LicenciaIndiceTabla> LicenciaIndiceTabla { get; set; }
    }
}