// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_TransportePasRecorridoTipo_Descripcion")]
    public partial class TransportePasRecorridoTipo
    {
        public TransportePasRecorridoTipo()
        {
            TransportePasLineaRecorrido = new HashSet<TransportePasLineaRecorrido>();
        }

        /// <summary>
        /// ID del Tipo de Recorrido
        /// </summary>
        [Key]
        [Column("TipoRecorridoID")]
        public short TipoRecorridoId { get; set; }
        /// <summary>
        /// Descripción del Recorrido(Fijo - Eventuales - Escolares - etc..)
        /// </summary>
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// Dias en que se raliza el recorrido
        /// </summary>
        public int DiasRecorrido { get; set; }
        /// <summary>
        /// Indicador si el recorriedo es realizado los dias Feriados
        /// </summary>
        public bool DiasLaborables { get; set; }

        [InverseProperty("TipoRecorridoNavigation")]
        public virtual ICollection<TransportePasLineaRecorrido> TransportePasLineaRecorrido { get; set; }
    }
}