// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("AlmaUserId", Name = "IX_TransporteAutorizacionCargaDetalle_AlmaUserID")]
    [Index("AutoizacionCargaId", Name = "IX_TransporteAutorizacionCargaDetalle_AutoizacionCargaID")]
    [Index("DestinolId", Name = "IX_TransporteAutorizacionCargaDetalle_DestinolID")]
    [Index("FechaHoraFinal", Name = "IX_TransporteAutorizacionCargaDetalle_FechaHoraFinal")]
    [Index("LiquidacionChoferId", Name = "IX_TransporteAutorizacionCargaDetalle_LiquidacionChoferID")]
    [Index("OrigenId", Name = "IX_TransporteAutorizacionCargaDetalle_OrigenID")]
    [Index("TraspViajeId", Name = "IX_TransporteAutorizacionCargaDetalle_TraspViajeID")]
    public partial class TransporteAutorizacionCargaDetalle
    {
        public TransporteAutorizacionCargaDetalle()
        {
            TransporteAutorizacionCargaDetalleTransporteCarga = new HashSet<TransporteAutorizacionCargaDetalleTransporteCarga>();
            TransporteAutorizacionRemito = new HashSet<TransporteAutorizacionRemito>();
            TransporteCargaConvenioColectivoDetalle = new HashSet<TransporteCargaConvenioColectivoDetalle>();
            TransporteCombustibleRuteo = new HashSet<TransporteCombustibleRuteo>();
        }

        [Key]
        [Column("AutorizDetalleID")]
        public int AutorizDetalleId { get; set; }
        public byte Orden { get; set; }
        [Column("OrigenID")]
        public int OrigenId { get; set; }
        [Column(TypeName = "money")]
        public decimal ComisionTransporte { get; set; }
        [Column("DestinolID")]
        public int DestinolId { get; set; }
        public int? OdometroInicio { get; set; }
        public int? OdometroFinal { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraFinal { get; set; }
        [Column(TypeName = "decimal(12, 4)")]
        public decimal? PromedioValorKm { get; set; }
        public bool? EsViajeVacio { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? KmRecorridos { get; set; }
        [Column(TypeName = "money")]
        public decimal? ComisionConductor { get; set; }
        [Column("LiquidacionChoferID")]
        public int? LiquidacionChoferId { get; set; }
        [Column("TraspViajeID")]
        public int TraspViajeId { get; set; }
        [Column("AutoizacionCargaID")]
        public int AutoizacionCargaId { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }
        [Column("ConductorID")]
        public int? ConductorId { get; set; }
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("TransporteAutorizacionCargaDetalle")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("AutoizacionCargaId")]
        [InverseProperty("TransporteAutorizacionCargaDetalle")]
        public virtual TransporteAutorizacionCarga AutoizacionCarga { get; set; }
        [ForeignKey("ConductorId")]
        [InverseProperty("TransporteAutorizacionCargaDetalle")]
        public virtual TransporteConductor Conductor { get; set; }
        [ForeignKey("DestinolId")]
        [InverseProperty("TransporteAutorizacionCargaDetalleDestinol")]
        public virtual TransporteOrigenDestino Destinol { get; set; }
        [ForeignKey("LiquidacionChoferId")]
        [InverseProperty("TransporteAutorizacionCargaDetalle")]
        public virtual TransporteCargaLiquidacion LiquidacionChofer { get; set; }
        [ForeignKey("OrigenId")]
        [InverseProperty("TransporteAutorizacionCargaDetalleOrigen")]
        public virtual TransporteOrigenDestino Origen { get; set; }
        [ForeignKey("TraspViajeId")]
        [InverseProperty("TransporteAutorizacionCargaDetalle")]
        public virtual TransporteViaje TraspViaje { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransporteAutorizacionCargaDetalle")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
        [InverseProperty("AutorizDetalle")]
        public virtual ICollection<TransporteAutorizacionCargaDetalleTransporteCarga> TransporteAutorizacionCargaDetalleTransporteCarga { get; set; }
        [InverseProperty("AutorizDetalle")]
        public virtual ICollection<TransporteAutorizacionRemito> TransporteAutorizacionRemito { get; set; }
        [InverseProperty("AutorizDetalle")]
        public virtual ICollection<TransporteCargaConvenioColectivoDetalle> TransporteCargaConvenioColectivoDetalle { get; set; }
        [InverseProperty("AutorizDetalle")]
        public virtual ICollection<TransporteCombustibleRuteo> TransporteCombustibleRuteo { get; set; }
    }
}