// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("LiquidacionId", Name = "IX_TransportePasLiquidacionDetalle_LiquidacionID")]
    [Index("ProductoPresentacionId", Name = "IX_TransportePasLiquidacionDetalle_ProductoPresentacionID")]
    public partial class TransportePasLiquidacionDetalle
    {
        /// <summary>
        /// Presentacion del producto que contiene el Nro de Serie
        /// </summary>
        [Column("ProductoPresentacionID")]
        public int ProductoPresentacionId { get; set; }
        public int? Cantiudad { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        /// <summary>
        /// Nro Liquidacion 
        /// </summary>
        [Column("LiquidacionID")]
        public int LiquidacionId { get; set; }
    }
}