// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("ConvColectivoId", Name = "IX_TransporteCargaConvenioColectivoDetalleConvColecectivoID")]
    public partial class TransporteCargaConvenioColectivoDetalle
    {
        [Key]
        [Column("ConvColectivoDetalleID")]
        public int ConvColectivoDetalleId { get; set; }
        [Column("ConvColectivoID")]
        public int ConvColectivoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaHoraFinal { get; set; }
        [Column("AutorizDetalleID")]
        public int? AutorizDetalleId { get; set; }
        [Column("OrigenID")]
        public int OrigenId { get; set; }
        [Column("DestinolID")]
        public int DestinolId { get; set; }
        public int OdometroInicio { get; set; }
        public int OdometroFinal { get; set; }
        public int? KmRecorridos { get; set; }
        public short? ControlDescarga { get; set; }
        public bool EsViajeVacio { get; set; }
        [Column("CodigoID")]
        public int? CodigoId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal KmCruceFrontera { get; set; }
        [Unicode(false)]
        public string Obsevaciones { get; set; }
        public int? KmAl100 { get; set; }
        public int? KmLiquidar { get; set; }
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }
        [Column("TipoCargaID")]
        public short? TipoCargaId { get; set; }
        public int? Km42420 { get; set; }

        [ForeignKey("AutorizDetalleId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalle")]
        public virtual TransporteAutorizacionCargaDetalle AutorizDetalle { get; set; }
        [ForeignKey("CodigoId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalle")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("ConvColectivoId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalle")]
        public virtual TransporteCargaConvencionColectivo ConvColectivo { get; set; }
        [ForeignKey("DestinolId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalleDestinol")]
        public virtual TransporteOrigenDestino Destinol { get; set; }
        [ForeignKey("OrigenId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalleOrigen")]
        public virtual TransporteOrigenDestino Origen { get; set; }
        [ForeignKey("TipoCargaId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalle")]
        public virtual TransporteTipoCarga TipoCarga { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransporteCargaConvenioColectivoDetalle")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
    }
}