// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_TransporteClasificacion_Descripcion")]
    public partial class TransporteClasificacion
    {
        public TransporteClasificacion()
        {
            Transporte = new HashSet<Transporte>();
        }

        [Key]
        [Column("TranspClasificacionID")]
        public int TranspClasificacionId { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public bool? PoseeLiquidacion { get; set; }

        [InverseProperty("TranspClasificacion")]
        public virtual ICollection<Transporte> Transporte { get; set; }
    }
}