// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_TransporteCargaEstadoFactura_Descripcion")]
    public partial class TransporteCargaEstadoFactura
    {
        public TransporteCargaEstadoFactura()
        {
            TransporteCarga = new HashSet<TransporteCarga>();
            TransporteCargaConceptosAdicionales = new HashSet<TransporteCargaConceptosAdicionales>();
        }

        [Key]
        [Column("FacturaEstadoID")]
        public int FacturaEstadoId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("FacturaEstado")]
        public virtual ICollection<TransporteCarga> TransporteCarga { get; set; }
        [InverseProperty("FacturaEstado")]
        public virtual ICollection<TransporteCargaConceptosAdicionales> TransporteCargaConceptosAdicionales { get; set; }
    }
}