// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("ConductorId", Name = "IX_TransportePasProgramacionDiaDetalle_ConductorID")]
    [Index("ProgId", Name = "IX_TransportePasProgramacionDiaDetalle_ProgID")]
    [Index("RecorridoId", Name = "IX_TransportePasProgramacionDiaDetalle_RecorridoID")]
    [Index("VehiculoId", Name = "IX_TransportePasProgramacionDiaDetalle_VehiculoID")]
    public partial class TransportePasProgramacionDiaDetalle
    {
        public TransportePasProgramacionDiaDetalle()
        {
            TransportePasRecorrido = new HashSet<TransportePasRecorrido>();
        }

        [Column("RecorridoID")]
        public int RecorridoId { get; set; }
        [Column("ConductorID")]
        public int ConductorId { get; set; }
        [Key]
        [Column("ProgDetalleID")]
        public int ProgDetalleId { get; set; }
        public TimeSpan HoraRecorrido { get; set; }
        [Column("VehiculoID")]
        public int VehiculoId { get; set; }
        [Column("ProgID")]
        public int ProgId { get; set; }

        [ForeignKey("ConductorId")]
        [InverseProperty("TransportePasProgramacionDiaDetalle")]
        public virtual TransporteConductor Conductor { get; set; }
        [ForeignKey("ProgId")]
        [InverseProperty("TransportePasProgramacionDiaDetalle")]
        public virtual TransportePasProgramacionDia Prog { get; set; }
        [ForeignKey("RecorridoId")]
        [InverseProperty("TransportePasProgramacionDiaDetalle")]
        public virtual TransportePasLineaRecorrido Recorrido { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransportePasProgramacionDiaDetalle")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
        [InverseProperty("ProgDetalle")]
        public virtual ICollection<TransportePasRecorrido> TransportePasRecorrido { get; set; }
    }
}