// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Para Armar el Ruteo (Circuito de Vehiculo)
    /// </summary>
    public partial class TransporteViajeCelular
    {
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHoraServer { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHoraMobil { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        [Column("ConductorID")]
        public int ConductorId { get; set; }
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }
        public int Odometro { get; set; }
        public bool Situacion { get; set; }
        [Column(TypeName = "decimal(12, 10)")]
        public decimal? Latitud { get; set; }
        [Column(TypeName = "decimal(12, 10)")]
        public decimal? Longuitud { get; set; }
        [Unicode(false)]
        public string Ubicacion { get; set; }
        [Unicode(false)]
        public string Observacion { get; set; }
        public bool? EsVacio { get; set; }
        /// <summary>
        /// 0=A CARGAR,1=A DESCARGAR,2=DESCARGA PARCIAL,3=DESCARGA FINAL,4=SIN VIAJE
        /// </summary>
        public byte? ViajeAccion { get; set; }
        [Column("AlmaUserID")]
        public int? AlmaUserId { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("TransporteViajeCelular")]
        public virtual Usuario AlmaUser { get; set; }
    }
}