// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class TransporteCombustibleImputacion
    {
        public TransporteCombustibleImputacion()
        {
            TransporteCombustibleRuteo = new HashSet<TransporteCombustibleRuteo>();
        }

        [Key]
        [Column("RegistroCargCombID")]
        public int RegistroCargCombId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHoraRemito { get; set; }
        [Column("ConductorID")]
        public int? ConductorId { get; set; }
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }
        public int Odometro { get; set; }
        [Column(TypeName = "decimal(13, 4)")]
        public decimal? Litros { get; set; }
        public int? RemitoTalonario { get; set; }
        public int? RemitoNro { get; set; }
        /// <summary>
        /// Registro de Imputacion
        /// </summary>
        public int RegistroImputacion { get; set; }
        [Column(TypeName = "money")]
        public decimal Importe { get; set; }

        [ForeignKey("ConductorId")]
        [InverseProperty("TransporteCombustibleImputacion")]
        public virtual TransporteConductor Conductor { get; set; }
        [ForeignKey("RegistroImputacion")]
        [InverseProperty("TransporteCombustibleImputacion")]
        public virtual OperacionImputacion RegistroImputacionNavigation { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransporteCombustibleImputacion")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
        [InverseProperty("RegistroCargComb")]
        public virtual ICollection<TransporteCombustibleRuteo> TransporteCombustibleRuteo { get; set; }
    }
}