// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_TransporteClaseBultos_Descripcion")]
    public partial class TransporteClaseBultos
    {
        public TransporteClaseBultos()
        {
            TransporteCrt = new HashSet<TransporteCrt>();
        }

        [Key]
        [Column("IDClaseBultos")]
        public short IdclaseBultos { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        public bool EstaHabilitado { get; set; }
        [Column("IDClaseBultoserER")]
        public short? IdclaseBultoserEr { get; set; }

        [InverseProperty("C11idclaseBultosNavigation")]
        public virtual ICollection<TransporteCrt> TransporteCrt { get; set; }
    }
}