// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Indica el Tipo de Boleto
    /// </summary>
    [Index("FechaHoraCierre", Name = "IX_TransportePasRecorrido_FechaHoraCierre")]
    [Index("FechaHoraInicio", Name = "IX_TransportePasRecorrido_FechaHoraInicio")]
    [Index("LiquidacionId", Name = "IX_TransportePasRecorrido_LiquidacionID")]
    [Index("ProgDetalleId", Name = "IX_TransportePasRecorrido_ProgDetalleID")]
    public partial class TransportePasRecorrido
    {
        public TransportePasRecorrido()
        {
            TransportePasRecorridoDetalle = new HashSet<TransportePasRecorridoDetalle>();
        }

        [Column(TypeName = "datetime")]
        public DateTime FechaHoraInicio { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Liquidacuion RecorridoID
        /// </summary>
        [Key]
        [Column("LiquidacionRecID")]
        public int LiquidacionRecId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHoraCierre { get; set; }
        /// <summary>
        /// Nro Liquidacion 
        /// </summary>
        [Column("LiquidacionID")]
        public int? LiquidacionId { get; set; }
        [Column("ProgDetalleID")]
        public int? ProgDetalleId { get; set; }
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }
        [Column("RecorridoID")]
        public int? RecorridoId { get; set; }
        [Column(TypeName = "decimal(4, 2)")]
        public decimal? Vueltas { get; set; }

        [ForeignKey("LiquidacionId")]
        [InverseProperty("TransportePasRecorrido")]
        public virtual TransportePasLiquidacion Liquidacion { get; set; }
        [ForeignKey("ProgDetalleId")]
        [InverseProperty("TransportePasRecorrido")]
        public virtual TransportePasProgramacionDiaDetalle ProgDetalle { get; set; }
        [ForeignKey("RecorridoId")]
        [InverseProperty("TransportePasRecorrido")]
        public virtual TransportePasLineaRecorrido Recorrido { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransportePasRecorrido")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
        [InverseProperty("LiquidacionRec")]
        public virtual ICollection<TransportePasRecorridoDetalle> TransportePasRecorridoDetalle { get; set; }
    }
}