// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("AutorizDetalleId", Name = "IX_TransporteAutorizacionCargaDetalleTransporteCarga_AutorizDetalleID")]
    [Index("CargaId", Name = "IX_TransporteAutorizacionCargaDetalleTransporteCarga_CargaID")]
    [Index("ProductoPrecioId", Name = "IX_TransporteAutorizacionCargaDetalleTransporteCarga_ProductoPrecioID")]
    public partial class TransporteAutorizacionCargaDetalleTransporteCarga
    {
        public TransporteAutorizacionCargaDetalleTransporteCarga()
        {
            TransporteAutorizacionRemito = new HashSet<TransporteAutorizacionRemito>();
        }

        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Column("AutorizDetalleID")]
        public int AutorizDetalleId { get; set; }
        [Column("CargaID")]
        public int CargaId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? Cantidad { get; set; }
        [Column(TypeName = "money")]
        public decimal? TarifaTotalItem { get; set; }
        [Column("ProductoPrecioID")]
        public int? ProductoPrecioId { get; set; }
        [Column(TypeName = "money")]
        public decimal TarifaUnidad { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NroOperacion { get; set; }
        public short RemitoSuc { get; set; }
        public int NroRemito { get; set; }
        public bool TipoTarifa { get; set; }
        public bool? EnTrasbordo { get; set; }
        [Column(TypeName = "money")]
        public decimal? Cotizacion { get; set; }
        [Column("MonedaID")]
        public byte? MonedaId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string NroOrdenCompra { get; set; }

        [ForeignKey("AutorizDetalleId")]
        [InverseProperty("TransporteAutorizacionCargaDetalleTransporteCarga")]
        public virtual TransporteAutorizacionCargaDetalle AutorizDetalle { get; set; }
        [ForeignKey("ProductoPrecioId")]
        [InverseProperty("TransporteAutorizacionCargaDetalleTransporteCarga")]
        public virtual ProductoListaPrecio ProductoPrecio { get; set; }
        [ForeignKey("TipoOperacionId,CargaId")]
        [InverseProperty("TransporteAutorizacionCargaDetalleTransporteCarga")]
        public virtual TransporteCarga TransporteCarga { get; set; }
        [InverseProperty("Registro")]
        public virtual ICollection<TransporteAutorizacionRemito> TransporteAutorizacionRemito { get; set; }
    }
}