// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("LineaId", Name = "IX_TransportePasLineaRecorrido_LineaID")]
    [Index("TipoRecorrido", Name = "IX_TransportePasLineaRecorrido_TipoRecorrido")]
    public partial class TransportePasLineaRecorrido
    {
        public TransportePasLineaRecorrido()
        {
            TransportePasLineaPunto = new HashSet<TransportePasLineaPunto>();
            TransportePasProgramacionDiaDetalle = new HashSet<TransportePasProgramacionDiaDetalle>();
            TransportePasRecorrido = new HashSet<TransportePasRecorrido>();
        }

        [Column("LineaID")]
        public int LineaId { get; set; }
        [Key]
        [Column("RecorridoID")]
        public int RecorridoId { get; set; }
        /// <summary>
        /// Hora Inicio (Cantidad de segundos depues de las 0hs.)
        /// </summary>
        public TimeSpan HoraInicio { get; set; }
        /// <summary>
        /// Hora Final (Cantidad de segundos depues de las 0hs.)
        /// </summary>
        public TimeSpan HoraFinal { get; set; }
        /// <summary>
        /// Distancia en Kilometros
        /// </summary>
        public int Distancia { get; set; }
        public short TipoRecorrido { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [ForeignKey("LineaId")]
        [InverseProperty("TransportePasLineaRecorrido")]
        public virtual TransportePasLinea Linea { get; set; }
        [ForeignKey("TipoRecorrido")]
        [InverseProperty("TransportePasLineaRecorrido")]
        public virtual TransportePasRecorridoTipo TipoRecorridoNavigation { get; set; }
        [InverseProperty("Recorrido")]
        public virtual ICollection<TransportePasLineaPunto> TransportePasLineaPunto { get; set; }
        [InverseProperty("Recorrido")]
        public virtual ICollection<TransportePasProgramacionDiaDetalle> TransportePasProgramacionDiaDetalle { get; set; }
        [InverseProperty("Recorrido")]
        public virtual ICollection<TransportePasRecorrido> TransportePasRecorrido { get; set; }
    }
}