// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Descripcion", Name = "IX_TransporteCubierta_Descripcion")]
    public partial class TransporteCubierta
    {
        public TransporteCubierta()
        {
            OrdenServicioNroSerie = new HashSet<OrdenServicioNroSerie>();
            TransporteCubiertaMovimientoDetalle = new HashSet<TransporteCubiertaMovimientoDetalle>();
        }

        [Key]
        [Column("CubiertaID")]
        public int CubiertaId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// de AlmaNET TransporteCubiertaMedida
        /// </summary>
        [Column("MedidaCubiertaID")]
        public short? MedidaCubiertaId { get; set; }
        /// <summary>
        /// de AlmaNET TransporteCubiertaDiseño
        /// </summary>
        [Column("DiseñoCubiertaID")]
        public short? DiseñoCubiertaId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string NroSerie { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? FechaAlta { get; set; }
        /// <summary>
        /// de AlmaNET TransporteCubiertaCondicion
        /// </summary>
        [Column("CondicionCubiertaID")]
        public int? CondicionCubiertaId { get; set; }
        /// <summary>
        /// de AlmaNET TransporteCubiertaEstado
        /// </summary>
        [Column("EstadoCubiertaID")]
        public byte EstadoCubiertaId { get; set; }
        /// <summary>
        /// Producto Relacionado
        /// </summary>
        [Column("CodigoID")]
        public int CodigoId { get; set; }
        /// <summary>
        /// Vehículo Actual
        /// </summary>
        [Column("VehiculoID")]
        public int? VehiculoId { get; set; }
        /// <summary>
        /// Ubicación Actual - Eje3_Der_2 ,Recambio1
        /// </summary>
        [Column("UbicacionID")]
        public int? UbicacionId { get; set; }
        /// <summary>
        /// Nro de Deposito
        /// </summary>
        [Column("DepositoID")]
        public short? DepositoId { get; set; }
        [Column("TransporteCubiertaTipoID")]
        public short? TransporteCubiertaTipoId { get; set; }
        [Column("MarcaID")]
        public short? MarcaId { get; set; }
        [Column("ProveedorID")]
        public int? ProveedorId { get; set; }
        [Column(TypeName = "money")]
        public decimal? Precio { get; set; }

        [ForeignKey("CodigoId")]
        [InverseProperty("TransporteCubierta")]
        public virtual Producto Codigo { get; set; }
        [ForeignKey("DepositoId")]
        [InverseProperty("TransporteCubierta")]
        public virtual Deposito Deposito { get; set; }
        [ForeignKey("ProveedorId")]
        [InverseProperty("TransporteCubierta")]
        public virtual Proveedor Proveedor { get; set; }
        [ForeignKey("TransporteCubiertaTipoId")]
        [InverseProperty("TransporteCubierta")]
        public virtual TransporteCubiertaTipo TransporteCubiertaTipo { get; set; }
        [ForeignKey("UbicacionId")]
        [InverseProperty("TransporteCubierta")]
        public virtual TransporteCubiertaUbicacion Ubicacion { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransporteCubierta")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
        [InverseProperty("Cubierta")]
        public virtual ICollection<OrdenServicioNroSerie> OrdenServicioNroSerie { get; set; }
        [InverseProperty("Cubierta")]
        public virtual ICollection<TransporteCubiertaMovimientoDetalle> TransporteCubiertaMovimientoDetalle { get; set; }
    }
}