// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Contiene las Liquidaciones realizadas a los Choferes
    /// </summary>
    [Index("FechaDesde", Name = "IX_TransporteCargaLiquidacion_FechaDesde")]
    [Index("FechaHasta", Name = "IX_TransporteCargaLiquidacion_FechaHasta")]
    [Index("FechaYhora", Name = "IX_TransporteCargaLiquidacion_FechaYHora")]
    public partial class TransporteCargaLiquidacion
    {
        public TransporteCargaLiquidacion()
        {
            TransporteAutorizacionCargaDetalle = new HashSet<TransporteAutorizacionCargaDetalle>();
        }

        /// <summary>
        /// Nro ID de liquidacion
        /// </summary>
        [Key]
        [Column("LiquidacionChoferID")]
        public int LiquidacionChoferId { get; set; }
        /// <summary>
        /// Fecha y Hora en q se confecciono la Liquidacion
        /// </summary>
        [Column("FechaYHora", TypeName = "datetime")]
        public DateTime FechaYhora { get; set; }
        /// <summary>
        /// Periodo de la Liquidacion DESDE Fecha
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaDesde { get; set; }
        /// <summary>
        /// Periodo de la Liquidacion HASTA Fecha
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime FechaHasta { get; set; }
        /// <summary>
        /// Chofer al q se le confecciona la Liquidacion
        /// </summary>
        [Column("ConductorID")]
        public int ConductorId { get; set; }
        /// <summary>
        /// Nro Planilla- Comprobante
        /// </summary>
        public int PlanillaNro { get; set; }
        /// <summary>
        /// Tipo de Comprobante
        /// </summary>
        [Column("ComprobateID")]
        public short ComprobateId { get; set; }
        /// <summary>
        /// Detalle referido a la Liquidacion
        /// </summary>
        [Unicode(false)]
        public string Observacion { get; set; }

        [InverseProperty("LiquidacionChofer")]
        public virtual ICollection<TransporteAutorizacionCargaDetalle> TransporteAutorizacionCargaDetalle { get; set; }
    }
}