// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("CargaId", Name = "IX_TransporteCargaConceptosAdicionales_CargaID")]
    [Index("IdconceptoCarga", Name = "IX_TransporteCargaConceptosAdicionales_IDConceptoCarga")]
    public partial class TransporteCargaConceptosAdicionales
    {
        [Key]
        [Column("IDRegistro")]
        public int Idregistro { get; set; }
        [Column("CargaID")]
        public int CargaId { get; set; }
        [Column("IDConceptoCarga")]
        public short IdconceptoCarga { get; set; }
        [Column(TypeName = "money")]
        public decimal Importe { get; set; }
        [Column("FacturaEstadoID")]
        public int FacturaEstadoId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Column(TypeName = "decimal(13, 4)")]
        public decimal? Cantidad { get; set; }
        [Column(TypeName = "money")]
        public decimal? PrecioUnidad { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [ForeignKey("FacturaEstadoId")]
        [InverseProperty("TransporteCargaConceptosAdicionales")]
        public virtual TransporteCargaEstadoFactura FacturaEstado { get; set; }
        [ForeignKey("IdconceptoCarga")]
        [InverseProperty("TransporteCargaConceptosAdicionales")]
        public virtual TransporteCargaAdicionales IdconceptoCargaNavigation { get; set; }
        [ForeignKey("TipoOperacionId,CargaId")]
        [InverseProperty("TransporteCargaConceptosAdicionales")]
        public virtual TransporteCarga TransporteCarga { get; set; }
    }
}