// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("Detalle", Name = "IX_TransportePasLineaPunto_Detalle")]
    [Index("RecorridoId", Name = "IX_TransportePasLineaPunto_RecorridoID")]
    public partial class TransportePasLineaPunto
    {
        [Column("RecorridoID")]
        public int RecorridoId { get; set; }
        public int Orden { get; set; }
        [Key]
        [Column("RegistroID")]
        public int RegistroId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Hora del Primer Arribo
        /// </summary>
        public TimeSpan Hora { get; set; }

        [ForeignKey("RecorridoId")]
        [InverseProperty("TransportePasLineaPunto")]
        public virtual TransportePasLineaRecorrido Recorrido { get; set; }
    }
}