// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EmpleadoId", Name = "IX_TransportePasProgramacionDia_EmpleadoID")]
    public partial class TransportePasProgramacionDia
    {
        public TransportePasProgramacionDia()
        {
            TransportePasProgramacionDiaDetalle = new HashSet<TransportePasProgramacionDiaDetalle>();
        }

        [Column(TypeName = "date")]
        public DateTime FechaDesde { get; set; }
        [Column(TypeName = "date")]
        public DateTime FechaHasta { get; set; }
        [Unicode(false)]
        public string Observacion { get; set; }
        [Column("EmpleadoID")]
        public int EmpleadoId { get; set; }
        [Key]
        [Column("ProgID")]
        public int ProgId { get; set; }

        [ForeignKey("EmpleadoId")]
        [InverseProperty("TransportePasProgramacionDia")]
        public virtual Empleado Empleado { get; set; }
        [InverseProperty("Prog")]
        public virtual ICollection<TransportePasProgramacionDiaDetalle> TransportePasProgramacionDiaDetalle { get; set; }
    }
}