// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("LiquidacionId", Name = "IX_TransportePasLiquidacionDesglose_LiquidacionID")]
    public partial class TransportePasLiquidacionDesglose
    {
        [Column("LiquidacionID")]
        public int LiquidacionId { get; set; }
        /// <summary>
        /// Tipo de Desglose. Proveniente de la base AlmaNET (table: BilletesDesglose)
        /// </summary>
        [Column("DesgloseID")]
        public short DesgloseId { get; set; }
        [Key]
        [Column("LiquidacionDesgloseID")]
        public int LiquidacionDesgloseId { get; set; }
        /// <summary>
        /// Cantidad Desglose
        /// </summary>
        public int CantidadUnidad { get; set; }
        [Column(TypeName = "money")]
        public decimal? Valor { get; set; }
        [Column("MonedaID")]
        public byte? MonedaId { get; set; }

        [ForeignKey("LiquidacionId")]
        [InverseProperty("TransportePasLiquidacionDesglose")]
        public virtual TransportePasLiquidacion Liquidacion { get; set; }
    }
}