// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("EntidadSucId", Name = "IX_TransporteVehiculoDatoCompra_EntidadSucID")]
    [Index("FechaCompra", Name = "IX_TransporteVehiculoDatoCompra_FechaCompra")]
    [Index("NroFactura", Name = "IX_TransporteVehiculoDatoCompra_NroFactura")]
    [Index("ProveedorId", Name = "IX_TransporteVehiculoDatoCompra_ProveedorID")]
    [Index("VehiculoId", Name = "IX_TransporteVehiculoDatoCompra_VehiculoID")]
    public partial class TransporteVehiculoDatoCompra
    {
        [Key]
        [Column("RegistroCpaID")]
        public int RegistroCpaId { get; set; }
        [Column("VehiculoID")]
        public int VehiculoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaCompra { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NroFactura { get; set; }
        [Column(TypeName = "money")]
        public decimal ValorCompra { get; set; }
        [Unicode(false)]
        public string Detalle { get; set; }
        /// <summary>
        /// Nro Sucursal/Entidad
        /// </summary>
        [Column("EntidadSucID")]
        public int? EntidadSucId { get; set; }
        /// <summary>
        /// Quien es el Proveedor al q se compro el Vehiculo
        /// </summary>
        [Column("ProveedorID")]
        public int? ProveedorId { get; set; }

        [ForeignKey("ProveedorId")]
        [InverseProperty("TransporteVehiculoDatoCompra")]
        public virtual Proveedor Proveedor { get; set; }
        [ForeignKey("VehiculoId")]
        [InverseProperty("TransporteVehiculoDatoCompra")]
        public virtual TransporteVehiculo Vehiculo { get; set; }
    }
}