// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    [Index("TipoOperacionId", "CargaId", Name = "IX_TransproteCargaRemito_Carga")]
    [Index("TipoOperacionIdremito", "RemitoId", Name = "IX_TransproteCargaRemitos_Remito")]
    public partial class TransproteCargaRemitos
    {
        [Key]
        [Column("CargaRemitoID")]
        public int CargaRemitoId { get; set; }
        [Column("CargaID")]
        public int CargaId { get; set; }
        [Column("RemitoID")]
        public int RemitoId { get; set; }
        [Column("TipoOperacionID")]
        public byte TipoOperacionId { get; set; }
        [Column("TipoOperacionIDRemito")]
        public byte TipoOperacionIdremito { get; set; }

        [ForeignKey("TipoOperacionId,CargaId")]
        [InverseProperty("TransproteCargaRemitos")]
        public virtual TransporteCarga TransporteCarga { get; set; }
        [ForeignKey("TipoOperacionIdremito,RemitoId")]
        [InverseProperty("TransproteCargaRemitos")]
        public virtual TransporteRemitos TransporteRemitos { get; set; }
    }
}