// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Indical la Ubicacion Actual de cada Cubierta
    /// </summary>
    [Index("Descripcion", Name = "IX_TransporteCubiertaUbicacion_Descripcion")]
    public partial class TransporteCubiertaUbicacion
    {
        public TransporteCubiertaUbicacion()
        {
            TransporteCubierta = new HashSet<TransporteCubierta>();
            TransporteCubiertaMovimientoDetalle = new HashSet<TransporteCubiertaMovimientoDetalle>();
        }

        [Key]
        [Column("UbicacionID")]
        public int UbicacionId { get; set; }
        /// <summary>
        /// Descripcion Ubicacion Eje3_Der_2 ,Recambio1
        /// </summary>
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("Ubicacion")]
        public virtual ICollection<TransporteCubierta> TransporteCubierta { get; set; }
        [InverseProperty("UbicacionAnterior")]
        public virtual ICollection<TransporteCubiertaMovimientoDetalle> TransporteCubiertaMovimientoDetalle { get; set; }
    }
}