// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    /// <summary>
    /// Turnos de Trabajo que tiene la empresa 
    /// </summary>
    [Index("Descripcion", Name = "IX_EmpleadoTurno_Descripcion")]
    public partial class Turno
    {
        public Turno()
        {
            AccesoMensaje = new HashSet<AccesoMensaje>();
            Empleado = new HashSet<Empleado>();
            EmpleadoAcceso = new HashSet<EmpleadoAcceso>();
            EmpleadoTurno = new HashSet<EmpleadoTurno>();
            ProduccionOrdenItemProgramacion = new HashSet<ProduccionOrdenItemProgramacion>();
            ProduccionProgramacionItem = new HashSet<ProduccionProgramacionItem>();
        }

        [Key]
        [Column("TurnoID")]
        public short TurnoId { get; set; }
        /// <summary>
        /// Hora de entrada del personal
        /// </summary>
        public TimeSpan HoraEntrada { get; set; }
        /// <summary>
        /// Hora de entrada para Almuerzo
        /// </summary>
        public TimeSpan? HoraEntradaReceso { get; set; }
        /// <summary>
        /// Hora salida del almuerzo
        /// </summary>
        public TimeSpan? HoraSalidaReceso { get; set; }
        /// <summary>
        /// Hora salida
        /// </summary>
        public TimeSpan HoraSalida { get; set; }
        /// <summary>
        /// Nocturno-Diurno, etc..
        /// </summary>
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        /// <summary>
        /// Cantidad Minutos Tolerancia
        /// </summary>
        public byte? Tolerancia { get; set; }
        /// <summary>
        /// Indica q este turno ya no se utiliza
        /// </summary>
        public bool? Inhabilitado { get; set; }

        [InverseProperty("Turno")]
        public virtual ICollection<AccesoMensaje> AccesoMensaje { get; set; }
        [InverseProperty("Turno")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [InverseProperty("Turno")]
        public virtual ICollection<EmpleadoAcceso> EmpleadoAcceso { get; set; }
        [InverseProperty("Turno")]
        public virtual ICollection<EmpleadoTurno> EmpleadoTurno { get; set; }
        [InverseProperty("Turno")]
        public virtual ICollection<ProduccionOrdenItemProgramacion> ProduccionOrdenItemProgramacion { get; set; }
        [InverseProperty("Turno")]
        public virtual ICollection<ProduccionProgramacionItem> ProduccionProgramacionItem { get; set; }
    }
}