// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class UnidadFacturacionEquipoTomaEstado
    {
        [Key]
        [Column("TomaEstadoID")]
        public int TomaEstadoId { get; set; }
        public int UltimoRegistro { get; set; }
        public int? RegsitroActual { get; set; }
        [StringLength(150)]
        public string Detalle { get; set; }
        [Column("EquipoID")]
        public int EquipoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        /// <summary>
        /// Periodo en el que se factura
        /// </summary>
        [Column("PeriodoID")]
        public int? PeriodoId { get; set; }

        [ForeignKey("EquipoId")]
        [InverseProperty("UnidadFacturacionEquipoTomaEstado")]
        public virtual UnidadFacturacionEquipo Equipo { get; set; }
        [ForeignKey("PeriodoId")]
        [InverseProperty("UnidadFacturacionEquipoTomaEstado")]
        public virtual UnidadFacturacionPeriodo Periodo { get; set; }
    }
}