// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class UnidadFacturacionItem
    {
        /// <summary>
        /// Indica la COnexion O Mensualidad
        /// </summary>
        [Column("UnidadFactID")]
        public int UnidadFactId { get; set; }
        [Key]
        [Column("UF_ItemID")]
        public int UfItemId { get; set; }
        [Column("UF_ConceptoID")]
        public int UfConceptoId { get; set; }
        /// <summary>
        /// Equipo cuyo contador determina la cantidad a facturar en este Item
        /// </summary>
        [Column("EquipoID")]
        public int? EquipoId { get; set; }

        [ForeignKey("EquipoId")]
        [InverseProperty("UnidadFacturacionItem")]
        public virtual UnidadFacturacionEquipo Equipo { get; set; }
        [ForeignKey("UfConceptoId")]
        [InverseProperty("UnidadFacturacionItem")]
        public virtual UnidadFacturacionConceptos UfConcepto { get; set; }
        [ForeignKey("UnidadFactId")]
        [InverseProperty("UnidadFacturacionItem")]
        public virtual UnidadFacturacion UnidadFact { get; set; }
    }
}