// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class UsuarioAutorizacionSolicitud
    {
        [Key]
        [Column("SolicitudAutorizacionID")]
        public int SolicitudAutorizacionId { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string MensajeSolicitud { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string MensajeAutorizacion { get; set; }
        [Column("AprobacionTipoID")]
        public byte? AprobacionTipoId { get; set; }
        [Column("AlmaUserID")]
        public int AlmaUserId { get; set; }
        [Column("IDRegistroPrimario")]
        public int IdregistroPrimario { get; set; }
        [Column("TipoSolicitudAutorizacionID")]
        public short TipoSolicitudAutorizacionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }

        [ForeignKey("AlmaUserId")]
        [InverseProperty("UsuarioAutorizacionSolicitud")]
        public virtual Usuario AlmaUser { get; set; }
        [ForeignKey("TipoSolicitudAutorizacionId")]
        [InverseProperty("UsuarioAutorizacionSolicitud")]
        public virtual UsuarioAutorizacionSolicitudTipo TipoSolicitudAutorizacion { get; set; }
    }
}