// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DRR.Core.DBEmpresaEjemplo.Models
{
    public partial class VendedorRepresentada
    {
        [Key]
        [Column("VendedorRepretsentadaID")]
        public int VendedorRepretsentadaId { get; set; }
        [Column("ProveedorID")]
        public int ProveedorId { get; set; }
        [Column("VendedorID")]
        public int VendedorId { get; set; }
        [Column(TypeName = "decimal(7, 3)")]
        public decimal? Comicion { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Detalle { get; set; }

        [ForeignKey("ProveedorId")]
        [InverseProperty("VendedorRepresentada")]
        public virtual Proveedor Proveedor { get; set; }
        [ForeignKey("VendedorId")]
        [InverseProperty("VendedorRepresentada")]
        public virtual Vendedor Vendedor { get; set; }
    }
}